### ISSUE TITLE
experimental Macvlan: Explicit endpoint MAC address is not being set

### ISSUE THREAD

**Issue by nerdalert** [docker/libnetwork#1009]
In the `CreateEndpoint()` of the Macvlan driver, the user specified `--mac-address` or the libnetwork generated MAC address are being set but not honored somewhere along the lines. Netlink does allow the MAC to be set for a Macvlan type slave. Ipvlan uses the same MAC address as the parent and we reject user specified `--mac-address` setting there.

```
	ep := &endpoint{
		id:     eid,
		addr:   ifInfo.Address(),
		addrv6: ifInfo.AddressIPv6(),
		mac:    ifInfo.MacAddress(),
	}
	if ep.addr == nil {
		return fmt.Errorf("create endpoint was not passed an IP address")
	}
	if ep.mac == nil {
		ep.mac = netutils.GenerateMACFromIP(ep.addr.IP)
		if err := ifInfo.SetMacAddress(ep.mac); err != nil {
			return err
		}
	}
```

Link to the relevant [codeblock](https://github.com/docker/libnetwork/blob/master/drivers/macvlan/macvlan_endpoint.go#L25)

**Comment by nerdalert** [comment]
Update: the patch

**Comment by kunalkushwaha** [comment]
I guess this is fixed now?

**Comment by aboch** [comment]
Yes, this now works:
```
$ docker version | grep Version
 Version:      1.13.0-dev
 Version:      1.13.0-dev
$ 
$ docker network create -d macvlan mc
bea5e21d0934445e088d705de956b11c104a5ce43d55f1b7671c9fafe423c2f5
$ 
$ docker run --mac-address aa:bb:cc:ee:44:55 --network mc --rm busybox ifconfig eth0 | grep HWaddr
eth0      Link encap:Ethernet  HWaddr AA:BB:CC:EE:44:55  
$ 
```

Closing.
