### ISSUE TITLE
Dedicated IP for container

### ISSUE THREAD

**Issue by Hostile** [docker/libnetwork#1013]
Hi, is that done now? How can I run conteiner lets say debian image with dedicated IP (my host give me 100 ips)

point me in right direction please

**Comment by YujiOshima** [comment]
You can use --ip option to choose ip address of a container in you defined network.
https://docs.docker.com/engine/reference/commandline/run/#connect-a-container-to-a-network-net

**Comment by aboch** [comment]
Closing as docker documentation contains the necessary information to statically assing an IP address to a container connected to a user created network.
