### ISSUE TITLE
Experimental vlan drivers: null v4 IPAM slice can cause a panic

### ISSUE THREAD

**Issue by nerdalert** [docker/libnetwork#1018]
In the case of disabling IPAM `--ipam-driver=null` or a 3rd party IPAM driver sending an empty v4 slice will create a panic. `docker network create -d (ipvlan||macvlan) --ipam-driver=null  ipv` currently triggers a panic.

Patching with:
```
	// reject a null v4 network
	if len(ipV4Data) == 0 || ipV4Data[0].Pool.String() == "0.0.0.0/0" {
		return fmt.Errorf("ipv4 pool is empty")
	}
```

**Comment by domq** [comment]
Hmm, what if people want to [use macvlan with Docker, but decide on IP addresses themselves](https://forums.docker.com/t/docker-networking-without-ip-addresses-for-sdn/8996/7)?

**Comment by joakim-tjernlund** [comment]
Seems like this patch makes it impossible to use --ipam-driver=null ?
I get above error msg  and cant find a way around it

**Comment by gr3m1in** [comment]
Same problem here
Is there any update on this artificial limitation?
What is the approach to get rid of ipam with macvlan now?

**Comment by gr3m1in** [comment]
By the way, if i comment out the change for macvlan and build from sources, then network creation succeeds with no crashes.
So i assume that ipv4 probably is only required for ipvlan... It is ip based obviously
