### ISSUE TITLE
ipvlan/macvlan driver observations

### ISSUE THREAD

**Issue by cpuguy83** [docker/libnetwork#1020]
Tested out the macvlan/ipvlan drivers, some comments wrt the UX:
- I seem to be able to pass any option to the driver (e.g.`-o foo=bar`) and it won't ever error out... I would expect an invalid option to cause network creation to error.
- `-o macvlan_mode` and `-o ipvlan_mode` seems redundant since the driver is specifically `ipvlan` and `macvlan`. Opt name can just be `mode`

I'll have to play with it some more, but initially I had some issues b/c I didn't specify a gateway. Maybe read this from the host for when it's not specified? Currently no gateway is akin to `--internal` w/o giving any particular info to the user.

Then I had to specify an ip-range so it didn't overlap existing addresses...for instance, my host interface was 172.17.0.2, so the container interface took 172.17.0.1.

modprobe errors could be improved, right now it just copies directly from modprobe, might be nice to say something like "ipvlan kernel module needs to be loaded" and leave it at that.
Alternatively, maybe don't modprobe at all.

ping @nerdalert

**Comment by nerdalert** [comment]
Thanks for the feedback @cpuguy83 

- Think you have a good point on `$driver_mode=` vs. `mode=`. 

- You also nailed the modprobe. We had already patched it prior to vendoring to better present kernel requirements:

```
	kv, err := kernel.GetKernelVersion()
	if err != nil {
		return fmt.Errorf("failed to check kernel version for %s driver support: %v", macvlanType, err)
	}
	// ensure Kernel version is >= v3.9 for macvlan support
	if kv.Kernel < macvlanKernelVer || (kv.Kernel == macvlanKernelVer && kv.Major < macvlanMajorVer) {
		return fmt.Errorf("kernel version failed to meet the minimum macvlan kernel requirement of %d.%d, found %d.%d.%d",
			macvlanKernelVer, macvlanMajorVer, kv.Kernel, kv.Major, kv.Minor)
	}
```

Same for Ipvlan leaving a user message that looks like this: `Error response from daemon: kernel version failed to meet the minimum ipvlan kernel requirement of 4.2, found 4.1.1`


- re: gateway, if the gateway isn't specified, it will it will use the first usable address on the network via default IPAM functionality. If you get a second can you verify you are getting the first usable address on the `--subnet`?

```
# docker network create -d macvlan \
     --subnet=192.168.1.0/24 \
     -o parent=eth1 mcv \
     && docker run --net=mcv -it --rm alpine /bin/sh
021f0e4870578a8b746360e0faab262f30b5fcaebbb2c5296b371511e51c1ce8

/ # ip route
default via 192.168.1.1 dev eth0
192.168.1.0/24 dev eth0  src 192.168.1.2
```

In the case of the following where the default namespace route is `172.16.86.2` to @cpuguy83 point it would be assigned an invalid gateway of `172.16.86.1`

```
# Default namespace gateway is 172.16.86.2
# ip route
default via 172.16.86.2 dev eth0
10.1.1.0/24 dev eth2  proto kernel  scope link  src 10.1.1.251
172.16.86.0/24 dev eth0  proto kernel  scope link  src 172.16.86.151
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.0.1
192.168.1.0/24 dev eth1  proto kernel  scope link  src 192.168.1.251

# docker network create -d macvlan \
     --subnet=172.16.86.0/24 \
      -o parent=eth0 mcv && docker run --net=mcv -it --rm alpine /bin/sh
2b7b961def73b4ea9bbf8e3d4784d136971b6ed521ae6331f718b0edbd8d45bf
# ip route
default via 172.16.86.1 dev eth0
172.16.86.0/24 dev eth0  src 172.16.86.2
```

- On overlapping `eth` libnetwork offers `--aux-address` to blacklist an IP assignment. In the case of the following, `172.16.86.1` is blacklisted, `172.16.86.2` is the gateway and the first IPAM assigned address is `172.16.86.3`

```
docker network create -d macvlan \
    --subnet=172.16.86.0/24 \
    --gateway=172.16.86.2 \
     -o parent=eth0 mcv && docker run --net=mcv -it --rm alpine /bin/sh
```

- Along with `--aux-address=` you can also use `--ip-range=` to specify a sub-pool to allocate dynamic addresses from. In the following the container will be assigned `172.16.86.128`.

```
# docker network create -d macvlan \
     --subnet=172.16.86.0/24 \
     --gateway=172.16.86.2 \
     --ip-range=172.16.86.128/25 \
      -o parent=eth0 mcv && docker run --net=mcv -it --rm alpine /bin/sh
7a656c46bd1c5204da52751a901931c5b3e0c9bbea2f04ef3ed173edceb0883a

 # ip a show eth0

14: eth0@if15: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue state UP
    link/ether 02:42:ac:10:56:80 brd ff:ff:ff:ff:ff:ff
    inet 172.16.86.128/24 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:acff:fe10:5680/64 scope link
       valid_lft forever preferred_lft forever
```

Will get issues opened for `--mode`. Also on `--gateway` if we want to entertain overriding the default IPAM drivers. 

Thanks again, great feedback!

**Comment by cpuguy83** [comment]
I did something like so:

```
$  docker network create -d macvlan --subnet 172.17.0.0/16 --ip-range 172.17.2.0/24 -o parent=eth0 test
```

The gateway was set to `172.17.2.0` where as I would expect it to be `172.17.0.1`

**Comment by cpuguy83** [comment]
It would be cool if it were possible to read the subnet and default route of the parent interface when `--subnet` and `--gateway` are not specified.

**Comment by cpuguy83** [comment]
I think most of this is not relevant anymore.
