### ISSUE TITLE
Default IPAM driver does not adhere to CNM lifecycle

### ISSUE THREAD

**Issue by umairmufti** [docker/libnetwork#1038]
The [documented CNM lifecycle](https://github.com/docker/libnetwork/blob/master/docs/design.md#cnm-lifecycle) states:

> But LibNetwork keeps hold of the IP addresses as long as the endpoint is still present and will be reused when the container(or any container) joins again. This ensures that the container's resources are reused when they are Stopped and Started again.

However, the observed behavior is that IPs are released when containers are _stopped_ when using the defualt IPAM driver.

```
$ docker run -itd --name=container1 busybox
22be4588ba2e724ace1eb8af7408f028d1c558f73423350920be6710f77fb125
```

```
$ docker exec container1 hostname -i
172.17.0.2
```

```
$ docker run -itd --name=container2 busybox
fadc2f84f29a893d55b20a70af51d5552510a49d4895b2169cbfeb1b33b23850
```

```
$ docker exec container2 hostname -i
172.17.0.3
```

```
$ docker stop container1
container1
```

```
$ docker run -itd --name=container3 busybox
07d06afc15f3f5055e804e44f2c557090253ab4bb004a426c397c90e519a3d34
```

```
$ docker exec container3 hostname -i
172.17.0.2
```

```
$ docker start container1
container1
```

```
$ docker exec container1 hostname -i
172.17.0.4
```

```
$ docker info 2>/dev/null | egrep '(Version|System)'
Server Version: 1.10.2
 Library Version: 1.02.107-RHEL7 (2015-10-14)
Kernel Version: 3.10.0-327.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.2 (Maipo)
```

**Comment by aboch** [comment]
Thanks @umairmufti, the problem is that the document is out dated. An endpoint having independent life cycle from container was a concept from experimental libnetwork, which was later dropped. 
Now, the endpoint is created/destroyed along with the container start/stop. So, when a container is stopped the endpoint is actually destroyed, and libnetwork inform the ipam driver to release the endpoint's address(es), as you have observed.

Documentation needs to be fixed.

**Comment by umairmufti** [comment]
Thanks for clarification @aboch. Is there any way to achieve the documented behavior? It seems more logical than destroying the endpoint when the container is stopped. If the model itself has changed, then presumably _any_ IPAM implementation would exhibit the same behavior.

**Comment by mavenugo** [comment]
@umairmufti @aboch though the document is slightly out-dated. the CNM behavior has not changed. CNM continues to provide the same Join/Leave & Create/Delete abstractions which the applications of CNM can make use of independently. With the latest UX, docker decided to use Create/Join & Leave/Delete as a pair. But CNM (libnetwork API) itself is not dictating this behavior.
