### ISSUE TITLE
clarification with a point mentioned in design.md

### ISSUE THREAD

**Issue by sainath14** [docker/libnetwork#1047]
"The answer is based on the fact that Endpoint represents a Service which may or may not be backed by a Container. When an Endpoint is created, it will have its resources reserved so that any container can get attached to the endpoint later and get a consistent networking behaviour."

From the above statement looks like a container can make use of an existing endpoint.
Is there an api to create only endpoint? And to attach a container to an existing endpoint?

**Comment by chenchun** [comment]
@sainath14 you may refer to https://github.com/docker/libnetwork/issues/1038

> CNM continues to provide the same Join/Leave & Create/Delete abstractions which the applications of CNM can make use of independently. With the latest UX, docker decided to use Create/Join & Leave/Delete as a pair. But CNM (libnetwork API) itself is not dictating this behavior.
