### ISSUE TITLE
Using SIGHUP to reload cluster configuration causes `host` and `none` networks to disappear until restart

### ISSUE THREAD

**Issue by avuserow** [docker/libnetwork#1051]
On Docker 1.11 RC1, the `host` and `none` networks disappear when signaling the engine with SIGHUP after going from no configuration in `/etc/docker/daemon.json` to having cluster options (specifically, `cluster-advertise`, `cluster-store`, and `cluster-store-opts`). They reappear after a daemon restart.

**Comment by aboch** [comment]
Fixed by #1049
