### ISSUE TITLE
Proposal: support multiple A-records for redundant container aliases on a network

### ISSUE THREAD

**Issue by jbalonso** [docker/libnetwork#1054]
For basic load balancing and service discovery, it would help if a container could discover (via the embedded DNS) the addresses of *all* containers on a network providing a service (such as might be given in the form of an alias when those containers were joined to the network). The lack of this capability is particularly glaring when using `docker-compose scale`, where you'd naively expect the IP address of every container started as part of a service to be obtainable by a DNS query for the name of the service.

I have seen discussion for such support in #737, where the discussion hinted that #767 would cover the matter, but both of these issues appear to have closed without this capability appearing.

(Alternatively: if I'm missing something obvious, I'd *love* to hear about it.)

**Comment by mavenugo** [comment]
@jbalonso the support for multiple A-records made into docker for the upcoming 1.11 release via https://github.com/docker/libnetwork/pull/974. Infact you can try the 1.11.0-RC2 now and give us feedback : https://github.com/docker/docker/releases/tag/v1.11.0-rc2. Please do :)

**Comment by sanimej** [comment]
@jbalonso 1.11 RC2 has support for AAAA records as well. If you can give it a try and let us know of any issues you see that would be useful.

**Comment by jbalonso** [comment]
\o/

Thanks for the pointer: I searched pretty hard for evidence that this wasn't forgotten, but most discourse on the matter was tangled up with the old links feature... and my concerns were scattered across ``docker-engine``, ``docker-compose``, and here.

At present, I have an uncomfortable workaround. I'd test 1.11.0-rc2, but I'm on a project with a deadline. :disappointed:

I'm not certain what the issue closing convention is here, but in case the convention is "close when it ships", I'll leave this open for you.

**Comment by thaJeztah** [comment]
I think this can be closed, now that docker 1.11 has shipped

**Comment by sanimej** [comment]
@thaJeztah Yes. Thanks.
