### ISSUE TITLE
DNS message ID mismatch

### ISSUE THREAD

**Issue by vikstrous** [docker/libnetwork#1070]
Once in a while when trying to resolve a hostname from within a docker container using a Go binary I get "DNS message ID mismatch". This is happening in docker 1.11-rc2.

You can reproduce it with this script:

```go
package main

import (
    "fmt"
    "net"
)

func main() {
    for {
        _, err := net.LookupHost("google.com")
        if err != nil {
            fmt.Println(err)
        }
        fmt.Print(".")
    }
}
```

**Comment by sanimej** [comment]
Fixed by #1073
