### ISSUE TITLE
How do drivers set routes in the sandbox?

### ISSUE THREAD

**Issue by tomdee** [docker/libnetwork#112]
There is a TODO in the Sandbox.Info code (https://github.com/docker/libnetwork/blob/043a23ae122fa79bd51dfe6ee7feed2e1645a91c/sandbox/sandbox.go#L48) but nothing in the design docs/wiki about how this will be implemented.

For my use case, I need to be able to create the following kinds of routes in the sandbox
* `ip route add [GATEWAY_IP] dev [DEVICE]`
* `ip route add default via [GATEWAY_IP] dev [DEVICE]`

Will that be possible?

**Comment by tomdee** [comment]
The current code allows the default route to be set but it's still missing the ability to add static routes. I've raised a PR #180 to track the implementation.

**Comment by squaremo** [comment]
@tomdee I'm guessing this can be closed now #180 is merged?

**Comment by tomdee** [comment]
Yep, closing.
