### ISSUE TITLE
Proposal: pluggable embedded dns per network 

### ISSUE THREAD

**Issue by mariusGundersen** [docker/libnetwork#1124]
It would be useful to have a way to replace the embedded dns server on a network. Currently it's possible to specify a dns server for the container, but that is only called after the built in dns server. This means that some names might be matched by the embedded dns server when I want my own dns server to return a different result. Since dns is the primary form of service discovery in docker, it is something that I want to control. 

The embedded dns server should be per network and would be notified of connections and disconnections to the network. It must expose and endpoint for querying A records and is free to decide what result to return to these queries.

**Comment by bboreham** [comment]
https://github.com/docker/docker/issues/22004 is basically the same issue you are citing.

Have you thought about the situation where a container is attached to multiple networks?  Sadly the way DNS works you are only allowed to give one, complete, answer; you can't say "I don't know everything, ask the next guy".

**Comment by bboreham** [comment]
Referencing #936
