### ISSUE TITLE
Non-overlapping ip address space for overlay networks

### ISSUE THREAD

**Issue by chenchun** [docker/libnetwork#1128]
It seems currently overlay networks shares the `GlobalDefault` address space and libnetwork doesn't provide any interface to create a per-network address space. I think an overlay network should have the ability to create its private ip address space so that we don't have to worry about running out of ip ranges/ip addresses for multi tenant use cases.

**Comment by jmzwcn** [comment]
"option --subnet" is what you expect?

**Comment by chenchun** [comment]
Not exactly. You may refer to https://github.com/docker/libnetwork/issues/489

**Comment by vikaschoudhary16** [comment]
Hi Chun Chen,

I have created a PR for addressing this issue, PTAL.

https://github.com/docker/docker/pull/23150


Regards
Vikas

**Comment by thaJeztah** [comment]
Per https://github.com/docker/docker/pull/23150#issuecomment-237911402, it looks like this issue should be closed (at least for now)

**Comment by mrjana** [comment]
Closing this for now. Will revisit once we have clarity on multi-tenancy at docker level.
