### ISSUE TITLE
Clarification: Containers requesting a dynamic IP from dhcp server

### ISSUE THREAD

**Issue by sainath14** [docker/libnetwork#1139]
Does libnetwork support dynamic IPs for endpoints? For example, containers using macvlan interfaces behind a physical interface, is infrastructure/code in place to request a dynamic IP from the local DHCP server? 
Current drivers for bridge, overlay request IPs for endpoints from default IPAM driver. Please correct me if I am wrong.

**Comment by chenchun** [comment]
Libnetwork does not have a builtin DHCP IPAM driver currently. But you can write a DHCP IPAM plugin if you like.

**Comment by dvenza** [comment]
@chenchun No, you cannot: #843 
There is no way to handle lease renewal.
