### ISSUE TITLE
macvlan / ipvlan in a Swarm environment

### ISSUE THREAD

**Issue by fredhsu** [docker/libnetwork#1150]
Hi guys,
When issuing the `network create` command against Swarm, macvlan or ipvlan will try to use the same parent interface name on all hosts.  However, often hosts will have different interface names, due to linux distributions, naming conventions, or bond interfaces.  It would be great to have a way to auto-choose a parent interface, while still allowing manual configuration when needed.

**Comment by mavenugo** [comment]
@fredhsu in addition to the parent-interface, we still also have another issue wrt ipam config that is per-host. Also service discovery is not out-of-the-box. Though these vlan drivers are good independently, there are such integration issues with multi-host requirements.

am starting to think if we can make these drivers as plugins (instead of built-in driver) and provide more configuration options to support many use-cases.

@nerdalert wdyt ?

**Comment by nerdalert** [comment]
Regarding Macvlan IPAM I think DHCP is reasonable one for Macvlan. 

RE: plugins. When we tested them as plugins in skunkworks the feedback was they would be useful as native drivers. What is the difference between Macvlan/Ipvlan bridge/L2 modes from Bridge mode drivers other then being a lot easier for the user? 

I like @fredhsu suggestion of auto, it is similar to issue #1020 @cpuguy83 mentioned.

**Comment by mavenugo** [comment]
@nerdalert the biggest difference is that, bridge is essentially a single-host driver and hence the connectivity and service discovery requirements are within that specific host.
But the purpose of macvlan/ipvlan is to provide underlay connectivity across multiple-hosts in a swarm cluster. The current implementation of keeping it single host will fail the service-discovery requirements and hence applications that expect to work on top of Swarm + vlan drivers will fail.
If we make this a multi-host driver, then we have to start dealing with per-host ipam configurations especially if we have to support l3-mode without the /32 route exchange.
Also the question of pluggable Control-plane is a challenge if it is a built-in driver.

**Comment by fredhsu** [comment]
I agree with @nerdalert on using DHCP as a IPAM solution for L2 macvlan in particular.  I believe for most network operators this is a clean and well understood way to add containers to the network.  If we use DHCP to assign IP addresses to the containers does that pose a problem for service discovery?

Layer 3 IPVLAN is a different beast that I still need to play with more.

I'm not clear on the differences between a plugin driver from Docker and a built-in driver.  I do think that macvlan and ipvlan are valuable options for people to have out of the box.

**Comment by mavenugo** [comment]
@fredhsu i do agree that having built-in ipvlan/macvlan is useful. But, we need to solve the above problems before making it official. DHCP driver is useful. But we dont have a built-in DHCP driver. Also, making DHCP driver as a mandatory requirement for ipvlan/macvlan driver is against the composability requirement for the built-in network drivers. Hence, we should come up with a solution for providing per-host subnet/range allocation for these vlan drivers. Also, with such a local-scoped plugin, the SD cannot work cross-host and hence we have to make these drivers global-scoped driver.

**Comment by fredhsu** [comment]
@mavenugo Thanks for the clarification.. I can see how you would not want DHCP as a hard requirement, but a useful option.. I've deployed using a smaller subnet scope for the hosts and the iprange option.. i.e. break my /24 into /26's and give chunks for ranges.  But once again this wouldn't work in a swarm setup.  It seems logical that in order for the driver to be swarm friendly it would need to be globally scoped, or maybe just the IPAM could be globally scoped?

**Comment by klynch** [comment]
Just to clarify, if you manually break the network into smaller host-local networks with the same label (e.g. break a /16 into a unique /24 per swarm node), does Swarm not identify them as the same cluster and refuse to schedule on them?

If it is just Swarm service discovery and global routing that is the issue, I think that is easier to manage with traditional discovery mechanisms, so long as orchestration scheduling and L2 networking work.
