### ISSUE TITLE
Issue: not able to create overlay network on a swarm cluster

### ISSUE THREAD

**Issue by sainath14** [docker/libnetwork#1168]
Error response from daemon: error getting pools config from store: store for address space GlobalDefault not found

Below is the configuration I am trying to create overlay network on

Two Virtual Box VMs node0 and node1
node0 - swarm manager and consul
node1- swarm agent

swarm manager able to see node1 as the node in the cluster

docker daemon on both nodes with the following command
/usr/local/bin/docker daemon -D -g /var/lib/docker -H unix:// -H tcp://0.0.0.0:2376 --label provider=virtualbox -s aufs

On node1 - tried to create overlay network

docker network create --driver overlay --subnet=10.0.9.0/24  my-net

Is there anything missing to create overlay network with the above config

**Comment by mavenugo** [comment]
@sainath14 As of 1.11, overlay networking requires `--cluster-store` & `--cluster-advertise` daemon options. Pls read : https://docs.docker.com/engine/userguide/networking/get-started-overlay/.

**Comment by sainath14** [comment]
so following the document, there should be an existing cluster store container running already on a different docker host?

**Comment by mavenugo** [comment]
@sainath14 yes. or even the local host ...

**Comment by jmzwcn** [comment]
@mavenugo 
--cluster-advertise is mandatory? Why I did successfully without it...

**Comment by sainath14** [comment]
cluster advertise is not mandatory if you run a swarm container and use join in swarm

**Comment by jmzwcn** [comment]
Actually in the latest 1.12-rc2, seems the both are not required any more?
