### ISSUE TITLE
2 misterious endpoints on fresh setup 

### ISSUE THREAD

**Issue by doronp** [docker/libnetwork#1177]
Hi,

During investigation of 
https://github.com/docker/swarm/issues/2149

I've used vagrant to create 3 VMs all running latest docker
I ran consul on 1 of those and used the other 2 as engines using that consul 

I ran swarm on my host and create networks to investigate.

This issue which may end up as question is

Before doing any operation with the described setup I had those networks listed as result of swarm list networks:

NETWORK ID          NAME                      DRIVER
2da78b8447da        docker1/none              null  
f368d31e4f1b        docker1/host              host  
1f549a1b7b40        docker1/docker_gwbridge   bridge  
88ceb09718b7        docker2/host              host  
7830bbe345fc        docker2/docker_gwbridge   bridge  
0f79475d3fff        docker2/bridge            bridge  
d62982382f49        docker2/none              null  
88796a8d8422        docker1/bridge            bridge    

But in the endpoint in the consul web ui I had 2 more endpoint in which the IDs did not match any of the networks(the other did)

What are those?

**Comment by mavenugo** [comment]
@doronp It seems that you have created overlay networks in the past and removed them which results in the current state as described above. The endpoints that doesnt belong to any of these networks could be stale endpoints left in consul due to various reasons. Infact we resolved one such stale endpoint issue recently : https://github.com/docker/libnetwork/pull/1157

The above fix will help in cleaning up stale endpoints during ungraceful daemon restart. From your description above, since there are no overlay networks, I assume you have deleted the network and hence these endpoints will be left stale in the consul store with no way to clean it up even with `docker network disconnect -f {network} {endpoint-name}` since the network is now gone. But at the same time, these endpoints will not cause any harm in this case, as the corresponding network isnt present.

**Comment by doronp** [comment]
@mavenugo While I am certain that I got stale endpoints on a fresh system, I admit that since I ran consecutive experiments those logs may be from the wrong state. I will repeat the experiment and paste the results again If the number and names of endpoints is equal in the output of the network ls and in the consul UI I will close this issue.

**Comment by doronp** [comment]
@mavenugo here goes:

network ls output on swarm+2 nodes with consul all fresh:

f05c4a17bdd7        docker2/none        null                
436073bf9ece        docker2/host        host                
4b7b9c2b2b52        docker1/host        host                
622c4612fed0        docker1/bridge      bridge              
4bab51079934        docker1/none        null                
e69aa09e6a4e        docker2/bridge      bridge

(6 networks)

on my consul UI I got 8 endpoints
436073bf9ecea3af183dbc90f828620dd0f0e69b3b1786569429b4e94052b71b   V
4b7b9c2b2b525908ba534ad3c2880430c05f47e0f9764053c04152b617098ebc  V
4bab5107993442503cb83fb3f04fd9a61271e41e0d9be56c4b8182944101e97c   V
622c4612fed0fb286df2ff35f2d5158f0c17d4a953dc7a7a621a563aaaef3151        V
b7a17c62a8e48630eda3b88ad0c002c49c5fd42d9e07bebea8152a19ec79f4b8
e69aa09e6a4ed4e6cc72032bd43235c47c7c6f7da20eacb4f0d72983e11958ac   V
f05c4a17bdd7d0245ccdcbb2c996aef4158e4b8c887b9c04b68729980e9ba0de   V
f8783013017028011cf6f4828fd61dbfd9d1e1be7bfc708410c578845d513d4a

(8 endpoints)

Those not marked with V are the ones I wonder about.
Any ideas?

**Comment by mavenugo** [comment]
@doronp swarm or docker-engine will not create endpoints in overlay network by default. That essentially means, these endpoints are left over states in the consul KV-Store. Are you using the same `--data-dir` of consul from the previous attempt ? that would answer why you see these stale endpoints.

**Comment by doronp** [comment]
@mavenugo Both dockers and consul are running on a VM created with vagrant (Ubuntu)
In order to create the results above I did vagrant destroy to all of those then started them ran the docker engines to use the consul - the consul lives in a container in the dedicated VM for consul.
So unless I miss something the answer to your question would be no.

I can share My Vagrant environment with you along with steps to reproduce my experiment if you wish.
