### ISSUE TITLE
Tap adaptors are moved back to root namespace *after* the Leave endpoint is called

### ISSUE THREAD

**Issue by wrouesnel** [docker/libnetwork#1187]
In manipulating tap adaptors with a network plugin, I've found that libnetwork does not destroy them when a container is removed from a network, but rather they pop back into the root network namespace with their original name - which would be fine, except that this happens _after_ the Leave endpoint response is sent.

This means that without a separate GC process to clean up my tap adaptors, they get orphaned.

**Comment by aboch** [comment]
Your driver can delete the interface on the `DeleteEndpoint()` call which is invoked after the `LeaveEndpoint()` and after the container interface is moved back to the host namespace. This is in fact what the internal network drivers do.

**Comment by wrouesnel** [comment]
Ah, much clearer - though a little odd, since in cases where you don't want to leave the interface lying around in the host namespace, you try not to create it till the container is ready for it.
