### ISSUE TITLE
daemon ungraceful shutdown during starting make daemon failed to start next time with Error initializing network controller

### ISSUE THREAD

**Issue by coolljt0725** [docker/libnetwork#1188]
see https://github.com/docker/docker/issues/22834

**Comment by aboch** [comment]
See #1130

**Comment by coolljt0725** [comment]
@aboch  with #1130  I still can see this happening. Our case is that after the daemon fail to start with timeout using systemd on a heavy-load machine(the cpu is always 100%), the daemon ended with failed to start with `Address already in use`.

**Comment by aboch** [comment]
@coolljt0725 The IP pools for bridge networks are no longer stored.
If an ungraceful shutdown happens in between a pool allocation and the new network persistance to store, at next reload neither the network nor the pool will be in store.

**Comment by coolljt0725** [comment]
@aboch  I tried it several times with 1.12-rc4, it didn't happen again.  This is happening in 1.11.2 with patch #1130 , I think I missing something on backporting #1130. sorry for the noise :)

**Comment by aboch** [comment]
Thanks @coolljt0725 for confirming.
