### ISSUE TITLE
excessive traffic generated from overlay networking on kernels <3.16

### ISSUE THREAD

**Issue by vikstrous** [docker/libnetwork#1189]
Excessive traffic is generated from overlay networking on kernels <3.16 when using UCP 1.1.0 with docker 1.11.1 (and probably earlier versions too). My repro uses kernel 3.13 with ubuntu 14.04, but I suspect that it's the same for any kernel <3.16 because overlay networking works differently for later kernels and I haven't been able to repro this issue there.

You might have to tweak some of the parameters to get it to work on your aws account. You need a wide open security group to make sure you don't run into any firewall issues. I also haven't tested the license injection part, so if that doesn't work, enter the license through the web ui. My repro was done using docker machine 0.6 (in case that makes a difference).

**Steps to reproduce:**

1. Deploy 2 docker machines with ubuntu 14.04 and docker 1.11.1:

    ```
    TOKEN=`docker run swarm create`
    docker-machine create -d amazonec2 --amazonec2-ami ami-9abea4fb --amazonec2-instance-type m3.medium --amazonec2-region us-west-2 --amazonec2-root-size 30 --engine-storage-driver aufs --amazonec2-security-group $SECURITY_GROUP --amazonec2-ssh-keypath ~/.ssh/id_rsa --engine-opt debug repro-master
    docker-machine create -d amazonec2 --amazonec2-ami ami-9abea4fb --amazonec2-instance-type m3.medium --amazonec2-region us-west-2 --amazonec2-root-size 30 --engine-storage-driver aufs --amazonec2-security-group $SECURITY_GROUP --amazonec2-ssh-keypath ~/.ssh/id_rsa --engine-opt debug repro-slave
    ```
2. Set up a ucp 1.1.0 controller with a license

    ```
    docker-machine scp ~/Downloads/docker_subscription.lic repro-master:/home/ubuntu/license
    eval $(machine env repro-master)
    docker run --rm -it --name ucp  -v /home/ubuntu/license:/docker_subscription.lic -v /var/run/docker.sock:/var/run/docker.sock docker/ucp:1.1.0 install --admin-password password --controller-port 444 --fresh-install --san $(machine ip repro-master) --swarm-port 12345
    eval $(machine env repro-slave)
    docker run --rm -it --name ucp -v /var/run/docker.sock:/var/run/docker.sock docker/ucp:1.1.0 join --admin-username admin --admin-password password --url https://$(machine ip repro-master):444 --swarm-port 12345 --san $(machine ip repro-slave) --interactive
    ```
4. Set up some containers on an overlay network

    ```
    eval $(machine env repro-master)
    docker network create -d overlay repronet
    docker run -d -t --net repronet --name first alpine sh
    eval $(machine env repro-slave)
    docker run -d -t --net repronet --name second alpine sh
    ```
5. You'll start seeing errors like this one in the daemon logs:

    ```
    time="2016-05-23T22:28:32.322432536Z" level=error msg="could not resolve peer \"172.17.0.5\": timed out resolving peer by querying the cluster" 
    ```
6. These errors happen multiple times a second. We suspect that these errors become more and more frequent and they might be responsible for DoSing the network after a while. I'm confirming this theory right now. I'll post an update with aws network traffic graphs after I leave this repro running for a while.

**Comment by vikstrous** [comment]
Here are some of the results. Part way through I started two more containers on the overlay network and you can see the increase in traffic in the graph. These numbers seem pretty high to me.

![repro-master-in](https://cloud.githubusercontent.com/assets/482425/15493967/8ab856e4-213c-11e6-87b6-e749188850b3.png)
![repro-master-out](https://cloud.githubusercontent.com/assets/482425/15493966/8ab50368-213c-11e6-82cd-0cd90350461d.png)
![repro-slave-in](https://cloud.githubusercontent.com/assets/482425/15493965/8ab4d5dc-213c-11e6-8cc0-4aac844f6d96.png)
![repro-slave-out](https://cloud.githubusercontent.com/assets/482425/15493968/8ab8a7a2-213c-11e6-870e-8bf9647e6f1c.png)

After taking these screenshots I removed both containers from the overlay network and the slave traffic went down to around 50kBps on both nodes.

**Comment by mavenugo** [comment]
@vikstrous thanks for all the data. Does this happen regardless of the `--subnet` you used to create the network ?
For example, do you still see the same issue If you create a network using `docker network create -d overlay --subnet=180.0.0.0/16 repronet` ?

**Comment by vikstrous** [comment]
The LAN IPs of the nodes all start with 172. so I don't expect the subnet to matter, but I haven't tried changing it.

**Comment by vikstrous** [comment]
@mavenugo I just tried deleting the containers and network and creating a new network with new containers with a custom subnet and it behaved the same way.

**Comment by thaJeztah** [comment]
Opened https://github.com/docker/docker/issues/22975 for tracking this in the docker/docker repository

**Comment by cpuguy83** [comment]
I can repro at least the issue of the weird peer lookups with simply:

Create machine with kernel < 3.16, then...
```
$ docker run -d --name etcd --net=host quay.io/coreos/etcd`
$ `echo {"debug": true, "cluster-store": "etcd://127.0.0.1:2379", "cluster-advertise": "127.0.0.1:2375"}` > /etc/docker/daemon.json && kill -HUP <docker pid>`
$ docker run -d --name test1 busybox top
$ docker network create -d overlay testnet
$ docker run -d --net=testnet --name test2 busybox top
```

However the code-path for peer lookups does not seem to  confirm that this is the cause of high etcd traffic.

**Comment by vikstrous** [comment]
It looks like those AWS graphs are actually per 5 minutes, not per second, which makes way more sense. It looks like an extra 66 bytes per second per container? The traffic is not that high, but it's concerning that there's any traffic at all.
