### ISSUE TITLE
No possibility to create an IPv6 only network

### ISSUE THREAD

**Issue by narqo** [docker/libnetwork#1192]
Hey, docker maintainers!

Currently `NetworkController` do subnet params normalisation, through the [`network.ipamAllocate()`](https://github.com/docker/libnetwork/blob/a37c74ce0e6f02ea8e7293b8007753b1ec48284e/controller.go#L498) that always add predefined default IPv4 addresses with `ipam.Allocator`. This leads to inability to have an IPv6-only network even with drivers that (theoretically) might work without IPv4 address (e.g. [`macvlan`](https://github.com/docker/docker/blob/cef4ea0b9759386800aae27d6fa92c80d4465745/experimental/vlan-networks.md) from docker experimental).

Are there any reasons to do it in controller and not in the particular driver (taking into account that currently allocation is skipped for `host` and `null` drivers, using `if n.Type() == "host" || n.Type() == "null"`).

**Comment by tgraf** [comment]
Related: #826
