### ISSUE TITLE
datastore holds lock for too long

### ISSUE THREAD

**Issue by jimmycmh** [docker/libnetwork#1201]
I'm investgating https://github.com/docker/docker/issues/22322

It turns out it's due to datastore holds lock for too long. For example
```
func (ds *datastore) GetObject(key string, o KVObject) error {
	ds.Lock()
	defer ds.Unlock()

	if ds.cache != nil {
		return ds.cache.get(key, o)
	}

	kvPair, err := ds.store.Get(key)
	if err != nil {
		return err
	}

	if err := o.SetValue(kvPair.Value); err != nil {
		return err
	}

	// Make sure the object has a correct view of the DB index in
	// case we need to modify it and update the DB.
	o.SetIndex(kvPair.LastIndex)
	return nil
}
```

datastore holds the lock during accessing etcd. As it takes several hundreds milli seconds to write to etcd, the consequence is NetworkByName in controller.go would take up to one minute when creating 100 containers concurrently.

I investigated the code, and it seems the purpose of  Lock in datastore is not protecting datastore members but  making operations of datastore serially. 

I removed the Lock and made a stress test for docker engine. It worked fine and the speed of creating containers in overlay network increased a lot.

Is there any special reason for the Lock in datastore?

**Comment by jimmycmh** [comment]
@mrjana I noticed that you added the lock to datastore. Any way to avoid locking datastore for too long?

**Comment by mrjana** [comment]
@jimmycmh The main purpose of serializing access was for local store where we saw data corruptions. But since this is a common layer it actually applies for every kind of store. May be a configuration can be passed from caller to enable/disable locking so that we do it only for local store. Would you be willing to push such a PR?

**Comment by jimmycmh** [comment]
Good idea. I'll try fix it.

**Comment by jimmycmh** [comment]
@mrjana Please check my pl https://github.com/docker/libnetwork/pull/1206 
Thanks.
