### ISSUE TITLE
Raw exists check for iptables is broken

### ISSUE THREAD

**Issue by bobrik** [docker/libnetwork#1216]
From https://github.com/docker/libnetwork/pull/1096#discussion_r59558201:

```
(compute)root@haha:~# iptables -t nat -A PREROUTING -p tcp -d 192.168.1.1 --dport 1234 -j DNAT --to-destination 172.17.0.1:4321 ! -i lo
(compute)root@haha:~# iptables -t nat -S
-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P OUTPUT ACCEPT
-P POSTROUTING ACCEPT
-A PREROUTING -d 192.168.1.1/32 ! -i lo -p tcp -m tcp --dport 1234 -j DNAT --to-destination 172.17.0.1:4321
```

Note that arguments are reordered and raw check won't catch that.

> iptables 1.4.11 came out in 2011 (5 years ago), I wonder if anyone uses it with docker:

https://github.com/kubernetes/kubernetes/blob/master/pkg/util/iptables/iptables.go#L398-L440

Any reason to keep this broken code that is probably never called?

cc @aboch, @chenchun

**Comment by chenchun** [comment]
Sorry, I don't mean to block you. But I'm really one of the guys who is still using iptables 1.4.7 which does not support `-C` check. Lots of the servers are also have the same environment in our company.
I'd like to upgrade iptable versions on these machines. But I think we'd better make a notice about this incompatible change on docker release.

**Comment by bobrik** [comment]
@chenchun what distro and kernel are you running?

**Comment by chenchun** [comment]
We are using a self maintained kernel version based on centos7.

**Comment by bobrik** [comment]
I see iptables 1.4.22 here: http://mirror.centos.org/centos/7/os/x86_64/Packages/

**Comment by bobrik** [comment]
https://github.com/docker/libnetwork/pull/1096#issuecomment-329130108
