### ISSUE TITLE
Artificial limit on number of possible overlay networks

### ISSUE THREAD

**Issue by JamieGarside** [docker/libnetwork#1218]
We've been running into an issue where, after running a cluster for a while, we start to get errors when creating new networks (failed to allocate vxlan no bit available). After looking through, it seems that there's a hardcoded limit of 744 networks (https://github.com/docker/libnetwork/blob/master/drivers/overlay/overlay.go#L25) causing this error.

Is it possible to either raise this limit or make it configurable?

**Comment by chenchun** [comment]
https://github.com/docker/libnetwork/pull/1231 fixed it.

**Comment by jeffbaier** [comment]
I don't know what the OVManager does, but this file also has the limit set to 1000. Does it need to be updated as well?

https://github.com/docker/libnetwork/blob/e3663caf778739ab9c08a546981978e80da44f71/drivers/overlay/ovmanager/ovmanager.go#L23

**Comment by chenchun** [comment]
I think OVManager is used by swarmkit https://github.com/docker/swarmkit/blob/master/manager/allocator/networkallocator/networkallocator.go#L21.

**Comment by mrjana** [comment]
@jeffbaier Yes, that needs to be fixed too. Will fix it before 1.12 release.

**Comment by jeffbaier** [comment]
Thanks.
