### ISSUE TITLE
Have some way of configuring PredefinedBroadNetworks 

### ISSUE THREAD

**Issue by arthurlogilab** [docker/libnetwork#1272]
Follow up of a forum post about a networking problem I'm facing, I was wondering if there would be a way to configure PredefinedBroadNetworks somewhere in some configuration. Would this be a docker-engine feature request ?

**Comment by nerdalert** [comment]
Hi @arthurlogilab do you mind pasting the history for some context? Thanks!

**Comment by aboch** [comment]
@nerdalert In a couple of Issue/PR in docker/docker (which I cannot find), it was pointed out that users would benefit from being able to specify the block of subnets from which the default ipam driver picks from when user or script creates a network w/o specifying the subnet.
As of now the subnets are statically defined in ipamutils.

Thoughts converged on something like a daemon start option which defines a block of IPs and the size of the subnets it would be split into.

@arthurlogilab At first glance I think the user defined predefined pools would be passed to the network controller via config options: https://github.com/docker/libnetwork/blob/v0.8.0-dev.2/config/config.go#L85

**Comment by arthurlogilab** [comment]
@nerdalert sorry, I forgot to put the link to the forum https://forums.docker.com/t/would-it-be-possible-to-exclude-some-networks-when-doing-a-docker-network-create/15659

@aboch your summary is perfect, thanks!

**Comment by aboch** [comment]
Found the docker/docker issue where the feature was initially requested, Linking now for reference. https://github.com/docker/docker/issues/21776#issuecomment-206133109

**Comment by twang2218** [comment]
There are 2 more related issues:

* https://github.com/docker/docker/issues/25645
* https://github.com/docker/for-mac/issues/916

Both of them will benefit from configurable `PredefinedBroadNetworks` features.

**Comment by arthurlogilab** [comment]
I get the feeling that this feature request is still valid, seeing the number of issues reported on networking problems (and exotic workarounds using resolv.conf and other tricks).

**Comment by LTangaF** [comment]
Yeah. I just ran into a case where I brought up a a compose application and it randomly picked a network we were using internally, basically disrupting existing functional routing. I'm hoping that it will examine existing routing table when bringing up and that that would function as a workaround.

**Comment by fcrisciani** [comment]
I guess this PR https://github.com/docker/libnetwork/pull/2241 addresses this feature request. closing it
