### ISSUE TITLE
uuid management

### ISSUE THREAD

**Issue by shettyg** [docker/libnetwork#129]
According to current API, I see that you pass "name" of a network while creating it in libnetwork. libnetwork in turn provides only the uuid to the driver.

e.g: docker network create -d ovn --name=foo

For multi-host networking, from a different host, if someone does a "docker network ls", will libnetwork somehow share state and list both the name and uuid?

If it does indeed share state, how is it going to store that persistent information?

**Comment by mavenugo** [comment]
@shettyg Yes. libnetwork will distribute the states and `docker network ls` will list a consistent name and uuid in all the clustered nodes. As described in the design document (https://github.com/docker/libnetwork/blob/master/docs/design.md), the Network and Endpoint objects have a global scope and the UUID is unique across the cluster.
The shared states work is not complete yet. But the general consensus is to use a distributed KV store.

**Comment by shettyg** [comment]
Thanks @mavenugo. That answers my question. Closing
