### ISSUE TITLE
Error: Unknown discovery type : 3

### ISSUE THREAD

**Issue by bboreham** [docker/libnetwork#1296]
Seen in Docker 1.12-rc2 logs when using Weave network (as an example of a remote driver; this issue does not appear to have anything to do with Weave):

    Jun 25 20:57:53 host1 docker[15099]: time="2016-06-25T20:57:53.409535574Z" level=warning msg="Failed to set datapath keys in driver weavemesh: Unknown discovery type : 3"

This appears to be because [`agent.go`](https://github.com/docker/libnetwork/blob/335f49fc9582659c60369235b905617a47569490/agent.go#L150) calls `DiscoverNew` with type `EncryptionKeysUpdate` but the [`remote glue code`](https://github.com/docker/libnetwork/blob/dbb0722c99715b3d183e348d29b894f97f38634c/drivers/remote/driver.go#L297) errors on anything that is not `NodeDiscovery`.

**Comment by mrjana** [comment]
@bboreham Are you using `docker swarm mode` and trying to use a global scope plugin? If so, plugins are not yet supported in 1.12. The support may come in the future. But the current cluster mode formed with external k/v store will continue to support plugins.

**Comment by bboreham** [comment]
Yes, I did `docker swarm init`, but I was not using a global scope plugin.  `weavemesh`, the driver referenced in the error message, is local scope.

I _have_ a global scope plugin; it is listening, but I was not using it.

Is this "may be supported in the future" status documented somewhere?
