### ISSUE TITLE
How should we use Macvlan in 1.12.0-rc2?

### ISSUE THREAD

**Issue by jmzwcn** [docker/libnetwork#1298]
Macvlan seems not work.
1.Firstly create a subnet within LAN: docker network create -d macvlan --subnet 192.168.1.0/24 --gateway 192.168.1.1 lan;
2.Run a  container: docker run --net lan --ip 192.168.1.10 -d nginx.

We should could access http://192.168.1.10 from other node in LAN.

Client:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd-unsupported
 Built:        Fri Jun 17 21:12:28 2016
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd-unsupported
 Built:        Fri Jun 17 21:12:28 2016
 OS/Arch:      linux/amd64
 Experimental: true

**Comment by jmzwcn** [comment]
Client:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd-unsupported
 Built:        Fri Jun 17 21:12:28 2016
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd-unsupported
 Built:        Fri Jun 17 21:12:28 2016
 OS/Arch:      linux/amd64
 Experimental: true

**Comment by nerdalert** [comment]
Hi @jmzwcn can you add a `-o parent=ethX` when you create the network? Since you aren't assigning a parent we are just creating a dummy interface to attach the container to. 

Check out the documentation at [MacVlan Bridge Mode Example Usage](https://github.com/docker/libnetwork/blob/master/docs/macvlan.md#macvlan-bridge-mode-example-usage). The example shows the host `eth0` being used that associates to the given docker network subnet.

```
# Macvlan  (-o macvlan_mode= Defaults to Bridge mode if not specified)
docker network create -d macvlan \
    --subnet=172.16.86.0/24 \
    --gateway=172.16.86.1  \
    -o parent=eth0 pub_net
```

**Comment by jmzwcn** [comment]
1.docker network create -d macvlan --subnet 192.168.1.0/24 --gateway=192.168.1.1 -o parent=wlp3s0 lan
2.docker run -d --net lan --ip 192.168.1.50 nginx

Strange, why it still doesn't work.

**Comment by nerdalert** [comment]
Hi @jmzwcn, some things to try and comments.

- Is your wireless Nic going into promiscuous mode? 
- Are multiple mac addresses allowed from one device? 
- Per Macvlan design, `192.168.1.50 ` is not allowed to ping the IP on `wlp3s0`. When you test connectivity do so pinging something like your gateway `192.168.1.1 `.
Do you have a VM on your host you can run Docker on to get a feel for how the driver works and ruling out the issue as a wireless issue?

Can you paste or gist any relevant info from the following?
1. `ip address show wlp3s0` 
2. Create the network `docker network create -d macvlan --subnet 192.168.1.0/24 --gateway=192.168.1.1 -o parent=wlp3s0 lan`.
3. Any relevant logs regarding wlp3s0 going into promiscuous mode from the command `$ dmesg`.
4. Start the container and make sure you are trying to ping the gateway `192.168.1.1` or any host that is not the one the container is running on. 
5. Check Docker logs for any relevant messages. If you are starting `dockerd` from the command line, add `-D` to get the debug log output.

Thanks!

**Comment by jmzwcn** [comment]
@nerdalert , thanks for your so many help!

My local host is a thinkpad x220, ubuntu16.04, without any VM, just having docker 1.12.0-rc2. I only use wifi connection(router is 192.168.1.1 having DHCP). I test it on another LAN host(thinkpad t410).

1.ip address show wlp3s0
3: wlp3s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether a0:88:b4:98:02:3c brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.100/24 brd 192.168.1.255 scope global wlp3s0
       valid_lft forever preferred_lft forever
    inet6 fe80::a288:b4ff:fe98:23c/64 scope link 
       valid_lft forever preferred_lft forever

2.docker network create -d macvlan --subnet 192.168.1.0/24 --gateway=192.168.1.1 -o parent=wlp3s0 lan
7c266b1670d298c9a6971347ad55930300e8abc6518cf23439066479bd1bea89

**Comment by nerdalert** [comment]
```

**Comment by jmzwcn** [comment]
Great, after I try with "-d ipvlan", all is OK as expect, I could access "http://192.168.1.100" from other host in LAN.

Maybe macvlan has bug when NIC is wireless WIFI?

**Comment by nerdalert** [comment]
Hi @jmzwcn thanks to your info the issue appears to be the wireless NIC going into promiscuous mode.  Maybe lets leave the issue open for another day or two and see if anyone can test manually adding a macvlan port using `ip link` that has Linux on a laptop and see what their results are.

Thanks and will close the issue in the next day or two if ok with you. Also hoping to have Ipvlan out of experimental come v1.13 so you don't have to use experimental for Ipvlan L2.

**Comment by jmzwcn** [comment]
Any feedback?

**Comment by jmzwcn** [comment]
Close it.

**Comment by hyzhak** [comment]
@nerdalert I got similar case, but "ip link" doesn't help: `ip netns exec ns1 ping 192.168.1.1` stuck forever with:
> PING 192.168.100.1 (192.168.100.1) 56(84) bytes of data.

Is there any alternative to `Ipvlan` which is still experimental
