### ISSUE TITLE
Incorrect option specified for bridge driver MTU in documentation

### ISSUE THREAD

**Issue by asridharan** [docker/libnetwork#1311]
Looks like a documentation bug . The following documentation https://docs.docker.com/engine/userguide/networking/work-with-networks/ lists the MTU option for the bridge driver as “com.docker.network.mtu” , however in the code its actually “com.docker.network.driver.mtu” https://github.com/docker/libnetwork/blob/0fcaacd848f60973235ae82b8fd7d9409227bac8/netlabel/labels.go#L34

**Comment by aboch** [comment]
Thanks, the documentation has now been fixed.
