### ISSUE TITLE
ILB behavior with AWS ELB

### ISSUE THREAD

**Issue by rhim** [docker/libnetwork#1313]
I setup two AWS instances running 1.12.0-rc2, and ran a simple service as such:

docker service create --replicas 2 --network mynet --name whoami -p 8000:8000 jwilder/whoami

I then configured an ELB to point to these instances. I can see load balancing happening:

~$curl -sSL whoami-584842023.us-west-1.elb.amazonaws.com
I'm 474cbb74a3ed
~$curl -sSL whoami-584842023.us-west-1.elb.amazonaws.com
I'm 46b89a421ff7

However, to testdrive ILB, I removed one of the instances from ELB configuration. My assumption is that it shouldn't matter, i.e., routing mesh should still ensure load balancing across containers. But to my bewilderment, it is routing traffic only to one container after that:

~$curl -sSL whoami-584842023.us-west-1.elb.amazonaws.com
I'm 46b89a421ff7
~$curl -sSL whoami-584842023.us-west-1.elb.amazonaws.com
I'm 46b89a421ff7
~$curl -sSL whoami-584842023.us-west-1.elb.amazonaws.com
I'm 46b89a421ff7

more _surprisingly_, this is the container on the instance that I removed from LB configuration!

Can someone please explain what could be going on here?

**Comment by mavenugo** [comment]
@rhim you are trying a valid scenario and it should work as you expect. This seems like a bug. If you can try adding the other node to the ELB (and remove the faulty node), does it load-balance properly ?

**Comment by rhim** [comment]
@mavenugo I also noticed something funny. When I tried after a long inactive period (~20 hrs), I saw that it did route to both containers once, before resorting again to routing to a single container.

> ~$curl -sSL whoami-584842023.us-west-1.elb.amazonaws.com
I'm 46b89a421ff7
~$curl -sSL whoami-584842023.us-west-1.elb.amazonaws.com
I'm 474cbb74a3ed
~$curl -sSL whoami-584842023.us-west-1.elb.amazonaws.com
I'm 46b89a421ff7
~$curl -sSL whoami-584842023.us-west-1.elb.amazonaws.com
I'm 46b89a421ff7
~$curl -sSL whoami-584842023.us-west-1.elb.amazonaws.com
I'm 46b89a421ff7

I then removed the "faulty" node (say node-1), and replaced it with the other node (node-2). Results are similar, as in the requests are now only routed to the container on *node-1*.

> ~$curl -sSL whoami-584842023.us-west-1.elb.amazonaws.com
I'm 474cbb74a3ed
~$curl -sSL whoami-584842023.us-west-1.elb.amazonaws.com
I'm 474cbb74a3ed
~$curl -sSL whoami-584842023.us-west-1.elb.amazonaws.com
I'm 474cbb74a3ed

So, in effect, the problem remains irrespective of the node.

Putting both nodes back in ELB configuration restores the correct load balancing behavior.

Seems like the packets are being routed to the node other than the one that receives the request. I.e, when ELB routes to node-1, routing mesh then routes it to node-2's container, and vice-versa. That would explain the behavior I am seeing. However, that's not the intended behavior I expected from ILB.
