### ISSUE TITLE
docker network join lifecycle

### ISSUE THREAD

**Issue by shettyg** [docker/libnetwork#133]
I am a little confused around the life cycle.

What does 'docker network join CONTAINERUUID NETWORKNAME -l foo=bar' call in terms of libnetwork apis?
Does this call the following 2 one after the other?:
network.CreateEndpoint(NETWORKNAME, labels(foo=bar)) 
      -> driver.CreateEndpoint(nid, eid, labels(foo=bar))

endpoint.join(CONTAINERUUID, labels(foo=bar)) 
       -> driver.Join(nid, eid, sboxkey, labels(foo=bar))

**Comment by mrjana** [comment]
@shettyg `docker network join` should have an endpoint name and a network name in addition to container ID. With that in mind internal calls are like this:
```
network.CreateEndpoint(EndpointName, labels(foo=bar))
-> driver.CreateEndpoint(nid, eid, labels(foo=bar))

endpoint.Join(containerID, labels(container_labels))
-> driver.Join(nid, eid, sboxKey, labels(container_labels))
```
The container labels are the labels that you assign the container when it is created.

**Comment by shettyg** [comment]
@mrjana 
So the following pull request (https://github.com/docker/libnetwork/pull/106) from @dave-tucker would eventually change the "docker network join" syntax to also include the EndpointName?

**Comment by mrjana** [comment]
@shettyg yes
@dave-tucker let us know if you thought otherwise

**Comment by shettyg** [comment]
@mrjana  

Which of all my following statements are true? If they are false, a oneliner on why would be helpful.

* Eventhough there are 2 driver calls with driver.CreateEndpoint and driver.Join, they will always be called together. (I do not seen any docker daemon facing CLI tool that lets you eventually call driver.CreateEndpoint and driver.Join as 2 separate calls)

* driver.CreateEndpoint() will create physical veth pairs (with any self-assigned mac addresses) and return back their names to libnetwork. It will also provide back IP address and
GATEWAY information. libnetwork will move the veths to the container namespace and then
assign them the IP addresses and also set the GATEWAY. It then calls driver.Join()

* driver.Join() will not get the same labels that was used when you did a 'docker network join' but instead get the labels that you passed with 'docker create container'.

* Since veth pairs have already been moved inside the container namespace, driver.Join()
can only do some post-processing with the nid and eid that it gets. 

* If you want to add multiple endpoints to a container, you will have to first "docker create" the container and then do multiple 'docker network join' with the CONTAINERID. And then finally a 'docker start'

**Comment by mrjana** [comment]
> Eventhough there are 2 driver calls with driver.CreateEndpoint and driver.Join, they will always be called together. (I do not seen any docker daemon facing CLI tool that lets you eventually call driver.CreateEndpoint and driver.Join as 2 separate calls)

There will be new CLIs in the future which will probably say something like `docker service create` which is actually a CLI to create an endpoint and then a separate CLI `docker service join` to join a container to that. So the driver should never assume that these are going to be called together.

> driver.CreateEndpoint() will create physical veth pairs (with any self-assigned mac addresses) and return back their names to libnetwork. It will also provide back IP address and
GATEWAY information. libnetwork will move the veths to the container namespace and then
assign them the IP addresses and also set the GATEWAY. It then calls driver.Join()

libnetwork just saves the info that gets back from the driver during `CreateEndpoint`. It only attempts to push them into the container during the `Join` call after successfully returning from the `driver.Join` call

> driver.Join() will not get the same labels that was used when you did a 'docker network join' but instead get the labels that you passed with 'docker create container'.

Yes

> Since veth pairs have already been moved inside the container namespace, driver.Join()
can only do some post-processing with the nid and eid that it gets.

Again interfaces are moved into the namespace only after the Join call but that is not important. Vut the driver can delay network plumbing until a  `Join` call like attaching the external end of veth pair to the bridge or setup iptable rules or send information to it's peer nodes about the `Join` just happened so that correct routing information can be populated in all the nodes etc.

> If you want to add multiple endpoints to a container, you will have to first "docker create" the container and then do multiple 'docker network join' with the CONTAINERID. And then finally a 'docker start'

One endpoint can be implicitly created based on docker run parameters. But you don't have to delay `docker start` until all endpoints are joined. You can join an actively running container to more endpoints.

**Comment by shettyg** [comment]
@mrjana Thanks for the explanations. It helps!

driver.CreateEndpoint() is supposed to reply back with veth names. Does not this make it local host dependent. If the intention was to make driver.CreateEndpoint() portable across multiple hosts, would it not be more useful if providing back the veth names is not the responsibility of driver.CreateEndpoint() but rather of driver.Join()?

Is your thought process that the driver can create vethnames based on endpointuuid to make it truly portable. i.e., one can call driver.CreateEndpoint() on one host and return back vethnames based on eid, but not actually create the veths.  Call driver.Join() on a different host. So even though veth names are created during 'docker service create' but veths are physically created only during 'docker service join'. (But, vethnames can only be 15 characters long on Linux, so there is a very very small possibility of collisions.)

**Comment by dave-tucker** [comment]
@mrjana you shouldn't need an endpoint name. If we require it at all, it should be optional (if no ID is specified, a new endpoint is created)

Simple use case is as follows...

I `c=$(docker run -itd ubuntu --net=foo)`.
After starting, I realise I need to access resources on `--net=bar`.
Therefore it should be feasible to `docker network join $c bar`

If you are going to optionally require and endpoint ID, then you should also add the necessary CLI to manage endpoint lifecycle.

For example
```
# Create a new endpoint on Network foo
$ docker network endpoint create --net=foo
aabbccdd123456
# Delete and endpoint
$ docker network endpoint delete aabbccdd123456
```

**Comment by shettyg** [comment]
@dave-tucker 
It will be very useful to have the optional endpoint name. The use case for me is that if endpoint has been pre-created in OpenStack, it already has a uuid. I can now provide that uuid as a endpointname to 'docker endpoint create'. Since docker itself will create a new eid, the name lets me relate two different uuids.

**Comment by dave-tucker** [comment]
Closing this one as the original question has been answered and the UI has changed rather significantly since the question was asked.
