### ISSUE TITLE
Jumbo frames not working in swarm overlay network

### ISSUE THREAD

**Issue by zcrisler** [docker/libnetwork#1330]
Jumbo frame support seems broken in swarm overlay networks.  They work fine between containers on the same host by passing --mtu=9000 to dockerd. However, the swarm overlay networks seem to not use that flag.

I think this is causing network throughput to be much less then what could  be achieved by having overlay networks support jumbo frames.   I believe this because the throughput I'm currently getting with swarm overlay networks is identical to what I saw when using weave
(non-encrypted, using vxlan) with the default MTU (1450).  Weave provides an option to set the MTU, and once set to 8950 (9000 - 50 for vxlan overhead), the performance increased dramatically.

To put numbers to it, on a 10Gbps network performance went from 1.1Gbps to 8.7Gbps.  Right now, 1.1Gbps is what what we're currently seeing with docker swarm overlay networks.  I'm hoping jumbo frame support will show similar performance benefits.

I love Docker and the new additions to 1.12, but unfortunately without jumbo frame support in the overlay networks, the overlay networks are unusable in my production environment.

**Comment by adrecord** [comment]
This is related to #1021.  I was hoping for a pointer from @mavenugo or @mrjana so I could finish making the needed changes to get jumbo frames working.  Read my comment in that issue for details.

I agree with @zcrisler that jumbo frames is a requirement for many production environments.. hopefully the needed code change is small enough that it could make it into 1.12.
