### ISSUE TITLE
Continuous Invalid broadcastQ encountered while gossiping for network errrors  

### ISSUE THREAD

**Issue by sanimej** [docker/libnetwork#1363]
With docker master as of 07/27 I see this error continuously in the following case..

- 1 manager with 2 workers running a service with 3 replicas (one task on each node)
- swarm leave on worker 2
- daemon restart on worker 1 and the Invalid broadcastQ encountered while gossiping for network error happens continuously on worker 1.

**Comment by tedli** [comment]
Same error. A docker swarm mode cluster with four nodes what are all act as manager. An overlay network with three services running on. One of the three is a web front end rely on the other two service with published port(let's say 8000). Each of the three has 2 replicas. After restarting one docker daemon, curl 127.0.0.1:8000 didn't work any more while the error mentioned continuously on that machine. Before restarting the docker daemon, curl 127.0.0.1:8000 worked as expect on all the four nodes.

**Comment by sanimej** [comment]
@tedli The issue that trigged `Invalid broadcastQ` errors has been fixed and will be available in 1.12.1 release. I will try recreating the issue you have with accessing the service after a daemon restart.

**Comment by tedli** [comment]
@sanimej My situation may caused by #24234 .

**Comment by thaJeztah** [comment]
@sanimej looks like this can be closed now that https://github.com/docker/libnetwork/pull/1365 was merged

**Comment by sanimej** [comment]
@thaJeztah Yes, this can be closed. Thanks.
