### ISSUE TITLE
How do drivers decide the ethX name?

### ISSUE THREAD

**Issue by shettyg** [docker/libnetwork#141]
Currently it is expected that driver.CreateEndpoint() returns back the sandbox.info structure that needs to include ip, gateway, veth_inside and veth_outside information. (Where veth_inside is "The name that will be assigned to the interface once moved inside a network namespace.") 

As I see it, the driver cannot return back that information because it does not know how many other endpoints will be added to the container in question. What is the thought process of the designers here?

**Comment by mrjana** [comment]
@shettyg Was busy integrating libnetwork with docker hence the delay in answering some of your earlier questions. Getting back to this question, the interface `SrcName`, `DstName` being present as part of the return value of the `CreateEndpoint` is an artifact of an earlier design where endpoint was a local resource and a container joined it during CreateEndpoint. With the goal of Endpoint being a service abstraction and hence a universal resource, it makes no more sense to keep interface names as part of information returned during `CreateEndpoint`. The IP addresses still will remain as part of `CreateEndpont` info. But expect a few adjustments in what needs to be returned during endpoint create and join which will hopefully clarify all these question. I will probably push a PR tomorrow to fix this. Please take a look and comment.

**Comment by tomdee** [comment]
@mrjana Any update on this? This sounds like quite a significant change to the API. If you're not ready to push code for it, could you at least update the design doc (on a branch)?

**Comment by mrjana** [comment]
@tomdee I am getting back to working on this. Our first priority was settle down the libnetwork northbound apis so that we can get it integrated with docker core for which we have a PR in progress. It should probably not be that much of a change in driver API other than only IP addresses required to be returned during `CreateEndpoint` and everything else during `Join`. I will try to push a PR today and update the doc. If not I will try to see if we can send a doc update PR.

**Comment by tomdee** [comment]
@mrjana Thanks for the quick response. That all sounds good.

**Comment by squaremo** [comment]
Is this (or rather, the analogous problem with Join) addressed by #193, which changed the meaning of DstName to be a prefix to which libnetwork appends an index?

**Comment by mrjana** [comment]
@squaremo Yes, and I think we should close this issue
