### ISSUE TITLE
Semantics for "global" objects

### ISSUE THREAD

**Issue by squaremo** [docker/libnetwork#142]
In the design document it's stated that networks and endpoints are "global scope within a cluster".

What is a cluster?

What are the semantics associated with these being global? For example: if I try to create a network `"foo"` on one host, then delete `"foo"` on another host, should I expect this to succeed, or to report an error?

What specifically is required of drivers to support these globally-scoped objects?

**Comment by tomdee** [comment]
I'm very interested in this question too. Without knowing the answer to these questions it's hard t design an external plugin.

**Comment by mavenugo** [comment]
@squaremo @tomdee apologies on the delay. We are working on the finer details on this design and we will get back to this question shortly.

**Comment by squaremo** [comment]
@madhu Is this perhaps related to #188 -- is there anything (aside from code I suppose) describing the semantics of libnetwork with a config store?

**Comment by tomdee** [comment]
@mavenugo Would it be possible to provide an update on this issue? I can't see any docs describing the behavior but am I missing something?

**Comment by tomdee** [comment]
I still can't see any docs describing the difference between local and global drivers...
