### ISSUE TITLE
Docker hands out ip addresses outside of default range

### ISSUE THREAD

**Issue by creynders** [docker/libnetwork#1454]
I'm starting out with using custom docker networks and encountered the following problem:
I've got a bunch of running docker containers communicating with each other through custom networks, this worked fine until I hit the 16th network bridge created by docker. Previously it always used ip addresses in the range of 172.X.0.1 but for the last networks created it suddenly started assigning 192.168.X.1 addresses. Which is a problem since we already got stuff running in that ip range.

We're using default settings, the docker daemon was started without any networking flags and I'm a bit at a loss why this is happening. 

```
  IP address for br-9c1b63917a7a: 172.20.0.1
  IP address for br-01292ff0ca82: 172.19.0.1
  IP address for br-6eb09a983885: 172.18.0.1
  IP address for docker0:         172.17.0.1
  IP address for br-8038f622d999: 172.21.0.1
  IP address for br-5a406c4fc43f: 172.22.0.1
  IP address for br-34783be426ae: 172.23.0.1
  IP address for br-9dea9efa9a61: 172.24.0.1
  IP address for br-46324482365a: 172.25.0.1
  IP address for br-f894d5635313: 172.26.0.1
  IP address for br-3db7cd0fd877: 172.27.0.1
  IP address for br-57d7721a7692: 172.28.0.1
  IP address for br-118341306c9a: 172.29.0.1
  IP address for br-78e103bb9834: 172.30.0.1
  IP address for br-648cb9799215: 172.31.0.1
  IP address for br-6460cf0076b2: 192.168.0.1
  IP address for br-5aaa47cfa4cf: 192.168.16.1
  IP address for br-8597479c6016: 192.168.32.1
  IP address for br-1522739e229b: 192.168.48.1
  IP address for br-ebf8bc0ab9c7: 192.168.64.1
```

Is this "normal" behaviour or should I configure docker differently? Or?
I've been searching for info on this, but the only thing I can find is how to create a custom network with a specific ip address, however I'd really like docker to manage the ip addresses automatically.

**Comment by mavenugo** [comment]
@creynders This is the expected behavior. Docker's built-in IPAM uses fixed private address ranges to choose the subnets from. If you need a specific subnet for your network, you can use `--subnet` option when creating a network in `docker network create` command.

**Comment by creynders** [comment]
@mavenugo thanks, but how would I configure docker to automatically use only addresses in the 172.20.x.x range for all networks it creates? I.e. w/o having to provide a --subnet option manually each time?

**Comment by creynders** [comment]
@mavenugo ah, according to docker/docker#21776 that's apparently not possible yet..?

**Comment by christw92** [comment]
@DanielHabenicht Any idea why docker would still use ips outside the defined pools although i defined them in `/etc/docker/daemon.json` like you suggested?
The funny thing is, when I create a new network with `docker create foo` it uses the defined ranges. But when I restart the docker service itself (or restart the computer) it always creates a bridge named something like `br-064cc74666eb` with 172.17.0.1 which is an issue because this address is already used in my local network. This br-... also gets created if i stop all the containers.

Would be very thankfull for any hint.

Docker version 19.03.0, build aeac949
side note: i'm using docker-compose, but don't think its related to that.

**Comment by kubiaki** [comment]
I fixed this just performing the following:

`docker network prune`

This removed the unused networks that were causing the conflict.
