### ISSUE TITLE
Avoid dependency of remote drivers on Docker plugins

### ISSUE THREAD

**Issue by squaremo** [docker/libnetwork#147]
If libnetwork is to be considered useful independent of Docker, it should not depend on the Docker plugin system. However, this conflicts with the design goal of not having driver-related types in the libnetwork API.

To wit: one very simple design would be to have a `libnetwork.RegisterRemoteDriver` procedure, which adds a `driverapi.Driver` implementation to the list of available drivers; but this trivially compromises the "no driver types in API" goal.

Since drivers cannot be supplied to libnetwork, it must reach out and get them from somewhere. The plugin implementation (at this time) has a procedure for registering a handler for a plugin type -- e.g., `"NetworkDriver"` -- and this can be done during libnetwork's initialisation. However, to do so libnetwork needs to import the plugin package and use its types and handler registration mechanism.

This (near-)cycle can be broken by introducing interfaces which the plugin system implements or can be adapted to implement. The difficulty then is how does Docker (or some other application) supply its implementation to libnetwork?

One alternative might be to add a means for supplying such an implementation. For example, smuggling it through a special case of ConfigureNetworkDriver; or, a southbound API procedure.

The difficulty here is that it is needed by the remote driver initialisation, and that is locked up behind libnetwork's initialisation. So there would need to be a complicated dance to make sure things are initialised in the correct order (supply plugin implementation to remote package; initialise libnetwork) and there would be no good way to enforce the ordering.

Another alternative is to recognise that remote drivers are a special case, take the remote package initialisation out of libnetwork initialisation, and let people hook them together separately. This would require an additional API procedure in `NetworkController`, but it needn't use driver types, only the plugin adapter interfaces.

I am open to other suggestions, including that of just depending on docker/pkg/plugins despite the downsides.

**Comment by mavenugo** [comment]
@squaremo in my view, docker plugins is a reusable package. libnetwork remote drivers including it doesn't make it dependent on the Docker runtime itself. We can still use libnetwork independently in another runtime which happens to provide a plugin system that honors the contract established by the pkg/plugins.

My integration patch and my comments (https://github.com/docker/libnetwork/pull/70#issuecomment-100266456) reflects this opinion.

At this time, my choice is to take this approach ( https://github.com/mavenugo/libnetwork/commit/b3dcb1f ) for now, till we have a better alternative. This will unblock many who are waiting to integrate their remote plugins.

@mrjana @aboch can you please share your opinion as well ?

**Comment by squaremo** [comment]
> This will unblock many who are waiting to integrate their remote plugins.

Not yet, unless you are prepared to depend on the docker fork that includes the plugins work. But I am OK with this position -- it's just scheduling that presents a difficulty.

**Comment by squaremo** [comment]
Can someone advise on the code organisation: would this repository vendor in `docker/pkg/plugins`?

**Comment by mavenugo** [comment]
@squaremo @mrjana https://github.com/docker/docker/pull/13161 brings in the plugin infra to docker repo. I also have a proposal to the devs to move it under `docker/pkg/plugins` : https://github.com/calavera/docker/pull/6.

**Comment by squaremo** [comment]
docker/docker#13161 doesn't seem to include the `plugins.Handle` procedure. Trying now to find out where it went ..

**Comment by squaremo** [comment]
> doesn't seem to include the plugins.Handle procedure

Plugin autoloading got taken out. So this will require a rethink.

**Comment by squaremo** [comment]
Closing this and preparing a PR instead.
