### ISSUE TITLE
netlink calls should have timeouts

### ISSUE THREAD

**Issue by cpuguy83** [docker/libnetwork#1474]
Netlink can be slow, or sometimes not even respond even in a normal case (or so I'm told).
In one case where we have a known kernel bug stuck calls waiting for netlink to respond cause the daemon to freeze (since a container lock is held).

It would be awesome if calls to netlink could use a timeout so we can avoid these types of hangs.

**Comment by cpuguy83** [comment]
ping @mrjana

**Comment by cpuguy83** [comment]
Any chance we can get this for 1.13?
How can I help?

**Comment by aboch** [comment]
I opened https://github.com/vishvananda/netlink/pull/170 for this.
