### ISSUE TITLE
Clarifications on specs about interface creation/deletion and namespaces

### ISSUE THREAD

**Issue by mchiappero** [docker/libnetwork#1520]
I'm working on some changes on a remote driver (Kuryr) and I would like get some clarifications on the correct workflow and expected behavior from libnetwork.

After reading the related documentation, my understanding is:
- Actual interfaces (e.g. veths, ipvlan slaves, etc) should be created and deleted in driver.CreateEndpoint and driver.DeleteEndpoint by the driver. The file [docs/design.md](https://github.com/docker/libnetwork/blob/master/docs/design.md) seems quite clear on this but there may be some ambiguity in [docs/remote.md](https://github.com/docker/libnetwork/blob/master/docs/remote.md) (indeed Kuryr creates and deletes the interfaces in driver.Join and driver.Leave, which I suspect to be wrong).
- libnetwork will always take care of moving the interfaces in and out of the Sandbox, so the remote driver must not do that. The SandboxID, which seems to refer to the actual namespace in Linux, shouldn't be used by the driver but for referencing purposes.
- IP addresses must be assigned to the actual OS interfaces by the remote driver in driver.CreateEndpoint.

Could you please verify if the above assumptions are correct? Thank you.

**Comment by mchiappero** [comment]
Also, the spec is not clear at all on the expected returned values by [create endpoint](https://github.com/docker/libnetwork/blob/3c8e06bc0580a2a1b2440fe0792fbfcd43a9feca/docs/remote.md#create-endpoint) in the remote driver.
Some questions about the expected response:
- "As far as the value of Interface is concerned, MacAddress and either or both of Address and AddressIPv6 must be given.": does this mean returning the MacAddress is mandatory? It doesn't seem so from your implementation.
- "If the remote process was supplied a non-empty value in Interface, it must respond with an empty Interface value": does this mean the response should be {"Interface": { }}? I guess no, but the wording doesn't help.
- "LibNetwork will treat it as an error if it supplies a non-empty value and receives a non-empty value back, and roll back the operation". This is still ambiguous but let's assume it refers to "Address", "AddressIPv6" and "MacAddress": the latest implementation doesn't do any of these checks, so it's hard to guess the proper and expected behaviour.

Moreover, on the given args:
"If supplied, Address is an IPv4 address [...]. If supplied, AddressIPv6 is an IPv6 address [...]. MacAddress is a MAC address [...]". So is MAC address optional too, in the current implementation it seems so.

Could you please clarify what is the expected format and constrains and update the specs accordingly improving the wording?

Thank you.

**Comment by aboch** [comment]
> Actual interfaces (e.g. veths, ipvlan slaves, etc) should be created and deleted in driver.CreateEndpoint and driver.DeleteEndpoint 

True. 
But you actually can create the interface only when you need it during join, builtin overlay driver does in fact do it that way. But it still delete the link during endpoint deletion, and there were issues (which I can't recollect now) if the link deletion happened during leave. 

> libnetwork will always take care of moving the interfaces in and out of the Sandbox

Correct

> IP addresses must be assigned to the actual OS interfaces by the remote driver in driver.CreateEndpoint

No, the container interface's addresses are assigned by the libnetwork core code.
And the address is chosen either by the user or by the ipam driver

> I guess no, but the wording doesn't help.

Please feel free to push a PR to fix the documentation

> the latest implementation doesn't do any of these checks, so it's hard to guess the proper and expected behaviour.

The check is being run in https://github.com/docker/libnetwork/blob/master/drivers/remote/driver.go#L162

Are you seeing it does not work ? If so, please let us know.

> So is MAC address optional too, in the current implementation it seems so.

It is. But if user runs the container with `--mac-address` option, your remote driver will receive one in the interface structure and it is not allowed to change it.

**Comment by mchiappero** [comment]
Hi @aboch, thank you for replying and clarifying a bit, but I still don't fully understand.

>No, the container interface's addresses are assigned by the libnetwork core code.
And the address is chosen either by the user or by the ipam driver

This negates "The Interface value is of the form given. [...]; and the Interface itself may be empty" in the spec about the request.

> > I guess no, but the wording doesn't help.

> Please feel free to push a PR to fix the documentation

Okay, you seem to confirm that if "value" for a key is present in the request (in practice only "MacAddress" is optional then if what you said above is true), the response for that key must be empty. However there is no mention of the expected response in case no value is provided in the request:

1. The remote driver must provide "value".
If so, there is no check in libnetwork to verify that if ifInfo.MacAddress() == nil then inIface.MacAddress != nil else error. It's okay if the implementation is more tolerant than the spec, but people need to know what is compliant. BTW, this leads to the problem described in issue [1559](https://github.com/docker/libnetwork/issues/1559), but it's a different matter.

2. The remote driver is permitted to return no value. 
This would make no sense, what would be the purpose of returning an Interface then? Moreover, from the spec, about the expected response, "As far as the value of Interface is concerned, MacAddress and either or both of Address and AddressIPv6 must be given."

Which one is the most correct one? Please help with all these ambiguities.

Thank you
