### ISSUE TITLE
With VXLAN ARP proxy, ip neigh add fails due to ARP entry limits when a cluster has more than 1024 containers

### ISSUE THREAD

**Issue by BSWANG** [docker/libnetwork#1522]
docker version: 1.11.2  
kernel version:  
    <3.16   =>  a cluster can not create more than 1024 containers
    >=3.16 =>  a overlay network can not create more than 1024 containers

daemon logs:

```
1859999 time="2016-10-25T16:17:22.228057263+08:00" level=error msg="Peer add failed in the driver: could not add neigbor entry into t        he sandbox: could not add neighbor entry: no buffer space available\n"
1860000 time="2016-10-25T16:17:22.248622064+08:00" level=error msg="2016/10/25 16:17:22 [ERR] memberlist: Failed to send gossip to 10        .27.183.190:7946: write udp 10.27.183.183:7946->10.27.183.190:7946: sendto: invalid argument\n"
1860001 time="2016-10-25T16:17:22.334297387+08:00" level=error msg="could not resolve peer \"10.27.183.176\": timed out resolving pee        r by querying the cluster"
```

workaround:

```
sysctl -w net.ipv4.neigh.default.gc_thresh1=1024
sysctl -w net.ipv4.neigh.default.gc_thresh2=4096
sysctl -w net.ipv4.neigh.default.gc_thresh3=8192
```

So can docker set the kernel arp cache value by default? or use ebtables to avoid this issue?

**Comment by BSWANG** [comment]
ping @sanimej @mavenugo

**Comment by mtarsel** [comment]
>  could not add neighbor entry: no buffer space available\n"

You cannot create more than 1024 ports on a Linux bridge. If you are creating containers on any Linux bridge network you will have to change BR_PORT_BITS in order to scale to more than 1024 ports on your bridge.

**Comment by BSWANG** [comment]
close by #1789
