### ISSUE TITLE
The Overlay Driver

### ISSUE THREAD

**Issue by naotoy** [docker/libnetwork#155]
Do you plan the Overlay Driver is to be released at the same time as the docker 1.7.0?
In overlay driver, which will you use either of the Linux Bridge and OVS?

**Comment by WeiZhang555** [comment]
I have the same question, what's the plan on the Overlay Network Driver? 
Have you made decisions on the overlay driver implementation?

**Comment by mavenugo** [comment]
@naotoy @WeiZhang555 Overlay Network driver will be made available soon. This is not targeted for 1.7.0 release. The current thought process and design is based on Linux Bridge and VXLAN tunnel. Please watch this space and we will update the design document with the necessary details.

**Comment by sridhardevarapalli** [comment]
Do you have an update on the networking models that will be supported in Docker 1.7? Where can I find more details on the libnetwork APIs (including various options supported) that are described in this design doc? https://github.com/docker/libnetwork/blob/master/docs/design.md

The documentation on different drivers (Bridge, overlays etc) is very thin. Any additional info will be appreciated.

thanks

**Comment by dave-tucker** [comment]
Closed in #308 - for information on the implementation, see [here](https://github.com/docker/libnetwork/blob/master/docs/overlay.md)
