### ISSUE TITLE
Libnetwork fails with IPVLAN interfaces created by a remote plugin

### ISSUE THREAD

**Issue by mchiappero** [docker/libnetwork#1559]
I'm working on a remote plugin that at Driver.CreateEndpoint time creates an IPVLAN slave interface and returns its MAC address. However libnetwork then fails with the following error:

`docker: Error response from daemon: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:334: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: time=\\\\\\\"2016-11-11T06:31:17+13:00\\\\\\\" level=fatal msg=\\\\\\\"failed to add interface t_cf6978e4a-a5 to sandbox: error setting interface \\\\\\\\\\\\\\\"t_cf6978e4a-a5\\\\\\\\\\\\\\\" MAC to \\\\\\\\\\\\\\\"fa:16:3e:24:46:c2\\\\\\\\\\\\\\\": operation not supported\\\\\\\" \\\\n\\\"\"\n".`

While it's possible to introduce the ability to change the mac address for the IPVLAN Linux driver, it would makes little sense, while it's not clear the need for libnetwork or the oci runtime to try setting the same MAC address again when already set on the interface. A check should be added to discriminate between the real inability to set it upon a user provided one and the case where no change is needed at all.

**Comment by westsouthnight** [comment]
@mchiappero I have some situation, elk container after detach bridge network connection cannot start on some nodes, i dont know why

**Comment by buamod** [comment]
I have a similar issue 

_docker: Error response from daemon: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:334: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: time=\\\\\\\"2016-12-14T16:35:43-05:00\\\\\\\" level=fatal msg=\\\\\\\"failed to create a netlink handle: failed to set into network namespace 21 while creating netlink socket: invalid argument\\\\\\\" \\\\n\\\"\"\n"._

**Comment by mavenugo** [comment]
ping @nerdalert . can you pls take this one ?
