### ISSUE TITLE
License has placeholders

### ISSUE THREAD

**Issue by rdsubhas** [docker/libnetwork#1575]
Hi folks, Just notifying that the repo's LICENSE has placeholders instead of real data.

**Comment by rdsubhas** [comment]
Forget it, its just the template

**Comment by thaJeztah** [comment]
Actually, I think you're right; it should be 

    Copyright 2016 Docker, Inc.

https://github.com/docker/libnetwork/blob/master/LICENSE#L189

Are you interested in opening a PR to fix this?

**Comment by rdsubhas** [comment]
@thaJeztah yep and that seems to be the `APPENDIX: How to apply the Apache License to your work.` part after the `END OF TERMS AND CONDITIONS` :) Do you think its still relevant to change?
