### ISSUE TITLE
how container get its ip address when connected with docker0 bridge?

### ISSUE THREAD

**Issue by xiaopeng163** [docker/libnetwork#1581]
HI 

I  just want to know, I create a container by default, it connect with `docker0` bridge.

```bash
  $  docker inspect --format '{{.NetworkSettings.IPAddress}}' test1
  172.17.0.2
```

it can get an IP address, is this through DHCP or static assign? how it work? where can i find the information about this, because i can't get this information from https://docs.docker.com/engine/userguide/networking/

thanks.

**Comment by xiaopeng163** [comment]
anyone know this? please!

**Comment by mavenugo** [comment]
By default it uses the built-in ipam driver. By default it uses a set of predefined subnets from which it dishes out the IP addresses. Pls look under ipam directory for more I formation.

**Comment by xiaopeng163** [comment]
thanks. will check them
