### ISSUE TITLE
Query on design.md

### ISSUE THREAD

**Issue by bboreham** [docker/libnetwork#1597]
I am having trouble parsing this phrase in https://github.com/docker/libnetwork/blob/master/docs/design.md:

> An Endpoint can belong to *only one* network but may only belong to *one* Sandbox.

What is the intended distinction between "only one" and "one"?  
Or it it between "can" and "may"?

It's too subtle for me.  Please make it more obvious.

**Comment by mchiappero** [comment]
The difference is that there is a strict 1:1 relationship between endpoint and network, while and endpoint may, optionally, belong to one Sandbox, that is, either one or no Sandbox.

**Comment by bboreham** [comment]
Suggest changing "only belong to _one_" to "belong to _zero or one_"
