### ISSUE TITLE
Static IP Address option please

### ISSUE THREAD

**Issue by itoffshore** [docker/libnetwork#161]
It would be nice to be able to assign static ip addresses to Docker containers (for web servers for instance) as a built in feature. I have a temporary solution [here](https://it-offshore.co.uk/linux/debian/36-giving-docker-containers-static-ip-addresses) with [pipework](https://github.com/jpetazzo/pipework) but it is sub-optimal as `docker inspect --format '{{ .NetworkSettings.IPAddress }}' "$@"` no longer works.

The interest for this feature can be seen at https://github.com/docker/docker/issues/6743

**Comment by mavenugo** [comment]
@itoffshore Thanks. Yes, We are accommodating this request with the support from the drivers via the driver-api changes that is currently in PR : https://github.com/docker/libnetwork/pull/152
We are trying to approach this similar to the mac-address feature for containers. Please stay tuned.

**Comment by thaJeztah** [comment]
Thanks @itoffshore!

**Comment by Nagodar** [comment]
Now that the PR #152 is merged, what else is needed?

**Comment by mavenugo** [comment]
Few things -
1. Add a reserved label for static-ip
2. Modify the `run` command to pass labels to libnetwork
3. Pass the labels to the Driver which is responsible for honoring the set `ip` based on its IPAM policies

This will happen in the next few days. Stay tuned.

**Comment by Nagodar** [comment]
thanks a lot @mavenugo

**Comment by JonasT** [comment]
Reminder: please make sure it's possible to specify BOTH an ipv4 and ipv6 at the same time.

**Comment by spikecurtis** [comment]
We got the impression from the [remote driver API](https://github.com/squaremo/libnetwork/blob/remote_driver_docs/docs/remote.md#create-endpoint) that @squaremo wrote that pre-provisioned or static IP addresses would be passed to the driver on `endpointInfo.Interfaces()` containing one or more `Interfaces`.  

However, there doesn't appear to be any code that sets a non-zero number of interfaces before `CreateEndpoint`.  @mavenugo's comment suggests that the mechanism for static addresses will be via labels.  Does that mean the `endpointInfo.Interfaces()` method is vestigial code and will always return an empty list?  If not can you clarify under what circumstances it would return a non-empty list.

**Comment by mauri** [comment]
Is there any progress on this issue? I implemented a patch on docker 1.6 to support this and want to port it to 1.7 as a new driver in libnetwork. But I've seen some back and forth on the implementation, if there's a branch somewhere to take a look it would be great to not duplicate efforts :)

**Comment by tomdee** [comment]
I'm also interested in hearing what's happened with this issue

**Comment by deitch** [comment]
I too am very interested. But I think it is broader than just passing a fixed IP. I think it is about *how* you generate that IP.

Here is a sample use case using default Docker bridge:

1. Determine an IP from a DNS entry (or Consul, or etcd, ...)
2. Pass that IP on to docker (and through it to the driver)

If you are using a different plugin, e.g. a macvlan plugin

1. Set up a macvlan interface assigned to a particular port
2. Take the interface ... could just as easily be a physical port, or SR-IOV VF, or separate bridge, or... 
2. Assign the interface to the container
3. Configure the interface with IP and routing

libnetwork provides the plugin API for some of the above, but even plugins need real-time logic to determine what data to use, e.g. 

* which fixed IP to pass to Docker's bridge?
* which interface to connect the macvlan to?
* which SR-IOV VF to use to hand to the container?

Sure, I could run a script to generate these, and then hand them to my docker command as params that go to the correct plugin, but that wouldn't work for the same reason that pipework doesn't scale:

1. It is run as a script *after* running `--host=none`, which means that the ENTRYPOINT is executed *before* the network is complete. Oops. OK, libnetwork solves that.
2. It is run as a separate script, so restart policies won't invoke it. 
3. It is run as a separate script, so Docker-native orchestrators (swarm, Rancher, etc.) won't know how to invoke it.

There needs to be a way, as part of the Docker run even before it passes on to the network plugin (or perhaps as part of it) to run logic that will generate the necessary information the networking driver needs.

**Comment by mavenugo** [comment]
@mauri @tomdee @deitch I have been thinking about this issue for some time now and infact had a proposal of using the container labels https://github.com/docker/docker/pull/13476 to let the driver determine its course of action. But that proposal was closed due to some legitimate comments from @shykes and @icecrime : https://github.com/docker/docker/pull/13476#issuecomment-109363464.

Given that we have to separate out the operational concerns (IPAM) from user concern, I think the best way to solve this problem is by providing an optional pluggable IPAM. We can reuse the Plugin approach that is already being used by both Volume & Network drivers.

In order to preserve the user-experience across drivers, we have to keep the IPAM plugin independent of the network driver and let the network driver honor the IPAM plugin's request for using a specific ipv4/ipv6 address for a given container / service.

In the spirit of batteries-included, but swappable philosophy we can include a default IPAM driver which can use user-input for ipv4/ipv6 address assignment.

Such a design will both retain the expected UX & also operational flexibility required by operations.

@mrjana @icecrime @shykes WDYT ?

**Comment by deitch** [comment]
@mavenugo thanks for the links there. I saw their concerns, but I think it was a larger question: how do you pass runtime information to network drivers? Everyone likes labels for their ease of use in runtime, but their inclusion in Dockerfile (and hence images) is a concern. We almost need 2 categories of labels: runtime and buildtime. Or at least a way to distinguish.

Approaching IPAM as a separate element from network-driver is interesting, but isn't IPAM an inherent element *of* the network driver? I cannot exactly assign an IP address on the docker0 bridge unless I am working in the context of the bridge and know what addresses have been assigned in what namespace. The same holds for weave or rancher or any other driver. Similarly, if I go straight for a static IP, I need a driver to connect it, going to be one of physical eth, macvlan, ipvlan, or IOV VF (which is physical as far as the OS is concerned). Any of those will be just another network driver, which will need the IP.

So, sure, I could use an IPAM plugin, but my concerns are:

1. Would it require changes to all network drivers to respect the address?
2. Would it require changes to libnetwork to understand that this is a special plugin and pass it in?
3. How do we control the order of execution?
4. Would it weaken the network driver to the point of (in some cases) non-functionality?

On the other hand, different environments have different policies for generating that IP within those drivers that need it. One environment might use DNS lookup based on a property (label? hostname?) of the container. Another might look it up in etcd or consul. Etc. Which brings us back to configurable IPAM plugin.

Maybe a different approach. Maybe a plugin that runs after the network driver to manage IP? The network driver does its usual magic however it wants (macvlan setup, ipvlan, physical, weave, rancher, whatever), and then the IPAM driver runs later and can change things inside the container. The plugin could choose to run or not based on runtime config (which network-driver was used, labels, etc.).

That would allow me to use macvlan+DNS or ipvlan+static or weave+DHCP or whatever. Better yet, it does not require me to change any network drivers or weaken them at all.

Thoughts?

BTW, to solve my immediate problem, I was thinking of writing an events API (pre-1.8) and network driver plugin (1.8+) just to catch the creation, create the macvlan, and assign the IP.

**Comment by mavenugo** [comment]
@deitch Separating IPAM from network driver is a good thing for many reasons. We have heard from many end-users for a particular way to assign ip-addresses regardless of which network driver be used. 
I guess you answered your question 

>> On the other hand, different environments have different policies for generating that IP within those drivers that need it.
Thats the exact reason why we should keep them separated. 

Infact a simple static ip-address assignment for the containers can be easily achieved using this approach, by having a batteries-included ipam driver which can just provides a very simple way of assigning static-ip based on user-input.

To answer your other questions 

>> Would it require changes to all network drivers to respect the address?
This is already taken care of in the existing driver API

>> Would it require changes to libnetwork to understand that this is a special plugin and pass it in?
Yes. There will be changes to libnetwork to interface with the IPAM plugin APIs

>> How do we control the order of execution?
This is not very different from the way existing IPAM solutions work. Also, it is not very different from existing plugins are designed. For example, as of today, both network and volume plugins are containers that exposes plugin APIs which must be bootstrapped along with docker daemon. IPAM is no exception.

>> Would it weaken the network driver to the point of (in some cases) non-functionality?
Why would it ? IPAM is a fully composable entity that can be isolated to simplify the operational concerns. The comment from @shykes https://github.com/docker/docker/pull/13476#issuecomment-109363464 reflects the reality of how the ip-address assignment for containers are viewed. I certainly don't see it as an inherent functionality of network driver.

**Comment by deitch** [comment]
> I guess you answered your question
>> On the other hand, different environments have different policies for generating that IP within those drivers that need it.

> Thats the exact reason why we should keep them separated.

Ha! I guess I did. Often the process of asking the question causes the answer to come through.

> Infact a simple static ip-address assignment for the containers can be easily achieved using this approach, by having a batteries-included ipam driver which can just provides a very simple way of assigning static-ip based on user-input.

To keep with the libnetwork philosophy, wouldn't the IP assignment for docker0 bridge driver also want to use an IPAM driver? Not that I am a stickler for it, as much as looking at it as a use case where the IP driver depends on the network driver. If we can get them to play nicely together there, then we can do so for weave, and rancher, etc.

> Yes. There will be changes to libnetwork to interface with the IPAM plugin APIs.

How does the design discussion get started in a structured way? Happy to continue to be part of it. 

> >How do we control the order of execution?

> This is not very different from the way existing IPAM solutions work. Also, it is not very different from existing plugins are designed. For example, as of today, both network and volume plugins are containers that exposes plugin APIs which must be bootstrapped along with docker daemon. IPAM is no exception.

I wasn't referring to booting it, which may not even be necessary. I meant, how do we ensure that when we create an endpoint that IPAM driver is called correctly before or after network driver? I could see it both ways. Using the docker0 bridge as a model:

1. docker bridge driver called, creates veth, attaches one half to bridge, other to container
2. IPAM called, it needs to know that the eth0 was assigned by the bridge, so it knows in what IP space to assign it.

Or the other way around:

1. IPAM called, it needs to know that the driver will be the Linux bridge, so it can query it for the right address space, creates the address passes it back to driver manager, which passes it to:
2. docker bridge network driver, which just respects the IP it was given

I could see the same issue with a macvlan or ipvlan driver:

1. macvlan driver called, creates macvlan link, inserts to container
2. IPAM called, it is a little easier, it just needs to know on its own what IP to assign

Or the other way around:

1. IPAM called, it needs to know that it can find an IP on its own, creates the address passes it back to driver manager, which passes it to:
2. macvlan driver, which just respects the IP it was given

It is that inter-dependency that was bothering me in the first please when I said, "weaken".

**Comment by bboreham** [comment]
From experience working on weave Net, I can confirm that IPAM can be separated from the network; IPAM doesn't need to do any more than manage a set of unique points in an address space.  

Clearly it needs to be called in coordination with the network driver, and the respective API designs should support this. I think it's a bad idea if IPAM actually _assigns_ the address to the interface; what if I like the flannel network but want to use the weave IPAM with it?

Similar to static addresses, the user may want to specify an IP subnet but not care which address they get within that subnet.  There are probably a bunch of similar parameters that need to be specified either imperatively or declaratively by the administrator, then made available to all the plugins that are interested. I think #248 is making the same point.

**Comment by deitch** [comment]
> IPAM doesn't need to do any more than manage a set of unique points in an address space.

Depends. It might be more intelligent based on user parameters (giving an actual IP, looking up an IP, coordinating with a KV store, etc.)

> I think it's a bad idea if IPAM actually assigns the address to the interface;

Why does it matter? 

> what if I like the flannel network but want to use the weave IPAM with it?

How would that work?

> Similar to static addresses, the user may want to specify an IP subnet but not care which address they get within that subnet.

Sure, that is one use case. I could see a plugin with options, or multiple plugins.

**Comment by bboreham** [comment]
If an IPAM plugin is (config parameters in) -> (IP address out), then it has no contact with the actual network.  It's just an API call, which has to happen at the right time, and then the address is passed to the network plugin.

On the other hand, if the IPAM assigns the IP to the interface (as in what `ip addr add` does), then IPAM plugins are much more tightly bound to the associated network plugin.

**Comment by mavenugo** [comment]
@bboreham @deitch Yes. IPAM plugin role is just to manage the ipv4 / ipv6 addresses and its responsibility to provide the required guarantee across multi-host. 
IPAM plugin also should provide configuration options such as subnet and other usual suspects (All these will be well defined in the Plugin Spec).

IPAM plugin should NOT assign ip-address to the interface and it is beyond its scope and also makes it more tightly coupled to the implementation details.

Once we have IPAM plugin, all the ipv4/ipv6 requests must go through the plugin (including the bridge ip, etc...).

**Comment by deitch** [comment]
So IPAM is an IP address manager (as the acronym implies), and the network driver handles interacting with the container and eth (or similar) interface? I can see how that would be cleaner. And as my earlier examples show, it doesn't much matter which order you do it in... as long as the network driver knows to respect an IP it has been given. 

So the flow looks something like this:

1. Request to create container
2. Docker calls libnetwork
3. libnetwork calls IPAM driver to say, "creating endpoint with these parameters, please give me IP4/6 address, mask, route(s)"
4. libnetwork calls network driver to say, "creating sandbox with these parameters, here are the IP4/6 address, mask, route(s), please create endpoint"

I mostly see how that would work, but still some questions:

1. How does IPAM know the network parameters when it needs to? E.g. it needs to know if it was docker bridge or ovs or weave or whatever, and it needs to know the address space to know how to create the IP and assign it
2. You wrote earlier that we wouldn't need to change the network drivers, as respecting a passed IP is "already taken care of in the existing driver API". So the docker bridge driver, e.g. already respects a passed IP, but if it has none then does it on its own?


> IPAM plugin role is just to manage the ipv4 / ipv6 addresses and its responsibility to provide the required guarantees across multi-host. 

I guess we will have to work it out. The IPAM driver still will need to know, "I have a weave overlay network using the following address range," or "I am using Calico for L3 in the following range," or "I am using the physical fabric with no overlay, here is how you get an IP." In other words, every IP addressing scheme depends on knowing what my underlying network is.

Unless we decouple them... hm... 

> IPAM plugin also should provide configuration options such as subnet and other usual suspects (All these will be well defined in the Plugin Spec).

OK, where is it being defined? Process sounds great.

**Comment by mavenugo** [comment]
@deitch The flow is inline with my thought process as well.
I hope the examples that you have given here are for illustrative purposes and you didn't actually mean to add IPAM requirements with network driver specifics (such as weave or calico or no-overlay drivers). We will have to generalize them as different schemes/modes and define them in API.

Please take a look at the existing IPAM API that overlay driver makes use of https://github.com/docker/libnetwork/blob/master/ipam/contract.go. It provides address space (for multi-tenancy) support and subnet specific addressrequest. This IPAM implementation also uses the KV-Store to distribute the states and provide consistency guarantees in a multi-host scenario. This is just an example implementation.

The API that we will define for the IPAM plugin will have to cover more such generic requirements which will become the ipam plugin spec. Not all plugins need to satisfy all the schemes.

**Comment by deitch** [comment]
@mavenugo excellent. I like agreeing with smart people (but disagreeing is more fun!).

No, they aren't specific requirements. I am just trying to come up with various use cases, so I can understand and tease out how it would actually be used. I agree on different schemes and modes. Ideally, the IPAM would have no clue what network driver is being used, only the IP assignment specifics. The hard part, to me, is genericizing it, so that we can say, "this plugin is passed the IP space X so it can figure out Y," or such similar. The same flow applies whatever your driver.

Looking at the link you sent, I see it has:

* Config `AddSubnet`, `RemoveSubnet`, `AddVendorInfo`
* IPAM `Request`
* IPAM `RequestV6`
* IPAM `Release`

A number of questions/comments:

1. `Request`/`RequestV6`: these return an `AddressResponse`, which includes the `Address` and `Subnet`, i.e. mask/CIDR. Should it not also including routing info? Is that not part of the contract, "give me everything an endpoint needs to connect and route traffic"?
2. `AddSubnet`/`RemoveSubnet`: how/when do these get called? Is it part of initialization? That would make sense, but unsure
3. During initialization, how does additional data get passed in, e.g. URL for a KV store like etcd/consul, or DNS lookups, or method to use, etc.? Is that the job of `AddVendorInfo`?

I am going to try to find time next week to build that macvlan/ipvlan/physical interface with static IP events API (pre-1.8) network driver (1.8+) I discussed earlier. It will solve immediate problems for me, and also give me something to work with to tease apart the network driver from IPAM. I would be better in this discussion with something real to try.

**Comment by bboreham** [comment]
@deitch note that `AddressResponse.Subnet` is of type `SubnetInfo`, which includes the routing info you ask for.

**Comment by deitch** [comment]
Doh! I should have gone one more layer deep. :-)

**Comment by shettyg** [comment]
It would be pretty cool to have an optional IPAM that Docker provides (I could simply use it instead of depending on something else in a Docker only network). But it has to be optional in cases wherein the IPAM is your cloud provided to actually do the necessary underlay routing.

**Comment by mavenugo** [comment]
Thanks for the good discussion. Based on the comments, it seems like there is a general high-level consensus to introduce an optional IPAM plugin which the user can make use of to satisfy this PR. Also it addresses other concerns on keeping the operational and user intent separated.
Its not realistic to target this for the 0.4 milestone. Moving it to 0.5 milestone (for Docker 1.9 release).

**Comment by RX14** [comment]
Will this solution allow me to assign an externally-routable IPv6 address to a container? For example I have a dedicated server which comes with a /48 of IPv6 addresses and I would like to directly assign some of them to a container.

**Comment by deitch** [comment]
@mavenugo thanks. It sounds great. The will be nitty details in determining how to get the IP given a certain driver, but it should be doable. Please do flag my name, very happy to participate.

Were you thinking multiple IPAM pluggable? After all, if I can plug in docker's docker0 networking (can I shorten it to `d0`?) plus weave's plus flannel's, then the IPAM should be "stackable" too? I would think so even if it has just one network driver. After all, it is common to have multiple IPs on a single NIC in an OS, so why not here as well?

@RX14 that is my understanding. There are two parts to it:

1. Assign a NIC (virtual, macvlan, ipvlan, physical, VF, veth, whatever), that is performed by the network driver
2. Assign IP, CIDR/netmask, routing info, that is performed by the IPAM driver. So just have an IPAM that adds the IPv6, I would think?

**Comment by mavenugo** [comment]
@RX14 there are a few command-line options tricks (using fixed-cidr-v6 and mac-address) that we have today which provides a static way to assign ipv6 addresses to a container. But, IMHO the ipv6 management needs to be properly thought through and we should avoid special casing ipv6 with many such flags. Now that we are actually thinking about proper IPAM, we have a opportunity to address all these use-cases in a clean and consistent fashion.

I will open an enhancement proposal shortly for the pluggable IPAM support. Lets collect & consolidate the features that we all look forward for.

**Comment by deitch** [comment]
Great @mavenugo I look forward to it. Kindly post the link here.

**Comment by JonasT** [comment]
@mavenugo just to mention it again, you should consider putting IPv6 behind a NAT too, or at least block all incoming traffic on all ports not explicitly exposed with docker run's *publish* (-p) if that's not already happening. Otherwise, people are gonna produce security holes since ports only reachable from other containers with IPv4 will suddenly be globally reachable from outside with IPv6.

**Comment by kevinxucs** [comment]
@mavenugo so instead of specifying a static IP for each container, I am wondering if there is a easy way of persisting the IP address on container restart, is that achievable via IPAM?

**Comment by deitch** [comment]
@kevinxucs would that not just be a property of IPAM? The network-driver is getting another IP request because of container restart, it passes container info to IPAM. IPAM then uses logic - which may include assigning the same IP again - to assign a new (or previous) IP to the container.

In some cases, it may do so with no additional work, e.g. if the IP is based on a DNS lookup of the hostname, or if it is algorithmically based on something that is constant like a label. In others, it may need to be told, "this was the container IP last time it ran." 

That sounds very similar to DHCP...

**Comment by kevinxucs** [comment]
Hi @deitch. But is there any way to get info on the container that's requesting the IP? Currently, it seems to me there is no such way to get that info: https://github.com/docker/libnetwork/blob/master/docs/ipam.md#requestaddress

**Comment by deitch** [comment]
I have to assume it has some way of identifying the container and its info, maybe labels, past addresses, something. Otherwise it is just blindly handing out IPs, which is less than dhcp does.

**Comment by mavenugo** [comment]
@aboch this is another requirement towards the IP address management : https://github.com/docker/libnetwork/issues/161#issuecomment-163087592 (in addition to the static IP Address assignment). This particular requirement has come up multiple times in the past without any conclusive decision. It would be good to have a final decision, design and implementation to target the 1.10 release.

**Comment by aboch** [comment]
Closed by https://github.com/docker/docker/pull/19001

**Comment by makuk66** [comment]
The PR https://github.com/docker/docker/pull/19001 says "The configuration is persisted across container restart". But I can see a container lose its IP address in this scenario:

```
mak@trinity10:~$ docker network create --driver=overlay --subnet 192.168.122.0/24 netA
869e5c9cc34c89016957074499bcf2343d1eaa0df534c8283292e2ca9b326de2
mak@trinity10:~$ docker run -d --name c1 --net=netA --ip=192.168.122.2 busybox top && docker exec c1 ip -4 addr show eth0 | grep inet
ebd52c54c186fe635f8b321ee7c0e60a29e8ca04c3d42f56f205e6e447c71a53
    inet 192.168.122.2/24 scope global eth0
mak@trinity10:~$ docker kill c1
c1
mak@trinity10:~$ docker run -d --name c2 --net=netA busybox top && docker exec c2 ip -4 addr show eth0 | grep inet
a867bea48ae79e7b1440e819a1a8330a7ebfc005457ea8323696b5f2c5421772
    inet 192.168.122.2/24 scope global eth0
mak@trinity10:~$ docker start c1
Error response from daemon: Address already in use
Error: failed to start containers: c1
```

Version info:

```
mak@trinity10:~$ docker --version
Docker version 1.10.0-dev, build f11b6a2, experimental

mak@trinity10:~$ docker info
Containers: 4
Images: 116
Server Version: 1.10.0-dev
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 124
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host calico overlay
Kernel Version: 3.16.0-30-generic
Operating System: Ubuntu 14.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.66 GiB
Name: trinity10
ID: GTUO:4CDB:FHKA:3WUU:6G6R:RMX3:42TU:KYZN:GM67:FEXC:GHL5:CXRZ
WARNING: No swap limit support
Experimental: true
Cluster store: etcd://192.168.77.10:2379,192.168.77.20:2379,192.168.77.30:2379
Cluster advertise: 192.168.77.10:2375
```
How can I avoid that?

**Comment by deitch** [comment]
@mavenugo does that mean that the current IPAM driver API as described at https://github.com/docker/libnetwork/blob/master/docs/ipam.md#requestaddress does not yet support @shykes direction of allowing the IPAM driver to say: ` "if color == blue && prod == true { drivercfg.netmask = 10.42.42.0/24"` ? Is the assumption that at some point in the future env vars or labels or other similar properties of a started container will be passed to IPAM driver?

**Comment by mavenugo** [comment]
@makuk66 pls refer to https://github.com/docker/docker/pull/19001#issuecomment-168075164 where @aboch explained the way to do it. Essentially while creating the network, you can decide which range must come from automatic ip allocation (using `--ip-range` option) and the rest of the ip-addresses from the subnet can be statically allocated.

**Comment by mavenugo** [comment]
@deitch pls refer to https://github.com/docker/docker/pull/17316

**Comment by deitch** [comment]
@mavenugo, I didn't understand that. I get how `--ip-range` can allocate a range when creating a network (but may be irrelevant with a different IPAM plugin), but how does that enable the IPAM driver to say `if color == blue && prod == true`? How does it discover from the request what `color` and `prod` are set to for this particular container?

**Comment by mavenugo** [comment]
@deitch we don't have per-container level ipam options yet. 
BTW, '--ip-range' should be applicable for all the IPAM plugins (the information is passed to the IPAM plugin as the sub-pool).

**Comment by deitch** [comment]
So the concept by @shykes of `if color == blue and prod == true then ip=1.2.3.4` cannot work yet? Ugh. I saw a great opportunity to rip out some complex event-driven and container environment and label IP assignment with a simple custom IPAM and network plugin that read the container properties (`color == blue and prod == true`) and determined what IP to assign.

Is there an ETA for passing container labels and/or env vars to IPAM the way we pass it into events?

**Comment by mavenugo** [comment]
@deitch its a bigger discussion than the passing container labels to the ipam driver. Please take a moment and read @shykes's comment : https://github.com/docker/docker/pull/13476#issuecomment-109363464. It is generally discouraged to pass container labels to the drivers. We need a more generic way to translate the operational intent to low-level primitives. Now that we have user-assignable ip-address for the container, we could potentially use the operational intent overlayed on top of this low-level primitive to get your request fulfilled. But that has to be done as a generic implementation and not specific to ip-address. Does that make sense ?

**Comment by deitch** [comment]
I didn't understand that within @shykes's comment (probably too much jet lag; I am in San Francisco just for the day). 

Is he saying, rather than passing container labels to the driver itself, instead "out-of-band matching" means that there are multiple configs, and the container labels (a form of user intent description) are used to match which config to pass to the driver, or possibly which driver?

Why is that better than putting the logic in the IPAM driver? 

I guess I can see a use case where there is a static IP driver. It is generic, can assign any static IP. "out-of-band" or "wrapped" logic allows me to say, `if color==blue and prod==true then ip=1.2.3.4` and pass that to the IPAM driver. But then I am passing the "intent" (in the form of labels or host info or whatever) to some "logic engine", just another form of driver. What do I gain?

**Comment by Hostile** [comment]
is this works now ?

**Comment by bboreham** [comment]
@hostile yes, in Docker 1.10. For example see https://blog.jessfraz.com/post/ips-for-all-the-things/
