### ISSUE TITLE
IPAM, can I set custom options in RequestAddress api?

### ISSUE THREAD

**Issue by qiankunli** [docker/libnetwork#1635]
For RequestAddress API of ipam, the remote driver will receive a POST message to the URL /IpamDriver.RequestAddress with the following payload:

    {
        "PoolID":  string
        "Address": string
        "Options": map[string]string
    }

can I set custom options in RequestAddress api when running `docker run xxx`?

**Comment by elianka** [comment]
i think we should add some fields to RequestAddress to let the ipam know which container that it will allocate ip address for.
so maybe the options should be worked.
