### ISSUE TITLE
Why LinkLocalAddresses must in 169.254.xx.xx?

### ISSUE THREAD

**Issue by chchliang** [docker/libnetwork#1640]
for _, llIPNet := range ep.Iface().LinkLocalAddresses() {
		if !llIPNet.IP.IsLinkLocalUnicast() {
			return nil, types.BadRequestErrorf("invalid link local IP address: %v", llIPNet.IP)
		}
	}

func (ip IP) IsLinkLocalUnicast() bool {
	if ip4 := ip.To4(); ip4 != nil {
		return ip4[0] == 169 && ip4[1] == 254
	}
	return len(ip) == IPv6len && ip[0] == 0xfe && ip[1]&0xc0 == 0x80
}

**Comment by aboch** [comment]
By definition IPv4 link-local address are the one in 169.254.0.0/16
