### ISSUE TITLE
Update libnetwork plugin API doc

### ISSUE THREAD

**Issue by anusha-ragunathan** [docker/libnetwork#1649]
https://github.com/docker/swarmkit/pull/1607/files added swarmkit support for global network plugins while allocating network resources. Two new methods `AllocateNetwork` and `FreeNetwork` were added as part of the plugin API. 

These newly added methods should be documented in
https://github.com/docker/libnetwork/blob/master/docs/remote.md

cc @mavenugo

**Comment by Soulou** [comment]
On year later this issue is still valid, it would be great to address it

**Comment by anusha-ragunathan** [comment]
@fcrisciani @ddebroy , can you please do the needful in updating the relevant docs?
