### ISSUE TITLE
Rename service under libnetwork/client to endpoint to avoid confusion

### ISSUE THREAD

**Issue by huikang** [docker/libnetwork#1660]
The `libnetwork/client` package provides the ``service`` subcommand so that libnetwork supports the command like ``./dnet service publish | attach``. After reading the document, I feel that the ``service`` here really means an endpoint. To avoid the confusion with service in swarmkit or other things in libnetwork such as LB and FW [1], how about renaming service under libnetwork/client to endpoint?

**Comment by aboch** [comment]
> I feel that the service here really means an endpoint

@huikang That is correct.

The libnetwork/api was added at the time the network endpoint was meant to carrying the service concept. And libnetwork was thought to also be used as an independent binary (see `dnet`) and programmed via those apis.

This is no longer the case.

But the dnet and libnetwork/api were kept as the integration tests can be achieved by using them without dependency on docker.

**Comment by huikang** [comment]
@aboch Thanks for clarifying this. It takes a while for me to identify that difference between `service` in `dnet` and `service` in docker engine. I agree that libnetwork/api and dnet should be kept to make libnetwork independent of docker. 

If you think this renaming proposal is a valid change, I am glad to spend some time working on this. Please let me know. Thanks.
