### ISSUE TITLE
why overlay network is not included in the circleci integration test

### ISSUE THREAD

**Issue by huikang** [docker/libnetwork#1662]
Is there any limitation in the circleci testbed to prevent running the overlay integration test [1]? Thanks.

[1] https://github.com/docker/libnetwork/blob/530e1d972eae4b8bde5177656ba888d9303a8ca7/test/integration/dnet/run-integration-tests.sh#L240-L248

**Comment by aboch** [comment]
Yes, I think there was some limitation in the CI.
Feel free to push a test PR where you enable those tests.

**Comment by huikang** [comment]
@aboch I found that the major limitation is that circleci uses LXC as the docker engine [1]. I tried their workaround and it does not work for running a command in a nested network namespace [2].

So this seems difficult to implement in circleci environment. How about creating some new ci script for travis-ci, which uses VMs and allows installing newer version of docker engine.

[1] https://circleci.com/docs/1.0/docker/#docker-exec
[2] https://github.com/docker/libnetwork/blob/master/test/integration/dnet/helpers.bash#L269

**Comment by aboch** [comment]
Thanks @huikang. Now that you mentioned it, I kind of remember that was the reason @mrjana did not enable it.

If you are interested in contributing around the integration test area, I would suggest you to do so in docker integration-cli. IMO it is way simpler, more flexible and easier to debug than in libnetwork integ test infra.
