### ISSUE TITLE
Finding libnetwork version used by docker daemon

### ISSUE THREAD

**Issue by asridharan** [docker/libnetwork#1663]
Given a docker daemon, how do you figure out the libnetwork version supported by the daemon?

**Comment by sanimej** [comment]
libnetwork is not a stand alone product by itself. So there isn't a fixed/published version scheme. For purposes of vendoring to docker patch releases we maintain certain versions. But if you are trying to check out the libnetwork code for a given docker version you can use the libnetwork commit id from the  vendor.conf file. For ex: For docker 1.13.x

https://github.com/docker/docker/blob/1.13.x/vendor.conf#L26
