### ISSUE TITLE
DNS resovler should continue on SERVFAIL

### ISSUE THREAD

**Issue by marcosnils** [docker/libnetwork#1664]
According to the DNS spec, clients receving a ` SERVFAIL` response should try to the next server in the list if available. Current docker resolver doesn't take that into consideration and doesn't forward the request to the next available DNS.

https://github.com/docker/libnetwork/blob/beb66e43697a675a0efd1fb6ee3ca4d439ad79e6/resolver.go#L474-L488

**Comment by sanimej** [comment]
@marcosnils Yes, I am aware of `SERVFAIL` not being handled correctly. Will fix it.

**Comment by marcosnils** [comment]
@mavenugo ?

**Comment by tomthetommy** [comment]
Any movement on this one guys?

**Comment by tomthetommy** [comment]
Any movement on this? I've recently discovered this issue with Docker version 17.05.0-ce, build 89658be.

**Comment by ddebroy** [comment]
I will pick this up.

**Comment by thaJeztah** [comment]
@ddebroy slightly related (in case _none_ of the servers resolve) https://github.com/docker/libnetwork/pull/1972

**Comment by ddebroy** [comment]
The fix has been merged. Should land in an engine release soon.

**Comment by thaJeztah** [comment]
This fix is  included in Docker 18.03.1; https://github.com/docker/docker-ce/blob/v18.03.1-ce/components/engine/vendor/github.com/docker/libnetwork/resolver.go#L494-L498, so looks like this can be closed
