### ISSUE TITLE
Issue with Docker network overlay

### ISSUE THREAD

**Issue by JnMik** [docker/libnetwork#1685]
Hello peps! 
Not sure this is the right projet to post this, feel free to redirect me if it's not ! 

We had a weird issue with Docker swarm this afternoon.

We deploy containers using the stack yml file, and we currently don't specify networks in yml, so by having it empty, swarm creates one with a name like stack_name_default and use it.

Today, we ended up with a container having it's IP address assigned in the same subnetwork as the docker nodes, and the container lost all connectivity with external services. From inside the container, I was able to ping the other replicas, but wasn't able to curl google.ca or other external services. I tried dropping the service & stack and relaunch it but seems swarm was always redeploying it with the same non-working subnetwork.

So I dropped the stack, create an overlay network that I forced to another IP subnetwork, and then re-launched the stack using that pre-created network.
It's working for now.

Anyone had this issue before, is that a known behavior ? 
Should we always create network overlay at first, for production servers ?

Docker version 1.13.0, build 49bf474

thx !

**Comment by fcrisciani** [comment]
@JnMik you can pre create a network specifying the subnet and use it inside your compose as external, or specify the subnet in the compose file itself.
Closing this, but if you have other question feel free to open it again
