### ISSUE TITLE
Documentation for bridge driver options not available?

### ISSUE THREAD

**Issue by asridharan** [docker/libnetwork#1721]
I couldn't find any place where the options for the docker bridge driver are specified? Without this documentation the only option is to look at code but then this leads to a lot of red herrings due to version discrepancies.

**Comment by aboch** [comment]
https://docs.docker.com/engine/userguide/networking/work-with-networks/#create-networks

Look for
`When creating a custom network, you can pass additional options to the driver. The bridge driver accepts the following options:`

**Comment by inkblot** [comment]
That text is now gone.

**Comment by daninfuchs** [comment]
Seconded. Care to give this one a brief look?
