### ISSUE TITLE
CreateNetwork request's IPv4Data::GatewayAddress is sent in CIDR format

### ISSUE THREAD

**Issue by ofiliz** [docker/libnetwork#1745]
CreateNetwork IPv4Data (I suspect also IPv6Data, but I haven't tried IPv6) contains a GatewayAddress field. According to the remote plugin specification, this is supposed to be sent as a regular IP address, as opposed to CIDR notation like in "pool" field:

https://github.com/docker/libnetwork/blob/master/docs/remote.md
"Pool": ipv4-cidr-string,
"Gateway" : ipv4-address"

Yet, the Gateway field is also sent in CIDR (for example: 10.1.1.1/24). The implementation and design spec conflict. I think the spec is correct (libnetwork shouldn't care what the subnet prefix length of a gateway is).

In any case, the ambiguity needs to be resolved so plugin implementations can choose one or the other.

**Comment by aboch** [comment]
The network gateway is passed down to the drivers in the same notation the IPAM driver provided it to libnetwork core, which is in CIDR notation.

Will push a fix to the remote driver specifications.

**Comment by ofiliz** [comment]
Hmm, no, at least in my case, the IPAM driver doesn’t use CIDR notation, either.

Also it seems to me that it doesn't really make sense to use the "CIDR notation" in this case. The subnet prefix length of the default gateway's IP address is not useful or needed.

**Comment by aboch** [comment]
No, I meant the IPAM contract says the IPAM driver must return an address in CIDR notation in response to `RequestAddress()`. This was required by reviewers of #489.

Libnetwork just passes that down to the network driver as network gateway.
You are right we could have passed that as a simple IP, but given the notation in which it is being passed now does not take anything away, I would not change this behavior now, to avoid any backward compatibility breakage with existing remote drivers.

This is why I am suggesting to fix the documentation.
