### ISSUE TITLE
Multiple endpoints for a container in an overlay network

### ISSUE THREAD

**Issue by doonhammer** [docker/libnetwork#1760]
We are trying to bring up a container that has two interfaces in the same network, using OVN/OVS overlay. We are getting an error message from the docker daemon:
Error response from daemon: service endpoint with name app1 already exists

I assume that multiple endpoints for a container are not currently allowed. Is this a fundamental architect problem or something that can be fixed in a future release?

Regards

John

**Comment by fcrisciani** [comment]
@doonhammer this is a design choice, where there will be only 1 endpoint per network.
