### ISSUE TITLE
 IPVS in libnetwork  query interfaces for services and destnations

### ISSUE THREAD

**Issue by fisherxu** [docker/libnetwork#1761]
I would like to know why IPVS in libnetwork does not provide query interfaces for services and destnations？

**Comment by dhilipkumars** [comment]
cc @aboch @mavenugo 
Yes.  We like libnetwork's ipvs library we want to vendor it into another project like kubernetes, the two main api's that are missing is GetServices and GetDestinations.   Are there any plans of adding them in the future?

**Comment by mavenugo** [comment]
@dhilipkumars I have plans for doing something similar. I think it is better to work together in making that happen (instead of having 2 different efforts). WDYT ?

**Comment by dhilipkumars** [comment]
@mavenugo sure, Great News. We like the idea.  Me and @fisherxu work for the same team.  Please tell us more about how we can help you expidate this.

**Comment by mavenugo** [comment]
@dhilipkumars @fisherxu can you pls signup to docker-community slack channel : https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/ and we can discuss the mechanics there ?
You can join the #docker-networking channel in the docker-community slack channel and we discuss further.

**Comment by mavenugo** [comment]
@dhilipkumars @fisherxu Based on the discussion we had, I think it is a good idea to have such a functionality in this package. Pls go ahead and push a PR if you can.

**Comment by dhilipkumars** [comment]
@mavenugo Thanks Madhu, we will send you the PR ASAP.

**Comment by dhilipkumars** [comment]
https://github.com/docker/libnetwork/pull/1770

**Comment by dhilipkumars** [comment]
the PR is merged @fisherxu Please close this issue.

**Comment by fisherxu** [comment]
@dhilipkumars done
