### ISSUE TITLE
service discovery between service task and unmanaged container takes long at times

### ISSUE THREAD

**Issue by sanimej** [docker/libnetwork#1768]
In a three node cluster with an attachable overlay network..

node 1 - has a container running on the attachable network
node 2 - has a service task on the same  network and also publishes a port
node 3 - accesses the published port of the service task, which does a name lookup (in go code) for the name of the container in node 1.

This works instantly most of the time. But sometimes it takes 10+ seconds to work. Creating this issue to identify what causes this delay.

**Comment by aluzzardi** [comment]
Happened again: https://ci.qa.aws.dckr.io/job/docker/job/docker-e2e/job/master/122/execution/node/45/log/


```
20:44:30 --- FAIL: TestAttachableNetwork (45.79s)
20:44:30 	assertions.go:226: 
                          
	Error Trace:	network_test.go:261
20:44:30 		
	Error:      	Received unexpected error:
20:44:30 		
	            	fetching http://172.31.1.167:30000/service-discovery?v4=TestAttachableNetworkContainer1768da9b-3528-464b-9569-cd5d33650 failed
```

I believe we were using a fresh master.
