### ISSUE TITLE
request bridge not created by "createTestNetwork" in libnetwork_test.go

### ISSUE THREAD

**Issue by baoyonglei** [docker/libnetwork#181]
libnetwork_test.go: createTestNetwork
network, err := controller.NewNetwork(networkType, networkName,
		libnetwork.NetworkOptionGeneric(netOption))

 the caller transfers the "netOption", one example is in "TestBridge":
netOption := options.Generic{
		"BridgeName":            bridgeName,
		"AddressIPv4":           subnet,
		"FixedCIDR":             cidr,
		"FixedCIDRv6":           cidrv6,
		"EnableIPv6":            true,
		"EnableIPTables":        true,
		"EnableIPMasquerade":    true,
		"EnableICC":             true,
		"AllowNonDefaultBridge": true} 
function "parseNetworkOptions" in bridge.go wil parse the option by the way
   genericData, ok := option[netlabel.GenericData]
they are not math, so the requested bridge will not created.

the solution is to change libnetwork_test.go: createTestNetwork:
"   ....
   	netGenericOption := make(map[string]interface{})
	netGenericOption[netlabel.GenericData] = netOption

	network, err := controller.NewNetwork(networkType, networkName,
		libnetwork.NetworkOptionGeneric(netGenericOption))
"

**Comment by baoyonglei** [comment]
@mavenugo  Can you check if this is a really issue. if so, can I take place to resolve it?

**Comment by aboch** [comment]
@baoyonglei Thanks for catching this.
Yes we need the fix.
