### ISSUE TITLE
IPAM allocating already in use networks

### ISSUE THREAD

**Issue by greenboxal** [docker/libnetwork#1819]
We had an issue in our company network today that was caused by docker/libnetwork. IPAM allocator created a network on 192.168.0.0/20 which is our LAN.

When that happened, as the network created is bridged-- default on docker-compose at least--, one of our development machines started to answer ARP who-has requests on behalf of our default gateway (192.168.0.1).

How can we prevent this to happen? I can imagine that it may have happened to several people already. Docker shouldn't be allowed to take a network that may be used outside of the container.

**Comment by sanimej** [comment]
For bridge networks docker IPAM uses the following range of IPs by default, `172.17-31.x.x/16, 192.168.x.x/20`.

These are by default, you can change it using the `--subnet` option for network create.

`docker network create -d bridge --subnet=172.1.0.0/16 testnet`

subnet to be used for the network can also be specified in the compose file.

**Comment by sanimej** [comment]
Closing this issue. Feel free to ask here if you have any other questions.

**Comment by greenboxal** [comment]
This is ok in a production environment, but definitely not ok in a development one.

Imagine I have hundreds of docker-compose projects, each one with a different network, how could I manage all those network addresses? Even worse, what if I hardcoded some specific network CIDR that works for me, but not for the other developers in the project?

Docker should definitely address that as it is still probably more used for development than in production.
