### ISSUE TITLE
DOCKER-INGRESS trumps DOCKER-USER

### ISSUE THREAD

**Issue by trapier** [docker/libnetwork#1827]
**Description**

The `DOCKER-INGRESS` chain is inserted above the `DOCKER-USER` chain the first time an ingress mode port is published.

**Steps to reproduce the issue:**
1. Intall Docker 17.06 CE
1. Form a two-node swarm with one manager and one worker
1. Start a service on the worker 

        docker service create --name listen --constraint node.role==worker nginx

1. Add a published port to the service

        docker service update --publish-add 8000:80 listen

**Describe the results you received:**

On the manager node:

    Chain FORWARD (policy DROP 0 packets, 0 bytes)
     pkts bytes target     prot opt in     out     source               destination
        0     0 DOCKER-INGRESS  all  --  *      *       0.0.0.0/0            0.0.0.0/0
        0     0 DOCKER-USER  all  --  *      *       0.0.0.0/0            0.0.0.0/0
    ...

**Describe the results you expected:**

On the manager node:

    Chain FORWARD (policy DROP 0 packets, 0 bytes)
     pkts bytes target     prot opt in     out     source               destination
        0     0 DOCKER-USER  all  --  *      *       0.0.0.0/0            0.0.0.0/0
        0     0 DOCKER-INGRESS  all  --  *      *       0.0.0.0/0            0.0.0.0/0
    ...

**Output of `docker version`:**

```
$ docker version
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:20:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:21:56 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
[vagrant@node01 ~]$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.06.0-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: xkg8qatmicxgd3f7svxnquh9l
 Is Manager: true
 ClusterID: 7hh3eimfcqou24um83q7sdl83
 Managers: 1
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Root Rotation In Progress: false
 Node Address: 192.168.121.237
 Manager Addresses:
  192.168.121.237:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.21.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 2.288GiB
Name: node01
ID: N6ZC:323C:2ZVX:JP3B:VV7J:V22X:LG6B:M4P7:HRKJ:BSRT:Q6UJ:Y26P
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: bridge-nf-call-ip6tables is disabled
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

```
CentOS Linux release 7.3.1611 (Core) 
```

**Comment by thaJeztah** [comment]
ping @fcrisciani @sanimej

**Comment by wenjianhn** [comment]
I'll take a look at it.
