### ISSUE TITLE
Improve Build Image in Makefile

### ISSUE THREAD

**Issue by dave-tucker** [docker/libnetwork#184]
After re-creating my `boot2docker` environment, libnetwork would no longer build.
I had to `rm libnetwork-build.created` first.

We should probably have a better mechanism to check whether the image exists before building it.
Perhaps something like `docker images | grep libnetwork-build > /dev/null  && created=true || created=false`

**Comment by codergr** [comment]
I could help on that in the process of learning the enviroment

**Comment by dave-tucker** [comment]
Thanks @codergr, if you have  the time and patience to push a patch to the Makefile it would be most appreciated!

**Comment by codergr** [comment]
Hi @dave-tucker I performed the necessary changes by mistake I issued a PR but I guess this was not required since it is registered as an issue thus I closed it. Let me know of any comments. Cheers.

**Comment by fcrisciani** [comment]
At the moment we have `make force-clean` that takes care of removing that file and starting fresh
