### ISSUE TITLE
TestMapTCPPorts and TestMapUDPPorts fails

### ISSUE THREAD

**Issue by LK4D4** [docker/libnetwork#189]
With errors like:
```
mapper_test.go:55: Failed to allocate port: Error starting userland proxy: listen tcp 192.168.0.1:80: bind: cannot assign requested address
```
I'm running test just by:
```
make all
```

**Comment by mrjana** [comment]
@LK4D4 Works fine for me. `make all` tests stuff inside a container as root so binding to port 80 should not be a problem. Can you post the whole test log?

**Comment by LK4D4** [comment]
@mrjana Problem is IP address, not port. Now I don't understand how it's even work on some machines :)

**Comment by mrjana** [comment]
@LK4D4 hmm... didn't take a closer look at the test case. The IP address doesn't even exist. Not sure how it's working for us and in circle-ci. Will have to debug further

**Comment by mavenugo** [comment]
:confused: me neither ... kernel maybe ?

**Comment by mavenugo** [comment]
@LK4D4 @mrjana am okay to revert the tests to use mockproxy .... now that we are anyways discouraging using the userland-proxy feature.

**Comment by mrjana** [comment]
@mavenugo I am fine with reverting the test case
