### ISSUE TITLE
Faulty test?

### ISSUE THREAD

**Issue by thaJeztah** [docker/libnetwork#1906]
While reviewing https://github.com/docker/cli/pull/434#pullrequestreview-55947949, I noticed this test uses `com.docker.network.mtu`. Should this be `com.docker.network.driver.mtu` ?

https://github.com/docker/libnetwork/blob/19ac3ea7f52bb46e0eb10669756cdae0c441a5b1/libnetwork_test.go#L413-L431

ping @fcrisciani @abhinandanpb

**Comment by abhinandanpb** [comment]
@thaJeztah yes does look like it https://github.com/docker/libnetwork/blob/af59385de01d1ab919f176c40ddc1a1044452da7/netlabel/labels.go#L37

**Comment by thaJeztah** [comment]
Opened https://github.com/docker/libnetwork/pull/1907
