### ISSUE TITLE
[macvlan] Cant communicate with host and container 

### ISSUE THREAD

**Issue by gabrielfsousa** [docker/libnetwork#1915]
what i'm doing wrong ? (host cant ping container and container cant ping host)
my host ip is 172.16.9.151

`docker network create -d macvlan --subnet=172.16.9.0/24 --gateway=172.16.9.1 -o parent=eno16780032 macvlan0`

`docker run --net=macvlan0 --ip=172.16.9.149 -v /mnt/tomcat_PROD/conf:/opt/tomcat/conf -v /mnt/tomcat_PROD/redouteapps:/opt/tomcat/redouteapps -p 8030:8030 -d docker01:5000/itsqd/alpine-oracle-tomcat`

**Comment by mavenugo** [comment]
@gabrielfsousa from : https://docs.docker.com/engine/userguide/networking/get-started-macvlan/

```
Note: In Macvlan you are not able to ping or communicate with the default namespace IP address. For example, if you create a container and try to ping the Docker host’s eth0 it will not work. That traffic is explicitly filtered by the kernel modules themselves to offer additional provider isolation and security.
```

**Comment by fcrisciani** [comment]
@gabrielfsousa I'm closing it for now considering it got the answer
