### ISSUE TITLE
Network statistics for number of packets REJECTed

### ISSUE THREAD

**Issue by freva** [docker/libnetwork#1922]
https://github.com/docker/libnetwork/blob/24bb72a8dcfe0b58958414890c8f4138b644b96a/osl/interface_linux.go#L196:L201
There is a network statistic for packet `errors` and `dropped`, but there is no statistic for packets `rejected`, what is the reason for this limitation? Any chance this will be added any time soon?

**Comment by wenjianhn** [comment]
There is no rejected field in the following output.
```
$ ifconfig vboxnet0
vboxnet0  Link encap:Ethernet  HWaddr 0a:00:27:00:00:00  
          inet addr:192.168.56.1  Bcast:192.168.56.255  Mask:255.255.255.0
          inet6 addr: fe80::800:27ff:fe00:0/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:58763540 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:4115419462 (4.1 GB)

```
Does errors + dropped + overruns equals to the "rejected" packets?

Or did you mean the rejected packets by iptables rules?

**Comment by freva** [comment]
Rejected by iptables

**Comment by wenjianhn** [comment]
Statistic of an interface is a network layer 2 thing. And docker iptables rules work at layer 3.
I don't think the rejected packets will be added to the statistic of an interface.

**Comment by freva** [comment]
I see. I just noticed that if my last rule in `iptables` is `DROP`, then the metric was increased, but when it's `REJECT`, there was no metric. 

But it makes if the metrics comes from the output you have above.

**Comment by fcrisciani** [comment]
As @freva was correctly saying iptables stats are different from interface stats, so nothing can really be done here.
