### ISSUE TITLE
Libnetwork housekeeping

### ISSUE THREAD

**Issue by fcrisciani** [docker/libnetwork#1926]
We are starting an effort to cleanup the backlog of open issues and PRs that are currently open on the libnetwork project.

All the issues that do not have activity in the last `6 months` are going to receive a warning message notifying that if there is no further activity they will be closed in a week.

This will allow us to identify what is still important for the community and for the success of the project.

Feel free to post here if you have concern, comments

**Comment by mavenugo** [comment]
SGTM

**Comment by fcrisciani** [comment]
housekeeping completed

**Comment by NullVoxPopuli** [comment]
I'm still getting the OpenVPN + `ERROR: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network
` error. :-\

**Comment by derTobsch** [comment]
@NullVoxPopuli same for me. I am on ubuntu 16.04 and with vpn on I cannot start docker containers
