### ISSUE TITLE
Support flush API for IPVS service

### ISSUE THREAD

**Issue by m1093782566** [docker/libnetwork#1930]
We vendor libnetwork's ipvs library into kubernetes and want a batch API for flushing IPVS services.

Do we have any plan to support the flush API for IPVS service? Without the Flush API, currently we delete services one by one, which is inefficient.

**Comment by m1093782566** [comment]
@mrjana @mavenugo @dhilipkumars @allencloud Any thoughts?

**Comment by mavenugo** [comment]
@m1093782566 Yes. We did add the `ipvsCmdFlush` constant for supporting this functionality. But I guess its missed in the library. Thanks for the PR. I will review and provide feedback.

**Comment by m1093782566** [comment]
I am going to close this issue since the related PR got merged. Thanks all.
