### ISSUE TITLE
local container cant use a swarm network

### ISSUE THREAD

**Issue by gabrielfsousa** [docker/libnetwork#1940]
version: 17.06.1-ce

how a local container uses a swarm network ?

i have this error:

> docker: Error response from daemon: Could not attach to network my-s: rpc error: code = 7 desc = network my-s not manually attachable

my-s is my overlay searm network

**Comment by fcrisciani** [comment]
@gabrielfsousa you have to create the network as: `docker network create --attachable -d overlay <network name>`
