### ISSUE TITLE
Can not run container after libnetwork integrated to Docker

### ISSUE THREAD

**Issue by hqhq** [docker/libnetwork#198]
It's a big problem but no one reported because I got it on ARM64. Anyway I don't think it's an architecture related problem.

Error message from daemon:
```
ERRO[0006] leaving endpoint failed: no container attached to the endpoint
ERRO[0006] Handler for POST /containers/{name:.*}/start returned error: Cannot start container 729e0b1a4b68c970b1067be56c9acd741dc9260436aa41a893b354ecb61a5246: Link not found
ERRO[0006] HTTP Error                                    err=Cannot start container 729e0b1a4b68c970b1067be56c9acd741dc9260436aa41a893b354ecb61a5246: Link not found statusCode=404
```
Not much useful, after some digging, I found error occured in libnetwork:
```
container.AllocateNetwork()
  -> ep.Join()
    -> sb.AddInterface()
      -> netlink.LinkByName()
        -> execGetLink()
          -> req.Execute()
```
here it failed in this block:
```
239                         if m.Header.Type == syscall.NLMSG_ERROR {
240                                 native := NativeEndian()
241                                 error := int32(native.Uint32(m.Data[0:4]))   // error = -19
242                                 if error == 0 {
243                                         break done
244                                 }
245                                 return nil, syscall.Errno(-error)
246                         }
```

This kind of error (-19 NODEV) looks like lack of some kernel support, when I run Docker on arm64 (that's before libnetwork integrated to Docker), I met exactly same error (that time was using netlink code in libcontainer), finially I found it's because I enabled veth as module and not loaded it, after enable veth as y, Docker worked well.

After libnetwork integrated to Docker (I bisected, exactly after this integration), I got this error again, I thought maybe libnetwork using some features depend on some kernel config, which is enabled by default in most distributions and not mentioned in check-config.sh. Since I worked on a fresh kernel, got this problem.

I'm not a network expert, hope can get some help here. Thanks.

PS: check-config.sh is all green in my box, they are all enabled (not as module). And I already tried to enable all netlink related configs, no lock.
```
$ cat .config | grep NETLINK
CONFIG_NETFILTER_NETLINK=y
CONFIG_NETFILTER_NETLINK_ACCT=y
CONFIG_NETFILTER_NETLINK_QUEUE=y
CONFIG_NETFILTER_NETLINK_LOG=y
CONFIG_NF_CT_NETLINK=y
CONFIG_NF_CT_NETLINK_TIMEOUT=y
CONFIG_NF_CT_NETLINK_HELPER=y
CONFIG_NETFILTER_NETLINK_QUEUE_CT=y
CONFIG_NETLINK_MMAP=y
CONFIG_NETLINK_DIAG=y
CONFIG_SCSI_NETLINK=y
CONFIG_QUOTA_NETLINK_INTERFACE=y
```

**Comment by mavenugo** [comment]
@hqhq Thanks for bringing this to our attention.
We dont have access to this specific environment to try it out.
libnetwork uses https://github.com/vishvananda/netlink as our netlink library.
Can you please do some investigation on the assumptions this library has for your environment ?

Also, it would be helpful if you can narrow down the specific issue that you mentioned that got resolved in earlier version of docker that is resurfacing with libnetwork. That will help quickly isolate the problem and probably a PR on the above netlink library.

**Comment by LK4D4** [comment]
@hqhq Thanks for report though. Can you try to run `vishvananda/netlink` tests on your machine?

**Comment by hqhq** [comment]
@mavenugo Last time, I got this error and fixed by enable CONFIG_VETH, then with the same kernel, I updated Docker code, I got this error again.

**Comment by hqhq** [comment]
@LK4D4 , seems lots of operation not supported error:
```
root@linaro-developer:/go/src/github.com/docker/docker/vendor/src# go test github.com/vishvananda/netlink/
--- FAIL: TestLinkAddDelDummy (0.16s)
        testing.go:278: operation not supported
--- FAIL: TestLinkAddDelVlan (0.25s)
        testing.go:278: operation not supported
--- FAIL: TestLinkAddDelMacvlan (0.00s)
        testing.go:278: operation not supported
--- FAIL: TestLinkAddDelBridgeMaster (0.35s)
        testing.go:278: operation not supported
--- FAIL: TestLinkSetUnsetResetMaster (0.00s)
        testing.go:278: operation not supported
--- FAIL: TestLinkSetNs (0.82s)
        testing.go:278: Failed to set basens
--- FAIL: TestLinkAddDelVxlan (0.29s)
        testing.go:278: operation not supported
--- FAIL: TestLinkAddDelIPVlanL2 (0.00s)
        testing.go:278: operation not supported
--- FAIL: TestLinkAddDelIPVlanL3 (0.00s)
        testing.go:278: operation not supported
--- FAIL: TestLinkByIndex (0.00s)
        testing.go:278: operation not supported
--- FAIL: TestLinkSet (0.00s)
        testing.go:278: operation not supported
--- FAIL: TestNeighAddDel (0.00s)
        testing.go:278: operation not supported
--- FAIL: TestProtinfo (0.04s)
        testing.go:278: operation not supported
--- FAIL: TestXfrmPolicyAddDel (0.00s)
        testing.go:278: protocol not supported
--- FAIL: TestXfrmStateAddDel (0.23s)
        testing.go:278: protocol not supported
FAIL
FAIL    github.com/vishvananda/netlink  4.699s
```

on x86, also have two cases failed:
```
root@4363725a48f1:/go/src/github.com/docker/docker/vendor/src# go test github.com/vishvananda/netlink/
--- FAIL: TestLinkAddDelIPVlanL2 (0.06s)
        link_test.go:21: operation not supported
--- FAIL: TestLinkAddDelIPVlanL3 (0.00s)
        link_test.go:21: operation not supported
FAIL
FAIL    github.com/vishvananda/netlink  1.354s
```

**Comment by dave-tucker** [comment]
I think this is related  to the `SET_NS` syscall - AFACIT it should be `375` for arm64
I'll push a patch to the netlink library and would be grateful if you could test @hqhq

**Comment by dave-tucker** [comment]
@hqhq please see the patch in to `vishvananda/netns`. Can you please checkout my patch and re-run the `vishvananda/netlink` tests? Thanks in advance!

**Comment by vishvananda** [comment]
@hqhq fyi the two tests failing on x86 are likely because your kernel is too old to support ipvlans. Support was added in 3.19

**Comment by dave-tucker** [comment]
Closing this as I believe the issue has been resolved
