### ISSUE TITLE
ndots issue on daemon config for services

### ISSUE THREAD

**Issue by fcrisciani** [docker/libnetwork#1988]
If the dns options is specified in the daemon.json like:

```
{
  "debug" : true,
  "dns-opts" : [
    "ndots:1"
  ],
  "experimental" : true
}
```

If a service is launched on a network like:
`docker service create --network net1 alpine top`

the resolv.conf results in:
```
options ndots: 2 ndots:0
```
Looks like the daemon config is ignored and the ndots:0 is appended blindly

**Comment by joeabbey** [comment]
Looks like ndots is almost entirely ignored.  In sandbox_dns_unix.go, the number of dots is parsed only for validation.  As you mentioned it is appended blindly, see sandbox_dns_unix.go:384: 	
`dnsOptionsList = append(dnsOptionsList, resOptions...)
`
This probably works for forwarding unsupported options on... but seems like it would be easy to "merge" in the dnsOpts loop above.

Moreover, ndots is treated (by libnetwork) as a boolean setting which changes resolver behavior.

This was introduced in e51268a:
https://github.com/docker/libnetwork/commit/e51268a42951a3b12b87be5fc87a332e1fd927a2

**Comment by joeabbey** [comment]
Hmm.. looks like no test case was added into that commit either

**Comment by fcrisciani** [comment]
@joeabbey I created a patch, and will have to add some tests on top. Feel free to take a look and review it
