### ISSUE TITLE
Oct 26 15:25:48 jhou-swarm dockerd: time="2017-10-26T15:25:48.659524166+08:00" level=error msg="Handler for POST /v1.32/containers/a67f92345ad005039c73a6549f78c78c03b47371b346fcfb5db2246cf7024336/start returned error: failed to update the store state of sandbox: failed to update store for object type *libnetwork.sbState: json: cannot unmarshal object into Go struct field sbState.ExtDNS of type string"

### ISSUE THREAD

**Issue by kingAndGithub** [docker/libnetwork#2003]
today, i run command:
`docker run -d -t 196e0ce0c9fb bash`
i got the message:
`[root@jhou-swarm ~]# docker run -d -t 196e0ce0c9fb bash
a67f92345ad005039c73a6549f78c78c03b47371b346fcfb5db2246cf7024336
docker: Error response from daemon: failed to update the store state of sandbox: failed to update store for object type *libnetwork.sbState: json: cannot unmarshal object into Go struct field sbState.ExtDNS of type string.`
why this happened?

`Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:41:23 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:49 2017
 OS/Arch:      linux/amd64
 Experimental: false`

my system is:
`CentOS Linux release 7.4.1708 (Core)`

**Comment by kingAndGithub** [comment]
the kernel is version:
 3.10.0-693.5.2.el7.x86_64

**Comment by kingAndGithub** [comment]
@mavenugo @fcrisciani , can you have a look it?
no matter i enable the  live-restore, the response are the same

**Comment by mavenugo** [comment]
@kingAndGithub I dont know exactly how you ran into this issue. I remember seeing this during one of the RCs of 17.03 - https://github.com/docker/libnetwork/pull/1620, which got resolved during the RC phase. By any chance you were using an RC build or docker master few months back and then later upgraded it to 17.09-ce ?

Can you pls take a backup of `/var/lib/docker/network/files/local-kv.db`, stop the daemon and remove this file before starting the daemon ?

**Comment by kingAndGithub** [comment]
@mavenugo yes, you are right, i upgrade the linux kernel from 7.2 to currently 7.4,  but the docker didn't be upgraded but installed directly.
However, the issue has been fixed with your suggestion, thanks very much.

**Comment by mavenugo** [comment]
You are welcome. I will close this issue. Pls feel free to reopen it if you face this issue again.
