### ISSUE TITLE
vendor problem

### ISSUE THREAD

**Issue by rudyfly** [docker/libnetwork#2022]
I have used libnetwork, it contains netlink package in vendor, I also use netlink package in my vendor directory, it conflicts with libnetwork's vendor, how to deal with it？

**Comment by fcrisciani** [comment]
when you vendor libnetwork in your project you won't bring the vendor folder of libnetwork with it, this is what is happening already in https://github.com/moby/moby, if you navigate the folders where libnetwork is vendored you will find only the libnetwork files not its dependencies: https://github.com/moby/moby/tree/master/vendor/github.com/docker/libnetwork

**Comment by fcrisciani** [comment]
(Closing for now, let me know if you have further questions)
