### ISSUE TITLE
DNS returns NXDOMAIN for MX request of existing host

### ISSUE THREAD

**Issue by analogic** [docker/libnetwork#2026]
```
$ dig a container
...
status: NOERROR
...
container.		600	IN	A	172.18.0.3

$ **dig mx container
...
status: NXDOMAIN**
```

Second request should respond NOERROR with empty data and not NXDOMAIN. This behaviour is problem for delivering emails between containers because some delivery servers will not fall back from MX record to A record assuming there is no such domain.

**Comment by fcrisciani** [comment]
code merged ref:#2041
