### ISSUE TITLE
openvswitch vlan/vxlan support?

### ISSUE THREAD

**Issue by liuflylove666** [docker/libnetwork#2034]
@mavenugo 
can libnetwork support openvswitch vlan/vxlan driver ? can you develop drivers support this ?

**Comment by fcrisciani** [comment]
@liuflylove666 there is currently no plan for this, but we accept PR for new drivers.
Closing this issue for now, and maybe if/when there will be the intention, we can open a design spec issue for feedback before implementation starts.
