### ISSUE TITLE
 cannot use &tv (type *syscall.Timeval) as type *unix.Timeval in argument to sock.SetSendTimeout

### ISSUE THREAD

**Issue by nim-nim** [docker/libnetwork#2048]
Hi,

With:

github.com/vishvananda/netlink 1882fa99fc5adc217f354c6f37a172876877f77d
github.com/vishvananda/netns   be1fbeda19366dea804f00efff2dd73a1642fdcc

(latest current versions)

+ go test -compiler gc -ldflags '-X github.com/docker/libnetwork/version.GitSHA=83862f448a88190ada5dec39a9aded5eb4f655f9 -extldflags '\''-Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld '\'''
# github.com/docker/libnetwork/ipvs
../../ipvs/ipvs.go:94:32: cannot use &tv (type *syscall.Timeval) as type *unix.Timeval in argument to sock.SetSendTimeout
../../ipvs/ipvs.go:98:35: cannot use &tv (type *syscall.Timeval) as type *unix.Timeval in argument to sock.SetReceiveTimeout
# github.com/docker/libnetwork/drivers/overlay
../../drivers/overlay/ov_network.go:704:34: cannot use &tv (type *syscall.Timeval) as type *unix.Timeval in argument to nlSock.SetReceiveTimeout

**Comment by fcrisciani** [comment]
@nim-nim 
on which platform are you trying to compile it?

Looking at the code in master the commit that introduced that code is:`https://github.com/docker/libnetwork/commit/df6600248773b327cee184907914d4c6338e8a3d` but it passes the right type

**Comment by nim-nim** [comment]
I'm testing on linux (fedora devel)

As a workaround I needed to downgrade github.com/vishvananda/netlink to b2de5d10e38ecce8607e6b438b6d174f389a004e but that kind of sucks (need to manage a specific commit in addition to the latest one)

**Comment by fcrisciani** [comment]
@nim-nim that's the one that we are currently vendoring
Just found out that this PR: https://github.com/vishvananda/netlink/pull/286
changed the type

**Comment by nim-nim** [comment]
@fcrisciani I know, I'm just trying to cut down on the obsolete vendoring that accumulated right and left :(

**Comment by fcrisciani** [comment]
@nim-nim not sure how big of a change is to update libnetwork, maybe should not be so big, but will definitely require a revendoring of the api

**Comment by fcrisciani** [comment]
next time that we will update the library we will take care of that. closing at the moment

**Comment by roffe** [comment]
@fcrisciani Did you ever get around to fix this, i just ran in to it when trying to update some projects
