### ISSUE TITLE
Feature req IPVS ActiveConn InActConn in SvcStats/Service struct

### ISSUE THREAD

**Issue by roffe** [docker/libnetwork#2057]
It would be nice if we could get ActiveConn & InActConn in SvcStats or Service struct of IPVS package like https://github.com/mqliang/libipvs/blob/master/api.go#L75 has done.

I'm currently writing on a PR for kube-router to fix some of our metrics and this is the missing piece of stats to be able to produce a nice dashboard showing the connections.

Right now we have SvcStats.connections which will only produce a total number since service creation and not the current Act/InAct conns

Cheers!

**Comment by amoghe** [comment]
@roffe  I see that the link you pointed to exposes the `ActiveConns` and `InactiveConns` on the `Destination` struct.

Similarly, this library defines the `Destination` like so:
```
type Destination struct {
	Address             net.IP
	Port                uint16
	Weight              int
	ConnectionFlags     uint32
	AddressFamily       uint16
	UpperThreshold      uint32
	LowerThreshold      uint32
	ActiveConnections   int
	InactiveConnections int
	Stats               SvcStats
}
```

So it has parity with what you linked to. Is there something else that you are requesting?

**Comment by roffe** [comment]
Mega stale issue, forgott it even existed. Ill get back to you in 8 months if i have any questions
