### ISSUE TITLE
Allow multiple endpoints per network

### ISSUE THREAD

**Issue by hongbin** [docker/libnetwork#2060]
It seems to me that Docker/Libnetwork doesn't allow to have multiple endpoints per network?

  $ docker network connect bridge caf25b6d5ef7
  Error response from daemon: endpoint with name dazzling_tereshkova already exists in network bridge

If no, this issue proposes to add support for that. The use case we have is from kuryr-libnetwork which is a network plugin that maps docker network model to OpenStack network model. OpenStack neutron allows to have multiple neutron ports (endpoint equivalent) per network, but this feature is not exposed to the container world due to this issue.

**Comment by fcrisciani** [comment]
@hongbin, there is no real plan to support multiple endpoints for the same network. That is not in line with the CNM model. Will proceed and close this one

**Comment by hongbin** [comment]
@fcrisciani any reason why the CNM model cannot be extend to support multiple endpoints per network? We have a real use cases for this. For example, in NFV scenario, we wanted to create two endpoints for two interfaces in order to configure the bonding: https://community.mellanox.com/s/article/howto-configure-lag-over-vf--connectx-3-pro-x
