### ISSUE TITLE
network rm (via API & UI) must fail for reserved networks

### ISSUE THREAD

**Issue by mavenugo** [docker/libnetwork#207]
Reserved networks such as (bridge, none and host) should not honor `network rm`.

**Comment by codergr** [comment]
I could help on this any hints where to focus ?

**Comment by mavenugo** [comment]
@codergr thanks. @nerdalert beat you to it :) 
We have no short of issues to handle, will check with you @codergr

**Comment by dave-tucker** [comment]
Closed in #208
