### ISSUE TITLE
docker host access overlay network?

### ISSUE THREAD

**Issue by llitfkitfk** [docker/libnetwork#2073]
How to config overlay network that docker host can access?

for example:

```
docker network create -d overlay --opt xxx overlay-network

docker plugin install rexray/s3fs \
S3FS_OPTIONS="allow_other,use_path_request_style,nonempty,url=http://<overlay-network-ip>:9000" \
S3FS_ENDPOINT="http://<overlay-network-ip>:9000" \
S3FS_ACCESSKEY="" \
S3FS_SECRETKEY=""

```

**Comment by fcrisciani** [comment]
@llitfkitfk not sure I got what you mean with docker host but I will try to give you a couple of options.

1) expose port
You can create a swarm service and expose a port. This port will be accessible from any node of the cluster and the ingress network will take care of directing the traffic to the container that serve your application.

2) host networking
You can create a service where the containers are actually running in the host namespace. This way you don't have the network isolation and your service is available directly from the host where the container is running.

I would say also mac/vlan driver can be an option (https://docs.docker.com/network/macvlan/#create-a-macvlan-network) but maybe requires more info on your use case

**Comment by fcrisciani** [comment]
closing, lmk if there is further questions

**Comment by llitfkitfk** [comment]
@fcrisciani 

Thanks
