### ISSUE TITLE
ipvs.go:94:32: cannot use &tv (type *syscall.Timeval) as type *unix.Timeval in argument to sock.SetSendTimeout

### ISSUE THREAD

**Issue by nim-nim** [docker/libnetwork#2110]
With Go 1.9.4 x86_64 Linux

```
Testing: "/builddir/build/BUILD/libnetwork-2112cace8efd4c7b71daccbf54897871e205f293/_build/src/github.com/docker/libnetwork/ipvs"
+ GOPATH=/builddir/build/BUILD/libnetwork-2112cace8efd4c7b71daccbf54897871e205f293/_build:/usr/share/gocode
+ go test -buildmode pie -compiler gc -ldflags '-extldflags '\''-Wl,-z,relro  '\'''
# github.com/docker/libnetwork/ipvs
./ipvs.go:94:32: cannot use &tv (type *syscall.Timeval) as type *unix.Timeval in argument to sock.SetSendTimeout
./ipvs.go:98:35: cannot use &tv (type *syscall.Timeval) as type *unix.Timeval in argument to sock.SetReceiveTimeout
FAIL    github.com/docker/libnetwork/ipvs [build failed]
```

**Comment by fcrisciani** [comment]
@nim-nim the issue is not with go 1.9.4 but with the version of the netlink library that you are using to compile. For libnetwork you need to use the one that is vendored where the propotype of method is:
```
func (s *NetlinkSocket) SetSendTimeout(timeout *syscall.Timeval) error {
```
This is the commit that changed the prototype: https://github.com/vishvananda/netlink/commit/0e3b74dbe28f37fd911f9bca3565fdca33c03f29

**Comment by amoghe** [comment]
@fcrisciani is there a reason we can't simply cast the `syscall.Timeval` to `unix.Timeval` and not have to vendor the `vishvananda/netlink` library?

**Comment by fcrisciani** [comment]
@amoghe they are 2 different types, they are not castable to each other, you will need to convert one into the other, but anyway that is not the only dependency that we have with netlink.

**Comment by amoghe** [comment]
@fcrisciani  understood. But with `libnetwork` using its own `vendor` , I seem to be running into issues with getting `dep` to correctly recognize this dependency. It ends up pulling in `vishvananda/netlink` at `v1.0.0` (which is newer than the one vendored here).

I understand this isn't strictly a libnetwork issue - but I'm not sure how to work around this. Any thoughts?

**Comment by fcrisciani** [comment]
@amoghe in dep you can force with a constraint to get a specific commit id

**Comment by amoghe** [comment]
True, but since I'm not explicitly imported that lib, this is a little fragile. See this message from dep:
```
"github.com/vishvananda/netlink" is not imported by your project, and has been temporarily added to Gopkg.lock and vendor/.
If you run "dep ensure" again before actually importing it, it will disappear from Gopkg.lock and vendor/.
```

**Comment by amoghe** [comment]
I'm wondering if using the updated type will be sufficient for us to move to the `1.0.0` tag of the netlink library. Do you have any ideas as to what else would need to be handled to facilitate the version bump up?

**Comment by fcrisciani** [comment]
try this:
```
[[contraint]]
name = "github.com/vishvananda/netlink"
revision = "b2de5d10e38ecce8607e6b438b6d174f389a004e"
```

**Comment by fcrisciani** [comment]
not sure, I did not spend time trying to change the revision, it can be easy as only fixing that type but the problem can still appear when libnetwork is vendored inside moby/mody for integration

**Comment by fcrisciani** [comment]
you can give it a shot, but I would try to bump in moby/moby directly and identify all the places where there is the issue

**Comment by amoghe** [comment]
Does `moby/moby` consume this lib? If so, then here's what I'll do:
1. update this lib
2. try building moby with this lib

Or are you suggesting something else?

**Comment by thaJeztah** [comment]
I had a PR that bumped the version; https://github.com/docker/libnetwork/pull/2118, but looks like it needs an update 😅

**Comment by amoghe** [comment]
@thaJeztah  thats from March . Any chance you could resuscitate it? :-)

**Comment by thaJeztah** [comment]
netlink was updated in PR https://github.com/docker/libnetwork/pull/2366 (revendor in moby/moby is done in https://github.com/moby/moby/pull/39054)
