### ISSUE TITLE
Structs for REST API should be tagged to produce proper output when marshalled

### ISSUE THREAD

**Issue by dave-tucker** [docker/libnetwork#217]
For example, we should use `network_type` in JSON instead of `NetworkType`.
This can be easily fixed using adding tags to the struct - see [here](http://golang.org/pkg/encoding/json/#Marshal)
/cc @aboch

**Comment by kunalkushwaha** [comment]
While testing still toml based config files are being used for libnetwork.

**Comment by kunalkushwaha** [comment]
New PR for same #237

**Comment by dave-tucker** [comment]
Thanks @kunalkushwaha - this LGTM
/cc @aboch

**Comment by thaJeztah** [comment]
@dave-tucker @kunalkushwaha I see https://github.com/docker/libnetwork/pull/237 was merged; does that mean this can be closed?

**Comment by kunalkushwaha** [comment]
@thaJeztah @dave-tucker The json tag are added and it works fine. So this Issue can be closed.

Though as one of comment by @dave-tucker at https://github.com/docker/libnetwork/pull/237#issuecomment-108029779

I think new issue can be created, to have a proper place to put types.go to avoid the reducendeny of this file.
