### ISSUE TITLE
API Versioning

### ISSUE THREAD

**Issue by erikh** [docker/libnetwork#221]
Are there plans for this? How will the URL structure change?

**Comment by dave-tucker** [comment]
@erikh I'm :+1: for versioning /cc @aboch

**Comment by aboch** [comment]
ATM, I am thinking the API version will not be part of the URL, but in the accept headers.
But given this is a contentious issue, we could also provide both ways.

As of now we also accept URLs coming from docker with docker API version as prefix (in order for libnetwork route to plug into docker router), but we ignore its value.

Whatever way we go, I'd prefer to keep libnetwork api version separate from docker api version, given libentwork is a individual separate ingredient of the docker solution.

**Comment by erikh** [comment]
+1!

Thanks for considering this.

**Comment by thaJeztah** [comment]
+1 for versioning

> ATM, I am thinking the API version will not be part of the URL, but in the accept headers.

Wondering how that will look, combined with accept content-type headers. Sounds more complicated to implement in a client, but perhaps because I don't see the full picture :)

**Comment by tomdee** [comment]
@dave-tucker Does this need a milestone assigning to make it into the 1.8 stable release?

**Comment by dave-tucker** [comment]
@tomdee good idea - i'll put it forward for 0.4
