### ISSUE TITLE
Setup container A's dns (using embedded dns server) from within container C

### ISSUE THREAD

**Issue by brubbel** [docker/libnetwork#2245]
Hi,
Possibly this is straightforward, but I cannot find a solution for this problem.

I'm trying to apply on-the-fly user-defined DNS settings for container(s) A by control-container C, without restarting A.

Running my application directly on the host instead of in C, it is easy: just make sure that /etc/resolv.conf picks up the changes. From within a container, not so easy as I hoped, as the /etc/resolv.conf is isolated for each container.
Of course I can run the application within A, but I don't like the idea of running many things in 1 container. Can the embedded dns server be queried/controlled (apart from the --dns flag on the command line at startup)?

Any ideas for the direction I should look into or just give up?
Thanks.

edit: if this is the wrong place to ask: please say so.

**Comment by ctelfer** [comment]
Yes, this is probably the right place for such a query.

As to the answer ... took a brief look through `resolver.go`, `sandbox_dns_unix.go` and `network.go`.  The external servers (taken from `/etc/resolv.conf`) should get set in `resolver.SetExtServers()`.   This only gets invoked once at container creation time.  So, no, there is no way to update the external DNS servers in use by the container's DNS proxy.  (It is also worth noting that `SetExtServers` limits the number of external servers for the container to query to 3.)

ATM, I can't think of any good way to handle such resolver updates dynamically w/ the existing code short of trying to bypass the proxy altogether.  (and that would prevent you from resolving container names).   Sorry.   I think changing the DNS list mid-stream will require a new feature in libnetwork and some new APIs in moby to make use of it.

**Comment by brubbel** [comment]
@ctelfer Thank you for the to-the-point answer!
Because this is neither a feature request nor a bug, I'll close this issue.
