### ISSUE TITLE
allow overlay network to create overlapping subnet

### ISSUE THREAD

**Issue by eubnara** [docker/libnetwork#2246]
Since docker 18.06, I cannot make overlay networks which have the same subnet.
I think it is okay to share the same subnet between overlay networks because those are separated by network namespaces.
I referred to this issue(https://github.com/moby/moby/issues/26912#issuecomment-249549542).
If it is true that after Kernel >= 3.16 overlay networks can overlap the same subnet, it should be allowed to create overlay networks overlapping subnet.
If it is not allowed to make overlapping subnet even in overlay networks, subnet or ip depletion will happen.

**Comment by selansen** [comment]
Can you share the output and let me know what kind of error are you getting ? There was a discussion on how to handle overlapping network and how to address it in upcoming releases. 
You shouldnt see any error messages while creating network but service creation should fail in newly created overlapping network.

**Comment by eubnara** [comment]
@selansen 

Thanks for reply.

For example, I cannot make 2 overlays which use the same subnet.

```
$ docker -v
Docker version 18.06.0-ce, build 0ffa825

$ docker network create --driver overlay --subnet 192.168.0.0/24 demonet
dd4c90c08da08882f0255d5ce78f23d4fbf6a878e7123b864e9aad20949acc38

$ docker network create --driver overlay --subnet 192.168.0.0/24 demonet2
Error response from daemon: Pool overlaps with other one on this address space
```

If it is desired situation, I have to use choose a subnet in private network pools.(https://en.wikipedia.org/wiki/Private_network)
Usually, `10.0.0.0 – 10.255.255.255` range is already used for intra netwok, I have to choose among `172.16.0.0 – 172.31.255.255`, `192.168.0.0 – 192.168.255.255`.
It will be limitation about the number of overlay networks or containers inside one overlay network.

**Comment by abhi** [comment]
@eubnara we disabled overlapping subnet in recent releases since it was not fully implemented e2e. Let us know if you have any concerns.

**Comment by eubnara** [comment]
Okay I got it. Thanks for reply. :)
