### ISSUE TITLE
Is roadmap still valid?

### ISSUE THREAD

**Issue by olljanat** [docker/libnetwork#2315]
I noticed that [roadmap](https://github.com/docker/libnetwork/blob/master/ROADMAP.md) have not been updated over two years and I was wondering if those short-term goals are still valid or already handled?

**Comment by fcrisciani** [comment]
@olljanat right, that document is now obsolete and we are not really following it

**Comment by fcrisciani** [comment]
we can simply delete it if that creates confusion

**Comment by olljanat** [comment]
@fcrisciani actually I already created PR of it #2316 or did you mean drop whole file?

**Comment by fcrisciani** [comment]
I think we can also drop the file as a whole, we are not really planning to update it in the near future.

**Comment by olljanat** [comment]
@fcrisciani OK. Updated PR to remove it
