### ISSUE TITLE
Internal macvlan network overrides default gateway

### ISSUE THREAD

**Issue by lemrouch** [docker/libnetwork#2406]
I have container which needs to be connected to multiple overlay networks and one internal macvlan network.
Every time I connect the container to the macvlan network, it's default gateway will be set to non-existent default gateway.

I don't think internal networks should touch default gateway at all.

**Comment by chiragtayal** [comment]
Can you please provide the output you see?

**Comment by lemrouch** [comment]
Prepare two networks:
_docker network create --driver=overlay --attachable --scope=global --ip-range=10.10.10.0/24 --subnet=10.10.10.0/24 public_net_
_docker network create --driver=macvlan -o parent=enp1s0 --internal --attachable --ip-range=10.10.20.0/24 --subnet=10.10.20.0/24 private_net_

Run container let say with Debian:
_docker run -it --rm --network=public_net debian:latest /bin/bash_

Check the network in the container:
`root@6c1d0c80568b:/# ip r s`
`default via 172.18.0.1 dev eth1`
`10.10.10.0/24 dev eth0 proto kernel scope link src 10.10.10.2`
`172.18.0.0/16 dev eth1 proto kernel scope link src 172.18.0.3`

Connect the container to the macvlan internal network:
_docker network connect private_net 6c1d0c80568b_

Check the containet network again:
`root@6c1d0c80568b:/# ip r s`
`default via 10.10.20.1 dev eth2`
`10.10.10.0/24 dev eth0 proto kernel scope link src 10.10.10.2`
`10.10.20.0/24 dev eth2 proto kernel scope link src 10.10.20.2`
`172.18.0.0/16 dev eth1 proto kernel scope link src 172.18.0.3`

As you can see the container has default gateway set to 10.10.20.1 which is macvlan internal network range.

According to [documentation](https://docs.docker.com/v17.09/engine/userguide/networking/#user-defined-networks) this is not expected behavior:
> When a container is connected to multiple networks, its external connectivity is provided via the first non-internal network, in lexical order.

**Comment by lemrouch** [comment]
Ping.
Anybody out there?

**Comment by selansen** [comment]
@chiragtayal  PTAL.

**Comment by lemrouch** [comment]
Maybe chiragtayal is overloaded. Is there anyone else who can take a look?

**Comment by suwang48404** [comment]
@lemrouch 
can you provide some insight with regard to having internal macvlan network? what is it used for?
