### ISSUE TITLE
Change iptables data model

### ISSUE THREAD

**Issue by aboch** [docker/libnetwork#242]
- iptables initialization in bridge code should be split in driver and network specific steps

- iptables.NewChain() is invoked for driver specific config (for table iptables.Nat) and the context is not preserved in the caller, so it cannot be cleaned: We should move this call to driver initialization, this implies hairpin mode (!useUserlandProxy) has to be moved to driver configuration, as it is needed by the NAT table creation and because it is really a driver specific config, we cannot honor different hairpin settings for different bridge networks.

- The iptables.NewChain() method is misleading as we are not creating a new chain for each bridge instance creation. NewChain() should be called once at bridge driver creation (taking care of the NAT table only), and later at network creation  we should call a new iptables method like iptables.ProgramFilters()

- As of now iptables has a context (Chain) which is tied to the bridge name (read bridge-network in multi-bridge network). This structure name should change, as it carries chain name and metadata as bridge name and table name.

Either we change the structure name, for example Chain -> NetworkRuleSet

**Comment by mbanikazemi** [comment]
#dibs
