### ISSUE TITLE
parseIP Error ip=[172 17 0 2 0 0 0 0 0 0 0 0 0 0 0 0]

### ISSUE THREAD

**Issue by amitgurav04** [docker/libnetwork#2431]
I am using libnetwork/ipvs to fetch the destinations for each ipvs service.

following is the code statement.

`		destinations, err := c.ipvsHandle.GetDestinations(service)
`

After latest commit I am getting error while fetching destinations of service.

parseIP Error ip=[172 17 0 2 0 0 0 0 0 0 0 0 0 0 0 0]

Please help me on this. I am not able to fetch the destinations of each ipvs service.

**Comment by icefed** [comment]
I'm tracking this error too, it's a BUG from https://github.com/docker/libnetwork/pull/2416
