### ISSUE TITLE
Enhancement proposal for security group support and more powerful IP allocator 

### ISSUE THREAD

**Issue by WeiZhang555** [docker/libnetwork#248]
In my understanding, the overlay network driver will implement a cluster network which can span one subnet over multi-host, so have you considered to add some more advanced concepts like _Security Group_?
And also, we want to enhance the IP allocator, user can give an IP POOL fixed numbers of IP addresses, e.g. network "frontend" owns an IP pool which has three IPs--{ "192.168.1.1", "192.168.2.1", "172.17.0.1"}, when user call `docker run --net=frontend CONTAINER`, ip allocator will give one of three IPs to that container, after 3 IPs is run out, `docker run --net=frontend` will fail. And user can add/delete IP address to/from network with cmd like `docker network add 10.110.52.1 frontend`, will you consider to add concept like this?
Thank you!
ping @mrjana @mavenugo

**Comment by naotoy** [comment]
@WeiZhang555 Please tell us the use cases or advantages of enhancement you proposed. Is the container attached "frontend" endpoint or gateway like weave router?
# Sorry, I'm not your ping target.

**Comment by naotoy** [comment]
@WeiZhang555 Please tell us the use cases or advantages of enhancement you proposed. Is the container attached "frontend" endpoint or gateway like weave router?
Sorry, I'm not your ping target.

**Comment by WeiZhang555** [comment]
@naotoy Welcome more discussions, next time I'll remember to ping you :)
For *Security Group*, it's easy to understand, I think you will be familiar with this concept if you ever played around with OpenStack, with Security Group, we can restrict every container from visiting other endpoint or being visited from outside, it's a security enhancement which is very helpful.
The other one *IP Allocator* enhancement came from our one special senario, you can think of it like this: we want to give every container an internet IP address, but you know, we have only limited numbers of IPs, sometimes we need to revoke/add IPs from/to the IP pool but existing docker can only allocate IP from subnet dynamicly, that's why we need to enhance IP allocator.
Glad to discuss with you, thank you!

**Comment by spikecurtis** [comment]
@WeiZhang555 In your example there was 1 network and one 1 pool.  Can you elaborate on the desired relationship between IP pools and networks (which represent a boundary of connectivity).  Would you always want a 1-to-1 relationship between networks and pools?  Would it be desirable for a network to have more than one pool from which to allocate?  Would it be desirable for more than one network to allocate from a single pool (e.g. a pool of public IPs, but networks representing different applications requesting IPs from that pool).

**Comment by WeiZhang555** [comment]
@spikecurtis 
In my senario, it's always 1-to-1 relationship, every network has exactly one IP pool, we can let the network own whole subnet(e.g. 172.17.42.1/24), or we can manually give IP addresses to IP pool and network can only pick up IP from the manually generated pool.
Your idea of many-to-many relationship is also interesting, but it seems 1-to-1 is enough for us now.
Thank you :)

**Comment by aboch** [comment]
@WeiZhang555 We had similar thoughts about the ipallocator we imported from docker when developing libnetwork. Especially for the multi-host solution. For the single host case, we felt the original ipallocator was good enough. So we came up with some requirements and in March I worked to a new IPAM service. We also identified the "allow reserving a block of ip" requirement, where an IPAM node can then manage its local block of IP addresses.

I am getting back to the IPAM now and I will push it sometime next week so that people interested in this topic can help review/improve.

Thanks.

**Comment by WeiZhang555** [comment]
@aboch 
Very excited to hear that! So you are developing a standalone IPAM which runs as a service, right? If true, that's exactly what we want! Hope I can have chance to help improve,  I'm really interested in that! :p

So another question is do you have plans to integrate function like *Security Group* into libnetwork? 
And thank you for your answer! :)

**Comment by WeiZhang555** [comment]
Closing this. :smile:
