### ISSUE TITLE
libnetwork does not transfer network names to the remote plugin API

### ISSUE THREAD

**Issue by erikh** [docker/libnetwork#251]
The struct CreateNetworkRequest has no notion of the network name. We use this as a means to associate a friendly network name with the network. Network IDs are really an internal state tracking thing for us.

In conversations with @mrjana I was surprised to hear there's not any intent to provide this and was hoping we could have a discussion about why.

/cc @jainvipin @mapuri @shykes

**Comment by erikh** [comment]
I'm happy to provide the code with a little guidance, fwiw.

**Comment by shettyg** [comment]
fwiw, I have asked for the same here:
https://github.com/docker/libnetwork/issues/139

**Comment by erikh** [comment]
ok, I'll close this one and watch that one, then. Thanks!

**Comment by shettyg** [comment]
@erikh 
Please do post your thoughts on why it is a good idea to pass the name too in #139. I think with more compelling use cases, we may get this feature.
