### ISSUE TITLE
Migrate custom error struct to well-known error interfaces

### ISSUE THREAD

**Issue by aboch** [docker/libnetwork#269]
Replace the custom error types in bridge/errors.go with the well-known error interface formatters:
types.XXXErrorf(). Once the replace is done, delete bridge/error.go file.

For example:
where the type:
`type ErrInvalidNetworkConfig struct{}`
is returned, replace it with:
`types.BadRequestErrorf(...)`

**Comment by fcrisciani** [comment]
code is merged, closing it
