### ISSUE TITLE
Error when using a default gateway outside of the allocated range

### ISSUE THREAD

**Issue by eolamey** [docker/libnetwork#287]
When setting up a default gateway, libnetwork will verify that it belongs to the bridge network, but will also try to allocate it from the allocated range which, I think, is the `--fixed-cidr` flag from docker.

However, the default gateway may very will be outside of the allocated range, such as:

```
% docker -d --bip=172.16.0.10/16 --fixed-cidr=172.16.122.0/24 --default-gateway=172.16.0.1
```

Currently, this fails, although it should work.

I think this code, https://github.com/docker/libnetwork/blob/master/drivers/bridge/setup_ipv4.go#L112, should only be called if the default gateway belongs to the allocated range.

**Comment by aboch** [comment]
Thanks for reporting this.
I think I know where the issue is. Will propose a patch soon.

**Comment by eolamey** [comment]
Thank you for working on this. I'm sorry, but I can't comment on your solution as I really don't know how libnetwork works. I've tested a much cruder patch that removes the call to `ipAllocator.RequestIP`, it works but it's obviously not appropriate :)

Do you think there's any chance this could make it to docker 1.7.0? I've been waiting for the possibility to set `--default-gateway` for a long time, but can't use without a fix to this bug.

No pressure though, I get it if you consider this only affects one use case for `--default-gateway` and is not a blocker.

**Comment by kgutwin** [comment]
+1. This bug prevents `--default-gateway` from working in many important cases.
