### ISSUE TITLE
Missing UI/API fixes

### ISSUE THREAD

**Issue by mavenugo** [docker/libnetwork#292]
- `network` & `service` config save & retrieve
- `service attach` command must honor container-name
- `service` and `network` should support labels
- ~~Handling default network in services UI/API~~
- ~~Replace -net with SERVICE[.NETWORK]~~
- ~~A few more usability bugs~~

**Comment by mavenugo** [comment]
Handled the following via https://github.com/docker/libnetwork/pull/294

* Handling default network in services UI/API
* service attach command must honor container-name
* A few more usability bugs

**Comment by dave-tucker** [comment]
@mavenugo is this issue still being used for tracking or can we close it?

**Comment by aboch** [comment]
No longer needed
