### ISSUE TITLE
Hosts don't share networks even when backed by the same datastore.

### ISSUE THREAD

**Issue by spikecurtis** [docker/libnetwork#302]
I've set up two Docker daemons with libnetwork, backed by an etcd datastore (hardcoded in [my testing version](https://github.com/spikecurtis/docker/tree/etcd-datastore)).

Creating a network on one host does not result in the network being displayed on the second host `docker network ls`.  (I've verified network objects are being written to etcd.)

Creating a network on the second host with the same name as used by the first host results in a different network UUID.

Is the function to have libnetwork read the datastore for existing networks implemented?  Has it been tested on datastores other than etcd?

**Comment by mavenugo** [comment]
@spikecurtis can you try consul and confirm if this is a datastore specific or issue in libnetwork ?
(I have tested it using consul. fyi)

**Comment by spikecurtis** [comment]
CC @tomdee

**Comment by tomdee** [comment]
I tested with consul and hit the same problem.

**Comment by mavenugo** [comment]
@tomdee which driver are you guys checking this against ?

**Comment by spikecurtis** [comment]
@mavenugo Remote driver with our own Calico driver backing it.

I also tried creating a standard bridge-driver network, and it wasn't persisted across the hosts either.

**Comment by mavenugo** [comment]
@spikecurtis bridge-driver is a local driver and hence it wont use the datastore.
Can you share the `libnetwork.toml` that you use to pass the configuration to dnet ?

**Comment by spikecurtis** [comment]
@mavenugo I hardcoded config in Docker, since the goal was to do some system testing with Calico.

from `daemon_unix.go`

```
func initNetworkController(config *Config) (libnetwork.NetworkController, error) {

	// SpikeCurtis HACK:  force use of etcd datastore.
	controller, err := libnetwork.New(netconfig.OptionKVProvider("etcd"),
		                              netconfig.OptionKVProviderURL("127.0.0.1:2379"))
	if err != nil {
		return nil, fmt.Errorf("error obtaining controller instance: %v", err)
	}
```

**Comment by mavenugo** [comment]
@spikecurtis so you are building on top of #13441 ?

**Comment by spikecurtis** [comment]
@mavenugo Yeah, until something gets merged to master we can use.
