### ISSUE TITLE
Bug in vishvananda/netlink

### ISSUE THREAD

**Issue by LK4D4** [docker/libnetwork#321]
There is bug in vishvananda/netlink which prevents main veth device from setting `TxQLen` to zero. It is fixed in master, but also in master changed value of `msg.Change` for some calls, and therefore you will need to up main veth interface with additional call.
vishvananda/netlink#38

**Comment by dave-tucker** [comment]
@mrjana @LK4D4 can we close this issue?

**Comment by mrjana** [comment]
Yeah this is fixed already.
