### ISSUE TITLE
make the overlay network range configurable 

### ISSUE THREAD

**Issue by kelseyhightower** [docker/libnetwork#334]
Looks like the network range is hard coded for the overlay network driver. https://github.com/docker/libnetwork/blob/master/drivers/overlay/overlay.go#L50 

This should be configurable, I'm happy to work on a PR for this.

**Comment by mavenugo** [comment]
Thanks @kelseyhightower. Yes. We are moving to the new ipam. And that will remove the hard coded range. Pls look out for a PR shortly.

**Comment by kelseyhightower** [comment]
@mavenugo Awesome.

**Comment by aboch** [comment]
Closed by #525

**Comment by mavenugo** [comment]
@kelseyhightower fyi, overlay and all network drivers are migrated to use the new IPAM concept.
