### ISSUE TITLE
Network name is not unique across the cluster

### ISSUE THREAD

**Issue by spikecurtis** [docker/libnetwork#337]
The current Docker UI has the user refer to networks by name.  In order for that to work correctly, the name needs to be unique across the cluster.  Currently, libnetwork doesn't enforce this.

A quick example to show this is a problem: create two Docker containers on different hosts

On the first host
```
docker run --publish-service serviceA.net1.overlay ...
```

On the second host
```
docker run --publish-service serviceB.net1.overlay ...
```

The desired effect is for these services to be on the same network.  However, if the commands are executed simultaneously, or in rapid succession, each Docker Engine will think it should create `net1` with a new UUID.  So there will be two `net1` networks with one endpoint each, rather than what was desired.

Some ideas for fixing:

If, as @mrjana has said, we want network names and IDs to have different lifetimes, then libnetwork should store the names in the consistent data store (with the name itself as part of the key, e.g. `/docker/libnetwork/netname/net1`).  The name would be a "pointer" object that points to the UUID.  In the above example, both Docker Engines would attempt to create the name `net1`, but only one would succeed.  The unsuccessful one would then read back the name key to find out which network it currently points to and then attach the container to that network.

Another possibility would be to simply use the name as the unique ID for the network.  Simpler to implement, but it ties the lifetime together.

/cc @lxpollitt @tomdee @squaremo

**Comment by squaremo** [comment]
> The name would be a "pointer" object that points to the UUID.

That would work for preventing races to create the network name; but, is it possible to atomically rename a network in this scheme? (I don't know the capabilities of libkv and its underlying stores well enough to know)

**Comment by lxpollitt** [comment]
@squaremo One approach might be to map rename to a create followed by a delete. Prior to the delete both old and new name would map to the same UUID.  (And you can build on that with things like generation numbers etc if you want to get more advanced and know which name to delete should you crash mid-way through the rename operation.)

**Comment by spikecurtis** [comment]
I think it's important to square away the UI before deciding how to implement renames.  In particular, can a network have more than one name at any given time?  

If yes, then I think renames are trivial in this model, as @lxpollitt suggested.

If each network can have only one name at a time, then the we can use a back "pointer" on the network object to ensure atomic renames.

**Comment by tomdee** [comment]
@mrjana  @mavenugo @aboch I think this issue is important for a first stable multi-host release of libnetwork. Could it get triaged and assigned to a milestone?

**Comment by bpradipt** [comment]
Is this still a problem, given that we store the network name and id in a central kv store ?

**Comment by spikecurtis** [comment]
I think this is still a problem.  Networks are keyed by ID in the data store, so the race condition described in the issue still exists.

**Comment by mrjana** [comment]
@bpradipt @spikecurtis It is not a problem anymore because before docker 1.9 release we have made names to be non-unique references/aliases to network which is uniquely identified using it's id only. In fact the network api allows you to create as many networks as you like with the same name. If you need unique names the user has to make sure of it external to docker either manually or using an external orchestrator. 

Now the api has a `CheckDuplicate` flag which will try to check for already existing networks with the same name in a best effort manner. But it is exactly that, best effort.

With this knowledge I am going to close this issue since it's not a problem anymore. Feel free to continue the discussion here.

**Comment by lxpollitt** [comment]
I know that Docker advocates strongly for the developer UX being of primary importance.  Can you help me understand how this fits with that philosophy?  I'm not saying it doesn't, but it would be very helpful to those of us outside the tent to better understand the thinking behind this.
