### ISSUE TITLE
unable to delete network after deletion of containers. / no command to delete/detach endpoint

### ISSUE THREAD

**Issue by kunalkushwaha** [docker/libnetwork#347]
This bug I faced with experimental build 1.8.0-dev.
- - - - 
I created a container with publishing a service ``myapp`` and network ``mydomain``.
After that I killed the container and tried to delete the network mydomain.

But I am not able to delete network, since an active endpoint is attached to it.

How to delete or detach the network with endpoint?
I think some command is not exposed to UI.

Below is details of docker and commands I executed.
 
```
 ✘  kunal@kunal-XPS-L421X  ~  docker run -it --publish-service=myapp.mydomain ubuntu /bin/bash
root@4a911191e3dd:/# exit
exit
 ✘  kunal@kunal-XPS-L421X  ~  docker network ls
NETWORK ID          NAME                TYPE
ac4b44804a92        none                null                
2549d95b995a        host                host                
93cb96a431e8        bridge              bridge              
d7f5fbc88156        mydomain          bridge  

docker network rm overlay
Error response from daemon: network with name mydomain id d7f5fbc88156cdedfc38b5d2531fd5b6ab6b0778f64edddfd10445fd48731f55 has active endpoints

 kunal@kunal-XPS-L421X  ~  docker rm 4a911191e3dd
4a911191e3dd

 kunal@kunal-XPS-L421X  ~  docker network rm mydomain
Error response from daemon: network with name mydomain id d7f5fbc88156cdedfc38b5d2531fd5b6ab6b0778f64edddfd10445fd48731f55 has active endpoints

 kunal@kunal-XPS-L421X  ~  docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
 
 ✘  kunal@kunal-XPS-L421X  ~  docker version
Client version: 1.8.0-dev
Client API version: 1.20
Go version (client): go1.4.2
Git commit (client): f39b9a0
OS/Arch (client): linux/amd64
Experimental (client): true
Server version: 1.8.0-dev
Server API version: 1.20
Go version (server): go1.4.2
Git commit (server): f39b9a0
OS/Arch (server): linux/amd64
Experimental (server): true

```

**Comment by mavenugo** [comment]
@kunalkushwaha when you run a container with `--publish-service` option, the service that you publish `myapp` remains as part of `mydomain` even after the container is gone. This is because one could attach another container behind the same service which will inherit all the service properties.
If you are done using the service, use the command `docker service unpublish myapp.mydomain` to unpublish the service and then you should be able to `docker network rm mydomain`.

**Comment by kunalkushwaha** [comment]
thanks @mavenugo , It fixes the issue :)

**Comment by kunalkushwaha** [comment]
Closing it too.
