### ISSUE TITLE
docker run should support multiple --publish-service options

### ISSUE THREAD

**Issue by miketonks** [docker/libnetwork#362]
Command: docker run -d --name es1 -p 9200:9200 -p 9300:9300 --publish-service=es1.bridge --publish-service=es1.cluster elasticsearch

the es1.bridge is not connected - would be nice if multiple services supported - is this intended?

docker ps
CONTAINER ID        IMAGE               COMMAND                CREATED             STATUS              PORTS                                            NAMES
a99c7ad9ec70        elasticsearch       "/docker-entrypoint.   2 seconds ago       Up 2 seconds        0.0.0.0:9200->9200/tcp, 0.0.0.0:9300->9300/tcp   es1 

docker service ls
SERVICE ID          NAME                NETWORK             CONTAINER
e6f5fcb9f2d9        es1                 cluster             a99c7ad9ec70

Additionally, I cannot connect to the server on the host:

curl http://localhost:9200 never returns, but if I enter the container and run the same command, it is alive and well.

Intention here is to create three elasticsearch servers in a cluster across 3 separate hosts.  Overview network 'cluster' will be used to connect the three nodes for clustering, and requires that we can configure the es server for automatic discovery.  Ideally this uses the eth0 network (default) otherwise we need to pass additional configuration.

docker -v
Docker version 1.8.0-dev, build f39b9a0, experimental

uname -a
Linux es1 3.19.0-18-generic #18~14.04.1-Ubuntu SMP Wed May 20 09:38:33 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by dave-tucker** [comment]
Hi @miketonks, thanks for raising this issue. As there is no UI in libnetwork, any UI issues should reside in docker/docker - so I'm going to close this one for now
