### ISSUE TITLE
Network I/O stats all zero / GlobalIPv6Address not set

### ISSUE THREAD

**Issue by BenHall** [docker/libnetwork#368]
Hello,

When using the /stats endpoint all the network stats are zero, the other stats return the expected results. There has been network traffic working with the container.

Any suggestions on what to try next?  Below is my debugging / output so far.

Thanks

Ben

======

Stats output

```
$ curl localhost/containers/414ne0_d2d/stats?stream=false
"network":{"rx_bytes":0,"rx_packets":0,"rx_errors":0,"rx_dropped":0,"tx_bytes":0,"tx_packets":0,"tx_errors":0,"tx_dropped":0},
```

Here are the network settings for the said container.

```
    "NetworkSettings": {
        "Bridge": "",
        "EndpointID": "4b1cd925b020c9f36237895ea233516b53ed58d8766840ccea67840cf42a4ceb",
        "Gateway": "172.17.42.1",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "HairpinMode": false,
        "IPAddress": "172.17.0.174",
        "IPPrefixLen": 16,
        "IPv6Gateway": "",
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "MacAddress": "02:42:ac:11:00:ae",
        "NetworkID": "47023aeadd22b0bead2073edbdd1811d34d8dfab2ddd409c2ba1ad039bba6a85",
        "PortMapping": null,
        "SandboxKey": "/var/run/docker/netns/87a43adf5425",
        "SecondaryIPAddresses": null,
        "SecondaryIPv6Addresses": null
    },
```

Attempting to output the netns file returns nothing.

```
$ cat /var/run/docker/netns/87a43adf5425
```

The results for ifconfig are all in inet6 with not iPv4 addresses so I'm unable to relate them back to the container, not sure why GlobalIPv6Address hasn't been set. Is this the reason?

```
$ ifconfig
vethd35519b Link encap:Ethernet  HWaddr f6:bf:bf:be:b1:ea
          inet6 addr: fe80::f4bf:bfff:febe:b1ea/64 Scope:Link
          UP BROADCAST RUNNING  MTU:1500  Metric:1
          RX packets:2061 errors:0 dropped:0 overruns:0 frame:0
          TX packets:2581 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:186088 (186.0 KB)  TX bytes:11125879 (11.1 MB)
```

The ethtool doesn't return any of the expected stats either.  It works for eth0

```
$ ethtool -i vethd35519b
driver: veth
version: 1.0
firmware-version:
bus-info:
supports-statistics: yes
supports-test: no
supports-eeprom-access: no
supports-register-dump: no
supports-priv-flags: no

$ ethtool -S vethd35519b
NIC statistics:
     peer_ifindex: 345
```

Environment details:
```
$ docker version
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): linux/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64
```

```
$ docker info
Containers: 1389
Images: 269
Storage Driver: aufs
 Root Dir: /home/docker/data/aufs
 Backing Filesystem: extfs
 Dirs: 3047
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-18-generic
Operating System: Ubuntu 15.04
CPUs: 8
Total Memory: 94.41 GiB
Registry: https://index.docker.io/v1/
```

**Comment by aboch** [comment]
@BenHall This is a known issue. The fix will be in 1.7.1
#14324

**Comment by BenHall** [comment]
That's great! Thank you.

**Comment by thaJeztah** [comment]
For reference, that PR is in the docker repository, not this repo; https://github.com/docker/docker/pull/14324

**Comment by thaJeztah** [comment]
@BenHall if you want to test if this issue is resolved for you, the current release candidates for docker 1.7.1 can be found here; https://github.com/docker/docker/pull/14264#issuecomment-119692197 (and RPMs here: https://github.com/docker/docker/pull/14264#issuecomment-119747020).

There will be an 1.7.1-rc3, so you might want to keep an eye on that PR, and the release is scheduled for next Tuesday

**Comment by dave-tucker** [comment]
Closing as docker 1.7.1 has been [released](https://github.com/docker/docker/releases/tag/v1.7.1)
If you still find that this issue is persisting, please drop us a note and we can re-open this issue!
