### ISSUE TITLE
Experimental Release: Unable to start docker daemon

### ISSUE THREAD

**Issue by dsampath** [docker/libnetwork#370]
I keep getting this error when I try starting the Daemon as per the instructions: 
```
FATA[0000] Error starting daemon: Error initializing network controller: error obtaining controller instance: failed to initialize vxlan id manager: failed to initialize bit sequence handler: Key not found in store
```

Am I missing something here? or is something broken on this nightly?

---

##### Here is the more complete description of the setup/output: 
1. Two virtualbox vms with 2 network interfaces (NAT, Host-only).
2. Consul setup is up and running on the host.
3. Docker experimental release build *2fe51ec* on each one. 
4. Ubuntu version 15.04 with Kernel Version >=3.16 (3.19)

```
ubuntu@ubuntu2:~$ consul members
Node     Address              Status  Type    Build  Protocol  DC
ubuntu2  192.168.59.106:8301  alive   client  0.5.2  2         dc1
ubuntu1  192.168.59.107:8301  alive   server  0.5.2  2         dc1
```

```
ubuntu@ubuntu2:~$ docker -v
Docker version 1.8.0-dev, build 2fe51ec, experimental
```

```
ubuntu@ubuntu2:~$ docker info
Containers: 1
Images: 2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 4
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-15-generic
Operating System: Ubuntu 15.04
CPUs: 1
Total Memory: 993.1 MiB
Name: ubuntu2
ID: L7KO:XHJP:5CMA:MC2W:FITF:GO7S:EKIM:UJPX:DIS6:RYN7:PVGS:OGYD
WARNING: No swap limit support
Experimental: true
```

```
ubuntu@ubuntu2:~$ uname -a
Linux ubuntu2 3.19.0-15-generic #15-Ubuntu SMP Thu Apr 16 23:32:37 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

```
ubuntu@ubuntu2:~$ sudo docker -d --kv-store=consul:localhost:8500 --label=com.docker.network.driver.overlay.bind_interface=eth1
WARN[0000] Running experimental build
INFO[0000] [graphdriver] using prior storage driver "aufs"
INFO[0000] Option DefaultDriver: bridge
INFO[0000] Option DefaultNetwork: bridge
INFO[0000] Option OptionKVProvider: consul
INFO[0000] Option OptionKVProviderURL: localhost:8500
INFO[0000] Listening for HTTP on unix (/var/run/docker.sock)
INFO[0000] Firewalld running: false
FATA[0000] Error starting daemon: Error initializing network controller: error obtaining controller instance: failed to initialize vxlan id manager: failed to initialize bit sequence handler: Key not found in store
```

**Comment by dsampath** [comment]
Ah - I don't see this when i build my own experimental binary though. I think the nightly is broken.

**Comment by mavenugo** [comment]
@dsampath we recently resolved this issue via https://github.com/docker/docker/pull/14402. I hope the experimental build will catch up to this fix soon.

**Comment by mavenugo** [comment]
@dsampath will close this issue based on the above information.

**Comment by jsindy** [comment]
I am seeing this again with latest.

**Comment by mavenugo** [comment]
@jsindy can you get the output for `docker version` ?

**Comment by jsindy** [comment]
Docker version 1.8.0-dev, build bfccd32, experimental

Looks like it might be an issue with 14.04? I have 3.19 kernel installed though.

**Comment by mavenugo** [comment]
@jsindy thanks for the confirmation. It seems you are using the latest and it is expected to work (even in 14.04 with an upgraded kernel as yours). 
ping @aboch

**Comment by jsindy** [comment]
The Vagrantfile is working which is what I need for testing anyways. Thanks!
