### ISSUE TITLE
Container fails to start after power outage

### ISSUE THREAD

**Issue by ricardobranco777** [docker/libnetwork#373]
Error response from daemon: Cannot restart container test1: invalid endpoint id: 27b2e9df4727b31dd216380ef32ffcaa1d71dec38e9e1be84f6861162f4e113a
# docker version

Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): linux/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64
# docker info

Containers: 2
Images: 266
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 270
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.16.0-0.bpo.4-amd64
Operating System: Debian GNU/Linux 7 (wheezy)
CPUs: 8
Total Memory: 15.38 GiB
Name: ems
ID: ASN5:NCXF:4CUK:WBZD:A7TY:O4FF:EFVP:VWHH:YH52:6UHW:FUSI:IOXD

**Comment by ricardobranco777** [comment]
I reproduced this bug again, and "docker start" succeeded at the 3rd attempt.

**Comment by bpradipt** [comment]
Is this still a problem with latest version ?

**Comment by ricardobranco777** [comment]
I haven't been able to reproduce it using Virtualbox.  Anyway, any status information on /var/lib/docker should be fsync'ed to avoid these issues.
