### ISSUE TITLE
createNetwork and createEndpoint' option can not be dynamically assigned

### ISSUE THREAD

**Issue by linzichang** [docker/libnetwork#374]
Using docker client or libnetwork client, network option can only be assigned by `label`. `label`s are given by some docker daemon flag such as `--label`.

The cmd `docker network create -d` don't provide a flag like `--options`. This make the network inflexible. I expect the networks are more flexible when using a remote driver.

**Comment by dave-tucker** [comment]
Hi @linzichang - this will be addressed by #222 and we have https://github.com/docker/libnetwork/issues/386 open to track this - we're hoping it will be ready in the next release!
