### ISSUE TITLE
Provide an embedded datastore for libnetwork and the overlay driver

### ISSUE THREAD

**Issue by dave-tucker** [docker/libnetwork#376]

**Comment by tomdee** [comment]
@dave-tucker Could you elaborate a little more on what this means? Is this an alternative to libkv? Is it something that remote drivers can use? Is it single host only or can it work multihost?

**Comment by mrjana** [comment]
@tomdee This is not an alternative to libkv. This will still use libkv apis. Just that we want to provide a way for the user to not setup backend data stores themselves. If they didn't provide a backend data store option (but provide a simpler option to signify a cluster of docker hosts) then they should still be able to form networks. So in essence this is something everybody can use(both the in-tree drivers and remote drivers as well as libnetwork itself) and it will work for multi-host configurations
