### ISSUE TITLE
Provide docs for the networking UI

### ISSUE THREAD

**Issue by dave-tucker** [docker/libnetwork#389]

**Comment by tomdee** [comment]
Do you mean the networking UI documented here? https://github.com/docker/docker/issues/14593

If so, isn't that making it into Docker 1.8? And therefore this should be milestone 0.4?

**Comment by mrjana** [comment]
@tomdee We do have a 0.4 milestone for libnetwork. But when you say this will make it into Docker 1.8 are you referring to 1.8 stable master in docker/docker. If so no, all of these UI will remain in experimental during 1.8 release and remember experimental is built nightly so it's not very meaningful of talking about any of the experimental features in terms of a docker/docker release version
