### ISSUE TITLE
/etc/hosts not modified on container attach

### ISSUE THREAD

**Issue by mbdas** [docker/libnetwork#393]
when using docker run with --publish-service, the /etc/hosts get modified to have the entries for all other containers in that network, thus making discovery possible over dns

However, when spinning up the container separately and then attaching the container to the service through docker service attach $cid x.y , the /etc/hosts do not get modified with other containers in the network.

Is this a bug or expected behavior?

**Comment by botchagalupe** [comment]
I was told this is a bug.  Check out 
https://github.com/docker/libnetwork/issues/359

**Comment by dave-tucker** [comment]
Closing this in favour of #359
