### ISSUE TITLE
Could not add vxlan interface inside the network sandbox

### ISSUE THREAD

**Issue by mbruzek** [docker/libnetwork#394]
Hello libntwork people!

I am trying to follow the Detailed setup on the [overlay network instructions](https://github.com/docker/libnetwork/blob/master/docs/overlay.md#detailed-setup).

Environment:
I have 2 KVM virtual machines, host-a and host-b.  Both are installed with Ubuntu 14.04.2 LTS with kernel: `Linux mbruzek-kvm-machine-3 3.13.0-55-generic #94-Ubuntu SMP Thu Jun 18 00:27:10 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`

Both hosts have docker 1.8.0-dev (experimental) installed.
```
# docker version
Client:
 Version:      1.8.0-dev
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   15f9766
 Built:        Mon Jul 13 21:26:03 UTC 2015
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.8.0-dev
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   15f9766
 Built:        Mon Jul 13 21:26:03 UTC 2015
 OS/Arch:      linux/amd64
 Experimental: true
```
I am attempting to attach the process to a service and I get the following error: 
```
# docker service attach $cid host-b-0.juju 
Error response from daemon: network sandbox join failed: could not add vxlan interface inside the network sandbox: failed in prefunc: failed to set namespace on link "vxlan2fcf912": invalid argument

root@mbruzek-kvm-machine-3:/home/ubuntu# docker network ls
NETWORK ID          NAME                TYPE
37271c5f6421        host                host                
1de71aba6592        bridge              bridge              
d27279d6eb59        juju                overlay             
54fcd3865787        none                null                
root@mbruzek-kvm-machine-3:/home/ubuntu# docker service ls
SERVICE ID          NAME                NETWORK             CONTAINER
20972e3e2cfa        nostalgic_bell      bridge              103d0d0eca1a
7314c09fe81e        host-a-0            juju                
1d13efd99ca5        host-b-0            juju 
root@mbruzek-kvm-machine-3:/home/ubuntu# docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS                    NAMES
103d0d0eca1a        ubuntu              "/bin/bash"         8 minutes ago       Up 8 minutes        0.0.0.0:8000->8000/tcp   nostalgic_bell
```

It looks to me like there is an error with the vxlan interface, and the nostalgic_bell container was attached to the bridge network by default.  

Please advise if I did something wrong, or if you know how to fix this.  Thank you!

**Comment by dave-tucker** [comment]
Hi @mbruzek, thanks for the bug report. We're already aware of this issue and we are tracking it  on https://github.com/docker/libnetwork/issues/329 - please subscribe to that issue to get notified when it's fixed. In the mean time, you might want to either upgrade your kernel to 3.16 or use a later version of ubuntu
