### ISSUE TITLE
Libnetwork can't handle long network names

### ISSUE THREAD

**Issue by tomdee** [docker/libnetwork#402]
If I run a container with a long network name - 

```
docker run --tty --interactive --detach --name workload2 --publish-service=a5accd88-869e-4149-8031-87af7c20318a.966204b315e55324148888e3808f6b4bf079a15f572142a69d4dab745bac7783 busybox

```

Container start fails with the following message

```
Error response from daemon: Cannot start container 11e8089573d188399487b1b490c1a786260dbd7cb33ec3b7817ea87528935b3f: Interface name 966204b315e55324148888e3808f6b4bf079a15f572142a69d4dab745bac7783 too long
```

Why is there this limit on the length of the network name and what does it have to do with interface names? I asked for a network not an interface!

I would be nice to have this restriction lifted but failing that it should at least be documented.

**Comment by bpradipt** [comment]
I think this should be closed now. The UX has changed. publish-service is no longer available (Ref: https://github.com/docker/docker/pull/16645) 
Also, current implementation is able to create network with long network names as given in the above example
# docker -H tcp://192.168.122.2:2376 network create --driver overlay --subnet=10.0.9.0/24 a5accd88-869e-4149-8031-87af7c20318a.966204b315e55324148888e3808f6b4bf079a15f572142a69d4dab745bac7783
e263a5b7e09e9e31f426cd13659bf07fae485d4f83322b824311f7447e3967bf
# docker -H tcp://192.168.122.2:2376 network ls
NETWORK ID          NAME                                                                                                    DRIVER
ef5c544f493b        bridge                                                                                                  bridge              
b8a13e791735        none                                                                                                    null                
88f0db67c08c        host                                                                                                    host                
74195bb74274        my-net                                                                                                  overlay             
e263a5b7e09e        a5accd88-869e-4149-8031-87af7c20318a.966204b315e55324148888e3808f6b4bf079a15f572142a69d4dab745bac7783   overlay
