### ISSUE TITLE
docker inspect not reporting correct MAC address

### ISSUE THREAD

**Issue by tomdee** [docker/libnetwork#406]
I created a container with `docker run -tid --publish-service=service5.prod.calico busybox`

When I run docker inspect, I can see that most of the `NetworkSettings` are populated but the MacAddress isn't. Can anyone else reproduce this problem or is it just me? I see this problem with the overlay driver and my remote driver (calico) but not on the bridge driver.

Inspect output is below

```
docker inspect boring_newton
[
{
    "Id": "e991512c9e33c8c2151e1bb40f11f05d3df5f5ab33c4663924ad788006a9495b",
    "Created": "2015-07-21T16:44:17.143703918Z",
    "Path": "/bin/sh",
    "Args": [],
    "State": {
        "Running": true,
        "Paused": false,
        "Restarting": false,
        "OOMKilled": false,
        "Dead": false,
        "Pid": 14685,
        "ExitCode": 0,
        "Error": "",
        "StartedAt": "2015-07-21T16:44:17.594565389Z",
        "FinishedAt": "0001-01-01T00:00:00Z"
    },
    "Image": "8c2e06607696bd4afb3d03b687e361cc43cf8ec1a4a725bc96e39f05ba97dd55",
    "NetworkSettings": {
        "Bridge": "",
        "EndpointID": "a2dc14eb484c6dc6f29c7e6488edf5a639259857f32e3ca72366a950f626f6cf",
        "Gateway": "10.0.2.15",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "HairpinMode": false,
        "IPAddress": "192.168.0.6",
        "IPPrefixLen": 32,
        "IPv6Gateway": "",
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "MacAddress": "",
        "NetworkID": "b35a41ef11c698e2972abc2ec029b6872d078eba70e5af01a9986a83e109b989",
        "PortMapping": null,
        "Ports": {},
        "SandboxKey": "/var/run/docker/netns/e991512c9e33",
        "SecondaryIPAddresses": null,
        "SecondaryIPv6Addresses": null
    },
    "ResolvConfPath": "/var/lib/docker/containers/e991512c9e33c8c2151e1bb40f11f05d3df5f5ab33c4663924ad788006a9495b/resolv.conf",
    "HostnamePath": "/var/lib/docker/containers/e991512c9e33c8c2151e1bb40f11f05d3df5f5ab33c4663924ad788006a9495b/hostname",
    "HostsPath": "/var/lib/docker/containers/e991512c9e33c8c2151e1bb40f11f05d3df5f5ab33c4663924ad788006a9495b/hosts",
    "LogPath": "/var/lib/docker/containers/e991512c9e33c8c2151e1bb40f11f05d3df5f5ab33c4663924ad788006a9495b/e991512c9e33c8c2151e1bb40f11f05d3df5f5ab33c4663924ad788006a9495b-json.log",
    "Name": "/boring_newton",
    "RestartCount": 0,
    "Driver": "aufs",
    "ExecDriver": "native-0.2",
    "MountLabel": "",
    "ProcessLabel": "",
    "Volumes": {},
    "VolumesRW": {},
    "AppArmorProfile": "",
    "ExecIDs": null,
    "HostConfig": {
        "Binds": null,
        "ContainerIDFile": "",
        "LxcConf": [],
        "Memory": 0,
        "MemorySwap": 0,
        "CpuShares": 0,
        "CpuPeriod": 0,
        "CpusetCpus": "",
        "CpusetMems": "",
        "CpuQuota": 0,
        "BlkioWeight": 0,
        "OomKillDisable": false,
        "Privileged": false,
        "PortBindings": {},
        "Links": null,
        "PublishAllPorts": false,
        "Dns": null,
        "DnsSearch": null,
        "ExtraHosts": null,
        "VolumesFrom": null,
        "Devices": [],
        "NetworkMode": "default",
        "IpcMode": "",
        "PidMode": "",
        "UTSMode": "",
        "CapAdd": null,
        "CapDrop": null,
        "RestartPolicy": {
            "Name": "no",
            "MaximumRetryCount": 0
        },
        "SecurityOpt": null,
        "ReadonlyRootfs": false,
        "Ulimits": null,
        "LogConfig": {
            "Type": "json-file",
            "Config": {}
        },
        "CgroupParent": ""
    },
    "GraphDriver": {
        "Name": "aufs",
        "Data": null
    },
    "Config": {
        "Hostname": "e991512c9e33",
        "Domainname": "",
        "User": "",
        "AttachStdin": false,
        "AttachStdout": false,
        "AttachStderr": false,
        "ExposedPorts": null,
        "PublishService": "service5.prod.calico",
        "Tty": true,
        "OpenStdin": true,
        "StdinOnce": false,
        "Env": null,
        "Cmd": [
            "/bin/sh"
        ],
        "Image": "busybox",
        "Volumes": null,
        "VolumeDriver": "",
        "WorkingDir": "",
        "Entrypoint": null,
        "NetworkDisabled": false,
        "MacAddress": "",
        "OnBuild": null,
        "Labels": {}
    }
}
]
```

**Comment by mbanikazemi** [comment]
#dibs

**Comment by mbanikazemi** [comment]
I think there is a need to define the keys for some of the iinformation returned from a network plugin as part of the endpointOperInfo such that they can be processed by docker. In the patch I just pushed I use MacAddress as the key for the MAC address information as I think it is what is used by the bridge driver. So for the MAC address to show up with docker inspect, the plugin needs to return the information with that key. If this is the correct approach, I can update the Overlay driver as well.

**Comment by tomdee** [comment]
Does it need to be added to the endpointOperInfo? The response to the createEndpoint request already includes the MAC address.

**Comment by mbanikazemi** [comment]
@tomdee No, but the question is essentially what keys are to be used (for both receiving parameters by the plugin or returning information back to docker/libnetwork) and how to make sure these are well defined so plugins can be developed more easily.

@mavenugo @dave-tucker @aboch  I have looked into how best to specify the keys that network plugins can expect to get in the incoming requests and what they need to use to pass the information to libnetwork. 

I think we want to have all the keys defined in a single place where the plugins can possibly directly use (at least when the plugin is written in go) or can be easily referenced while the plugin is being developed in other languages.

There are a couple of options I can think of:

1- Define and use the labels as specified in libnetwork/netlabel/labels.go
There are a couple of issues that make this less than desirable. There are keys being passed to network plugins that are not defined here. They are essentially obtained while the data structures defined in libnetwork/drivers/remote/api/api.go are marshaled. We either need to expand the net labels to include them or have the information needed by plugins in more than one place.
 
The other issue with this approach is that we will need to explicitly use these labels as the json encoding of fields specified in libnetwork/drivers/remote/api/api.go. This is certainly doable, but I believe by using encoding/json we have to explicitly specify these keys as strings (and not as reference to the exiting net label strings) as in for example

MacAddress  net.HardwareAddr `json:com.docker.network.endpoint.macaddress`

This means we have to hardcode these labels in two places, once as part of the netlabels and once in the api.go.

2- Use the libnetwork/drivers/remote/api/api.go as the single place where network plugins get these keys and possibly explicitly specify them through statements like:

MacAddress  net.HardwareAddr `json:macAddress`

and provide a function in the remote driver to parse/convert these keys to netlabel labels.
There is a small number of labels that need conversion and this can be done by a new function parseEndpointOperInfoResult which will be similar to what the bridge network functions parseEndpointOptions and parseContainerOptions are.

This approach requires updating this function when new labels are defined in netlabel. One can do this in a somewhat generic way for certain labels however, we still need to update the conversion function or table when new labels are added. However, for developing a network plugin one needs to only use/know the api package.

I think the second option is cleaner. What do you think? Are there better ways of doing this that you can think of?

Please let me know what you think and I will update the patch accordingly.

**Comment by fcrisciani** [comment]
tried on master and looks like the mac is returned:
```
[...]
"NetworkSettings": {                                        
            "Bridge": "",                                           
            "SandboxID": "d527c3afde3c9a29629e4028f397e04b24dbb60319c475da677c4295ea0850c6",                                            
            "HairpinMode": false,                                   
            "LinkLocalIPv6Address": "",                             
            "LinkLocalIPv6PrefixLen": 0,                            
            "Ports": {},                                            
            "SandboxKey": "/var/run/docker/netns/d527c3afde3c",     
            "SecondaryIPAddresses": null,                           
            "SecondaryIPv6Addresses": null,                         
            "EndpointID": "",                                       
            "Gateway": "",                                          
            "GlobalIPv6Address": "",                                
            "GlobalIPv6PrefixLen": 0,                               
            "IPAddress": "",                                        
            "IPPrefixLen": 0,                                       
            "IPv6Gateway": "",                                      
            "MacAddress": "",                                       
            "Networks": {                                           
                "net2": {                                           
                    "IPAMConfig": {                                 
                        "IPv4Address": "10.0.1.2"                   
                    },                                              
                    "Links": null,                                  
                    "Aliases": [                                    
                        "d5464ea1cd19"                              
                    ],                                              
                    "NetworkID": "rqfrlaafewitn2vttqfmqpn3s",       
                    "EndpointID": "32a53d8b389719fa6958b139cf151f1fe956f9a7dd4859f433f5f73eb7a30bfb",                                   
                    "Gateway": "",                                  
                    "IPAddress": "10.0.1.2",                        
                    "IPPrefixLen": 24,                              
                    "IPv6Gateway": "",                              
                    "GlobalIPv6Address": "",                        
                    "GlobalIPv6PrefixLen": 0,                       
                    "MacAddress": "02:42:0a:00:01:02",              
                    "DriverOpts": null                              
                }                                                   
            }                                                       
        }                                                           
    }                
```
