### ISSUE TITLE
Restarting the KV store causes Docker Daemons to peg the CPU to 100%

### ISSUE THREAD

**Issue by alvinr** [docker/libnetwork#408]
# Problem
Using the new networking, if I restart the KV store (consul in this case) causes the Docker daemon process to peg the CPU to 100%. See attached graph of CPU usage on an EC2 instance.

![screen shot 2015-07-22 at 11 07 49 am](https://cloud.githubusercontent.com/assets/336450/8833221/9cf4be2c-3062-11e5-858a-539f09808a02.png)

With `htop` you can see the Docker process taking 100% of the one core. I have seen this issue on EC2 (Ubuntu), VMWare Fusion (boot2docker) and VirtualBox (boo2docker)

# Reproduce

Start a new machine with daemon and run the container with consul
`$ docker-machine create swarm-consul`
`$ docker run -d -p 8400:8400 -p 8500:8500 -p 8600:53/udp -h swarm-consul --name swarm-consul progrium/consul -server -bootstrap`

Start a second machine with daemon
`$ docker-machine create foo`

Ensure you have configured the networking on the Daemon
`--default-network=overlay:multihost --label=com.docker.network.driver.overlay.bind_interface=eth0`

Restart consul machine
`$ docker-machine restart swarm-consul`

# Workaround
* Restart the docker daemon e.g. `sudo service docker stop; sudo service docker start`
* Reboot the machine the docker daemon is running on

# Environment
```
uname -a
Linux swarm-0 3.16.0-43-generic #58~14.04.1-Ubuntu SMP Mon Jun 22 10:21:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

```
docker version
Client:
 Version:      1.8.0-dev
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   8c7cd78
 Built:        Tue Jul 14 23:47:18 UTC 2015
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.8.0-dev
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   8c7cd78
 Built:        Tue Jul 14 23:47:18 UTC 2015
 OS/Arch:      linux/amd64
 Experimental: true
```

```
docker info
Containers: 6
Images: 43
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 55
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.16.0-43-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 2
Total Memory: 7.304 GiB
Name: swarm-0
ID: LO2F:EV7S:H25G:5RSQ:QISR:WIG6:AP25:VMGR:RBA3:IXJN:2HR5:6DKJ
Debug mode (server): true
File Descriptors: 24
Goroutines: 56
System Time: 2015-07-22T18:09:45.419817568Z
EventsListeners: 0
Init SHA1: 
Init Path: /usr/bin/docker
Docker Root Dir: /var/lib/docker
WARNING: No swap limit support
Labels:
 provider=amazonec2
 com.docker.network.driver.overlay.bind_interface=eth0
Experimental: true
```

**Comment by alvinr** [comment]
I'm looking at getting pprof (or similar) traces of where the CPU time is being spent.

**Comment by erikh** [comment]
I’m pretty sure the offender is a busy loop here: https://github.com/docker/libkv/blob/master/store/consul/consul.go#L303 <https://github.com/docker/libkv/blob/master/store/consul/consul.go#L303>

**Comment by abronan** [comment]
I don't think this is related to the call `WatchTree` because on Consul shutdown, `List` will fail, return an error thus closing the goroutine and the watch channel. The busy looping might be in `libnetwork` somewhere where it retries the `WatchTree` indefinitely on store failure. In Swarm, we wait for some time on `Watch` failure after retrying ([here](https://github.com/docker/swarm/blob/master/cli/manage.go#L134) is an example with the Leader Election process).

I'm not super familiar with the `libnetwork` codebase but I'll take a look at it and see if I can fix.

**Comment by gauravphoenix** [comment]
I'm hitting very same issue. Here is my docker info - 

```
Containers: 45
Images: 2
Engine Version: 1.9.0-dev
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 92
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
CPUs: 1
Total Memory: 1.665 GiB
Name: dockerhost2
ID: WEUP:VVZR:BUV6:YSLG:6MM2:2QZI:GBFA:YYLQ:CN4X:DG6R:LDAM:WJO3
WARNING: No memory limit support
WARNING: No swap limit support
Labels:
 com.docker.network.driver.overlay.bind_interface=eth0
 com.docker.network.driver.overlay.neighbor_ip=10.240.27.97
Experimental: true
```

**Comment by mavenugo** [comment]
@gauravphoenix this will be addressed soon. @mrjana is working on a fix to remove WatchTree and that should help.

**Comment by abronan** [comment]
@mavenugo We can close this one, just tested and works great when restarting the store.

**Comment by mavenugo** [comment]
:+1: thanks @abronan  that feels good :)
