### ISSUE TITLE
Q: container static ip address and classless interdomain routing

### ISSUE THREAD

**Issue by mauri** [docker/libnetwork#427]
Hi, I have patched docker 1.6 to support routed networks which allows to assign static ip addresses to containers, completely bypassing the bridge and portmapping thing, allowing containers to communicate transparently inside a datacenter.
I want to migrate it to use the abstractions introduced in 1.7 as a network driver, and get some feedback about the use case. Description of how it works below :)

So, an ip address can be specified for a container using a label. The default bridge is disregarded, instead only layer3 routing is involved. Basically I added a new ‘routed’ strategy that does the following:

1- create veth pair, e.g. veth1 and veth2)
2- add veth2 to container netns
3- set the ip-address/32 to veth2 (notice this is a /32 ip-address specified using a label)
4- rename container veth2 to eth0 
5- add default route in container: default dev eth0
6- add route in host: ip-address/32 dev veth1 

The routes to each container, present in the host, should be propagated between hosts using any interior gateway protocol, we currently use the Quagga’s OSPF implementation. The route propagation is quite fast, less than a second for 30k routes, and the performance is similar to host-to-host communication.

We have been testing this network modification deploying containers using Apache Mesos, Aurora and Marathon, which also runs as docker containers! Squid, dhcpd and named are also being running inside containers. No surprises so far.

I’d like to trigger the discussion around this implementation. The patch can be found here,
https://github.com/medallia/docker/commit/3065bb6fd281da9f643df726722852a2d6dcc7f4
What do you think?

I have two questions that came up while playing with 1.7 code:
- Sometimes is desirable to have more than one ip address in the container; is the idea that we should have two endpoints pointing to the same iface? I replaced InterfaceInfo.Address with an []net.IPNet 
- Is it possible to manipulate net namespaces inside the driver? I had to hack in sandbox.configure_linux to be able to add a route to the host. What would be the best place to do that?

Thanks,

**Comment by dave-tucker** [comment]
Hi @mauri - take a look at the docs here: https://github.com/docker/libnetwork/blob/master/docs/remote.md

1) IIRC it was decided that there wasn't a use case for having multiple attachments the same network (e.g a network using the routed driver in this case). To implement this right now, you would need two networks and to attach to the second one (using the `docker service attach` CLI) after the fact

2) Yes. See https://github.com/docker/libnetwork/blob/master/docs/remote.md#join as this the point where you can provide some routes

**Comment by dave-tucker** [comment]
Also, re 1) another option would be to provide multiple IP addresses for a given interface. I'm not sure if the API allows this right now but I think that would be a useful feature.

**Comment by mauri** [comment]
Hi @dave-tucker thanks for the answer.

WRT 1) I actually changed InterfaceInfo to have Address() []net.IPNet instead of only one, so I'm using just one endpoint. I have a patch with the whole thing here https://github.com/medallia/docker/commit/3065bb6fd281da9f643df726722852a2d6dcc7f4 if it makes sense I can extract the Address() changes and send a PR to support multiple addresses.

**Comment by dave-tucker** [comment]
@mauri I think we'd still need a facility to indicate which of the IP's was supposed to be the primary for that interface. If you could create an issue specifically for supporting multiple (e.g secondary) IP addresses in InterfaceInfo, we can discuss the design there. I think then if I've answered 2) to your satisfaction we can close this question!

**Comment by mauri** [comment]
sounds good!
