### ISSUE TITLE
Vagrantfile is producing an error on container startup.

### ISSUE THREAD

**Issue by ping-identity** [docker/libnetwork#432]
vagrant@net-1:~$ docker run -i -t --publish-service=svc2.dev.overlay debian
Unable to find image 'debian:latest' locally
latest: Pulling from library/debian
902b87aaaec9: Pull complete 
9a61b6b1315e: Already exists 
Digest: sha256:bbc01a8af2e75ee2d951c69e9cea6390b4e669782fb2cb93b0782af087a7c1bc
Status: Downloaded newer image for debian:latest
Error response from daemon: Cannot start container 8c463d1f75907368ea32a5aba259013d4d7e37b9d0620e477e2c74892392e199: [8] System error: no such file or directory

**Comment by mavenugo** [comment]
@ping-identity this is resolved by https://github.com/docker/libnetwork/pull/431. Can you pls confirm ?

**Comment by ping-identity** [comment]
Confirmed working
