### ISSUE TITLE
Add dnet cli tool

### ISSUE THREAD

**Issue by mrjana** [docker/libnetwork#45]
This is a development and debugging tool

**Comment by tomdee** [comment]
Could you provide some more detail on what this is? Would this be a way of running libnetwork code from the CLI without using docker/docker?

**Comment by mavenugo** [comment]
@tomdee yes.

**Comment by kunalkushwaha** [comment]
I would like to pick this issue if no one is yet picked up. 

Can you please discribe little more on this?
Is this cli will be like linux dnet (http://linux.die.net/man/8/dnet) tool ?

**Comment by mavenugo** [comment]
@kunalkushwaha this is already done under `cmd/dnet/` I will mark this as closed
