### ISSUE TITLE
Why are routes added by libnetwork and not by remote driver?

### ISSUE THREAD

**Issue by MalteJ** [docker/libnetwork#458]
In the remote driver documentation it says

> The entries in "StaticRoutes" represent routes that should be added to an interface once it has been moved into the sandbox. Since there may be zero or more routes for an interface, unlike the interface names they can be supplied in any order, and are marked with the InterfaceID of the corresponding interface.`
> https://github.com/docker/libnetwork/blob/master/docs/remote.md

Why are the routes just described by the remote driver but added by libnetwork?
Could the driver not add the routes itself?

Thanks for clarification.
Malte

**Comment by squaremo** [comment]
> Why are the routes just described by the remote driver but added by libnetwork?

Because libnetwork will subsequently put the interfaces in a network namespace that it has created for the container, and when it does so, any configuration of the interfaces (IP addresses, static routes) is reset. The driver cannot do this, because it's not told about the network namespace.

**Comment by MalteJ** [comment]
ahh, I think if have had misunderstood the flow.
I thought the driver would do all the veth pair and netns stuff. But it just has to provide the info. libnetwork creates all of this and the driver just has to connect the non-namespaced-veth device with a linux bridge or something.

Thank you! :)

**Comment by squaremo** [comment]
> libnetwork creates all of this and the driver just has to connect the non-namespaced-veth device with a linux bridge or something.

You've got it exactly. It's not the only possible design, but it's libnetwork's design.

**Comment by MalteJ** [comment]
thanks for your help!

**Comment by thaJeztah** [comment]
@MalteJ does that help you with your project, or will that complicate things?

**Comment by MalteJ** [comment]
It's fine.
I just think the name "driver" is misleading. It's more of a control plane, isn't it?

**Comment by MalteJ** [comment]
One thing you cannot do is setting up iptables within the network namespace.
You always have to do the firewalling on the bridge.
