### ISSUE TITLE
Optimization Idea

### ISSUE THREAD

**Issue by robin-zhou** [docker/libnetwork#460]
https://github.com/docker/libnetwork/blob/master/ROADMAP.md
The libnetwork's roadmap says: libnetwork aims to satisfy that composable need for Networking in Containers.
I have some idea about improve the libnetwork, make it more flexible in a docker cluster to config containers' network. Just as Neutron, we define a plugin/agent mode.
Does anyone think about it ?  please give me some advice , thanks.

**Comment by fcrisciani** [comment]
no further activity here and architecture changed since then, closing
