### ISSUE TITLE
Provide CLI and remote API options to force remove networks and endpoints

### ISSUE THREAD

**Issue by abronan** [docker/libnetwork#464]
It is not possible to force remove an `endpoint` or a `network` through the cli and remote API.

If a network depends on many endpoints, we need to remove the endpoints first before removing the network. This would be convenient to provide a way to *force remove* a network, which means that the dependency is ignored or that all dependent endpoints are also deleted by this operation (the same way we are able to force remove `containers` and `images` with `-f`).

**Comment by mavenugo** [comment]
@abronan network and endpoint objects are global in nature and hence forcing a removal on a node can be communicated effectively across the cluster and perform the cleanup. But, unfortunately, the container (sandbox) that is attached to the endpoint is a locally scoped object and hence attach/detach event is done on the local node where the container exist. Also, a distributed forced removal requires strong lock support, which we don't make use of today in libnetwork.

Also, a `-f` on a container or image has a localized effect, whereas a forced removal of network will have a cluster-wide effect that will impact connectivity for many containers and even worse,we cannot guarantee bringing the containers back to the same networking state as before.

If there is a strong requirement for this feature request, then it has to go through a thorough design process.

**Comment by abronan** [comment]
Thanks for the clarification :+1: , yes the distributed nature of the operation: ie. spreading network configuration and information between machines makes the operation a lot more complex to implement. I guess that from a UI perspective I expected a `-f` to be present. As of now I'm creating a lot of endpoints and networks for testing and removing them is quite tedious.

For the containers being in an inconsistent state, I guess that `-f` implies that the containers attached to an endpoint that is force removed must be removed/re-started and re-attached to a new endpoint (for now, we can probably find better ways to handle that later on).

We can leave this on hold, the feature can wait but I feel like I will not be the only one expecting a `-f` flag to be present :smile:

**Comment by mavenugo** [comment]
@abronan Yes. We have a similar request from @shykes on atomic service swap, where it will replace the 2 step process that we have `dettach` from an existing service and `attach` to another service. The idea is to perform this operation from any of the host in the cluster. These distributed configuration enhancements can all be considered under the same design effort.
