### ISSUE TITLE
External nodes network routing configuration to overlay mode containers

### ISSUE THREAD

**Issue by ajaybhatnagar** [docker/libnetwork#468]
Hi 
I tried overlay driver and it worked well as documented and application was able to connect to external nodes. However, in a cluster type of setup, if container is launched on specific node, route need to be added on remote hosts (not part of docker containers ). For example, If I have two nodes on which I can launch docker containers, then I need to change route on "external nodes" to route thru specific node on which container is running.

Would it be possible to have single route point  interface defined  or I have missed something?

My setup is as follows 
two nodes running docker and overlay driver with consul setup (as per documentation). 
docker version: 1.9.0-dev, build 1425b18 , OS: 3.16.0-46-lowlatency (Ubuntu)

If container is launched on node 1 then I have to define route add  on the external node (other than these two nodes) via node 1 ip address, if container is launched on node 2 , I need to define route add via node 2 ip. 
node 1 is running with bootstrap command option and node 2 is running with agent.

Also it is not clear, if we have more than 3 nodes, does all 3 nodes have to point to first node ip or they have to form a loop with neighbor's IP?

Thanks
Ajay
In virtualized setup the ip address could be floating.

**Comment by fcrisciani** [comment]
I think the solution here is going to remain outside of docker itself. Overlay is on top of the physical network, and the physical network itself has to provide proper connectivity between nodes
