### ISSUE TITLE
Start an overlay network with the consul bits in a container

### ISSUE THREAD

**Issue by Crazee** [docker/libnetwork#488]
I’ve been using docker-machine to create boot2docker-based hosts for my containers.  So I wanted to connect the hosts together using the fancy new “docker network” doodads.

What I wanted to do was
1. Create a new (boot2docker based) machine via docker-machine
2. On that machine setup a consul server via a progrium/consul container
3. Then get the docker process on the host machine to --kv-store=consul:localhost:8500
4. And then use “docker network create –d overlay mustard” to create an overlay network

But it seems impossible to create the consul bits in a container, because it has to be running before creating the boot2docker machine in the first place.  The examples suggest running a separate, outside of docker, host for the consul server, with publicly accessible IP address, etc.  Which I don’t want to do.

I’d later create new docker hosts in the same manner and glue them together with some kind of “consul join” mechanism.

Is it possible to make this networking architecture more “self-contained”?

**Comment by mavenugo** [comment]
@Crazee when you say `self-contained` what do you mean ? 
Embed consul (or other KV Store) inside libnetwork and not have the need to deal with this external bootstrapping issue ?

**Comment by Crazee** [comment]
That would help, as long as you could delay the grouping of the hosts together (via consul join) til later.  Until I can connect the hosts together with a container that creates a private VPN mesh.

**Comment by fcrisciani** [comment]
In swarm mode we have networkDB that is fully managed by libnetwork. I think this addresses this request
