### ISSUE TITLE
libnetwork overlay driver - plan for supported systems

### ISSUE THREAD

**Issue by rhim** [docker/libnetwork#492]
Hi Folks,

I see that libnetwork 0.5 is slated to go in docker 1.9. Overlay driver has dependency on kernel 3.16. Is it fair to say then if libnetwork 0.5 includes overlay networking, then docker 1.9 will require kernel 3.16 or newer (and hence will only support systems, like Ubuntu 15.04 that have that kernel).

Thanks,
Himanshu

**Comment by mavenugo** [comment]
@rhim fair question. But, from what we understand Ubuntu 14.04.3 LTS supports 3.19 kernel by default (https://wiki.ubuntu.com/TrustyTahr/ReleaseNotes#Updated_Packages).

Given the fact that latest 14.04 LTS has the updated kernel, you could just upgrade to 14.04.3 with the supported 3.19 kernel. Will that satisfy your needs ?

**Comment by mrjana** [comment]
@rhim But please note that this does not mean that docker 1.9 will not be supported in kernels < 3.16. It just means that if you need to use overlay driver you need to use a kernel version >=3.16. This is very similar to storage layer drivers like `overlay` (coincidentally with the same name) are supported only from kernel version >= 3.18

**Comment by rhim** [comment]
Thanks folks. @mrjana - that makes sense.
@mavenugo : yes it should. I will give it a spin and see how it goes.

**Comment by mavenugo** [comment]
Thanks @rhim closing the issue
