### ISSUE TITLE
`docker service ls` can't list container which is created by another machine

### ISSUE THREAD

**Issue by WeiZhang555** [docker/libnetwork#506]
I'm using a private network plugin, I found that the "docker service ls" can't list containers which are created by another machine. 
for example:
on machine A, using `docker run -itd --publish-service web.PluginNet ubuntu bash`  to start a container and register a service, then `docker serivce ls` will show that the service `web` has been bound to the container.
On another machine running docker daemon on same consul cluster with machine A, `docker service ls` can show the service but can't show the container ID.
This is one newly introduced bug and previous version works fine.

I tried to track the code, and found that endpoint has only sandboxID and since sandbox is not put into KV, we have no method to retrieve containerID from only sandboxID, so only machine on which the container is created can see container ID using `docker service ls`.

This leave us some choices to fix the bug:
1. Put sandbox data into KV, and watch sandbox changes in libnetwork controller. 
2. Add one more `containerID string` in endpoint structure. This is not a good choice, but as remote machine only cares about container ID but not the whole sandbox structure, this is most simple and need little change.
3. Us `containerID` as sandbox `ID`. The will revert late change of sandbox structure, I suppose you will not like this .

WDYT? Any good suggestions?  ping @aboch @mavenugo

**Comment by aboch** [comment]
@WeiZhang555 We are aware of this. Discussed with @mrjana and we are not planning to make changes, because sandbox is a local scope entity. At most we are thinking of a UI/presentation change where something like "remotely connected" can be shown under the container id column.

But we are holding on this because as @mavenugo mentioned somewhere else there are going to be UI changes coming in.

**Comment by WeiZhang555** [comment]
@aboch That's fair. 
But currently it's so inconvenient

**Comment by aboch** [comment]
@WeiZhang555 Understand. WDYT about changing the client code to show something on the line of "remotely connected" for the `service ls` command ?

**Comment by WeiZhang555** [comment]
@aboch That's fair. 
But currently it's so inconvenient, you see that If I connect one container to some service on one machine, then I can see the service with `docker service ls` on another machine, it tells me the service has not connected to any container but it fails when I try to connect another container to this service, this makes user confused easily. 
And if we publishes a lot of global services, how can we easily distinguish which service is available to use?

I like your idea of putting "remotely connected" under container id column, maybe we can implement this as a temporary solution?
It looks like not too much work to do and isn't hard to do, I can bring a PR if you feel OK about this. :)

**Comment by aboch** [comment]
@WeiZhang555 Yes, please push a PR for the `service ls` output fix. Thanks !

**Comment by WeiZhang555** [comment]
OK, I'll handle that. :)

**Comment by aboch** [comment]
`docker service` is another CLI which does no longer exist after multihost networking exited experimental.

Closing this issue then.
