### ISSUE TITLE
Zookeeper, etcd support multiple IPs but datastore.newClient only takes one.

### ISSUE THREAD

**Issue by alfredr** [docker/libnetwork#507]
Zookeeper, etcd support multiple ips but datastore.newClient only takes one.

This can cause inability to restart docker if the Zookeeper or etcd peer specified in kvstore argument goes down -- even if the other n-1 are up.

Further it appears that this list is the complete list of alternate backends that go-zookeeper/etcd client libraries will try in the event of a failure, meaning that if only one is specified it constitutes a single point of failure.

**Comment by mavenugo** [comment]
Thanks for reporting the issue. we will take a look at this
