### ISSUE TITLE
Dynamically maintained unqualified names in `/etc/hosts` obstruct resolution via search path

### ISSUE THREAD

**Issue by awh** [docker/libnetwork#519]
Current experimental Docker maintains entries in each container's `/etc/hosts` file for all services attached to the same network as the container. These entries take two forms: one with the unqualified container name (e.g. `172.17.0.11    foo`) and one with container name qualified with the network name (e.g. `172.17.0.11    foo.bridge`).

The unqualified entries are problematic because they obstruct search path resolution via DNS, preventing end users from taking full advantage of ecosystem service discovery solutions such as weaveDNS. Is there any way of disabling this behaviour?

Referencing weaveworks/weave#1374.

**Comment by awh** [comment]
You currently have fixing docker/docker#15617 scheduled into 1.9.0, from which I conclude that you're going to make this behaviour conditional - could this be exposed to us on a per `docker run` basis so that we can turn it off selectively for containers that are on the weave network?

**Comment by geku** [comment]
For me too, disabling this feature would be important as I have another networking solution in place. Even entries like `172.17.0.11 foo.bridge` are not ideal as I would like to have an `/etc/hosts` file which is never changed again after starting the container.

**Comment by fcrisciani** [comment]
Name resolution changed a lot since this time and is not anymore using resolv.conf
