### ISSUE TITLE
bit sequence handler does not initialize with zookeeper backend.

### ISSUE THREAD

**Issue by alfredr** [docker/libnetwork#523]
Passing kv-store="zk:10.3.0.151"

FATA[0000] Error starting daemon: Error initializing network controller: error obtaining controller instance: failed to initialize vxlan id manager: failed to initialize bit sequence handler: zk: node does not exist.

Zookeeper seems otherwise fine. This works with consul so it seems like it might be a difference in semantics between the two backends.

**Comment by abronan** [comment]
This should be fixed with the latest `libnetwork` and `libkv`. Thanks for reporting and opening the issue!

**Comment by abronan** [comment]
Fixed by docker/libkv#82
