### ISSUE TITLE
(Question) can ontainers talk to each other without publishing service when using overlay network?

### ISSUE THREAD

**Issue by gauravphoenix** [docker/libnetwork#530]
I am not sure if this is by design:

I'm running two containers Container X and Container Y on two different hosts. Docker daemons running on both of the hosts are connected via the overlay network. I'm not using docker swarm. 

Now if I don't publish any service, X can't reach Y (and vice-versa) using IP address or hostname.

So my question is- can two containers talk to each other using IP address even if they are not publishing any service? In other words, is publishing a service a requirement for overlay networking to work?

**Comment by mavenugo** [comment]
@gauravphoenix publishing a service is mostly to publish the service name in the network so that the containers can reach each other using the name. But, they are still reachable by default using the ip-address without the need for publishing the service name.

**Comment by gauravphoenix** [comment]
@mavenugo thanks for clarification. 

On Debian jessie kernel version  3.16.0-4-amd64 I don't see that behavior. If I don't publish any service /etc/hosts are not updated at all. I am using latest docker binary from experimental.docker.com

**Comment by mavenugo** [comment]
@gauravphoenix thats exactly the expected behavior. if you dont publish a service, then /etc/hosts will not be updated. but containers can still reach other via ip-address.

**Comment by gauravphoenix** [comment]
@mavenugo I must have calrified that they can't reach each other using IP address

**Comment by gauravphoenix** [comment]
Refer to below screenshot. As soon as I published the service, I was able to ping 172.21.0.8 which I wasn't able to before.

![image](https://cloud.githubusercontent.com/assets/627662/9898809/533cbb1c-5c0a-11e5-9688-a27b511902ff.png)

**Comment by gauravphoenix** [comment]
This is weird, I restarted my consul server (deleting all data including key value data), restarted daemons and now I am containters are able to ping each other without publishing any service.

**Comment by mavenugo** [comment]
@gauravphoenix can you post your `docker version` output ?

**Comment by gauravphoenix** [comment]
```
root@dockerhost3:/home/gaurav# docker version
Client:
 Version:      1.9.0-dev
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   ec6d91c
 Built:        Fri Sep 11 18:33:47 UTC 2015
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.9.0-dev
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   ec6d91c
 Built:        Fri Sep 11 18:33:47 UTC 2015
 OS/Arch:      linux/amd64
 Experimental: true
```

**Comment by fcrisciani** [comment]
works on master, closing
