### ISSUE TITLE
remote api, returned IP address is none

### ISSUE THREAD

**Issue by rospring** [docker/libnetwork#531]
Hi,

i have the following problem: if my plugin puts 
`"Address": None`
when endpoint creation is called (/NetworkDriver.CreateEndpoint) then in etcd the value is stored as 
`"addr": "<nil>"`
When the join is called docker would like to add <nil> as an IP address, which is not right. Maybe i am wrong but there is a check whether IP address is nil or not, an if it is not defined then ip addr add is not executed. but in this case "<nil>" is a string and join fails.

Thanks your help in advance!

Update: net/ip.go has method String() which returns "<nil>" when IP or IPMask or IPNet is empty. Check should be done when configuring the interface or when information is stored. I made ugly check in osl/interface_linux.go and it seems this is the problem.

**Comment by fcrisciani** [comment]
not sure if this is still relevant but due to the age will close for now
