### ISSUE TITLE
bridge IP allocator should reserve the address of the default gateway

### ISSUE THREAD

**Issue by mountkin** [docker/libnetwork#538]
If the user adds the physical interface to a bridge and configures Docker to use the same subnet as the host (start daemon with the -b parameter), the IP address of the default gateway might be in the IP pool of the allocator.
In such case we should exclude it from the IP pool. Otherwise the gateway IP may be assigned to a container, which will disrupt the host network.

The problem can be reproduced by:
- run the following script with your own network variables (gateway IP, interface name, IP addr, etc.)
```bash
#!/bin/bash
ip l add br1 type bridge
ip l set br1 up
ip ad flush dev eth0
ip ad add 192.168.122.122/24 dev br1
ip l set eth0 master br1 promisc on
ip r del default
ip r add default via 192.168.122.1 dev br1
arping -A -b -c 1 -I br1 192.168.122.122
```
- Start docker daemon with docker daemon -b br1
- Create some containers

As discussed in #517 this should be addressed when the bridge driver make use of the IPAM driver.

**Comment by aboch** [comment]
@mountkin Now that the IPAM driver is in, docker user can add the known interface's address as auxiliary address when creating the network. Libnetwork will reserve the auxiliary addresses with IPAM driver so that on new container connect, that IP will not be given out by the ipam driver.

Could you please check whether this is enough to solve the reported by this issue ?
Thanks

**Comment by mountkin** [comment]
@aboch I did the following test but it seems that the specified `--aux-address` are not reserved properly after the last IP address of the pool is taken and then reiterates from the beginning of the IP pool.

```bash
#!/bin/bash
docker-dev network rm dev || true
docker-dev network create -d bridge --gateway=192.168.123.1 \
  --ip-range=192.168.123.200/28 \
  --subnet=192.168.123.1/24 --aux-address='ip1=192.168.123.200' \
  --aux-address='ip2=192.168.123.201' dev
docker-dev network inspect dev

for ((i=0;i<10;i++)); do
  docker-dev run --net=dev --rm busybox /bin/sh -c 'ifconfig eth0|grep inet'
done
```

```
b1601415a3058640215e88cbb2b33b7ecfb46448deff6767163e9e3ba2946bf8
{
    "name": "dev",
    "id": "b1601415a3058640215e88cbb2b33b7ecfb46448deff6767163e9e3ba2946bf8",
    "scope": "local",
    "driver": "bridge",
    "ipam": {
        "driver": "default",
        "config": [
            {
                "subnet": "192.168.123.1/24",
                "ip_range": "192.168.123.200/28",
                "gateway": "192.168.123.1",
                "auxiliary_address": {
                    "ip1": "192.168.123.200",
                    "ip2": "192.168.123.201"
                }
            }
        ]
    },
    "containers": {}
}
          inet addr:192.168.123.202  Bcast:0.0.0.0  Mask:255.255.255.0
          inet addr:192.168.123.203  Bcast:0.0.0.0  Mask:255.255.255.0
          inet addr:192.168.123.204  Bcast:0.0.0.0  Mask:255.255.255.0
          inet addr:192.168.123.205  Bcast:0.0.0.0  Mask:255.255.255.0
          inet addr:192.168.123.206  Bcast:0.0.0.0  Mask:255.255.255.0
          inet addr:192.168.123.207  Bcast:0.0.0.0  Mask:255.255.255.0
          inet addr:192.168.123.200  Bcast:0.0.0.0  Mask:255.255.255.0
          inet addr:192.168.123.200  Bcast:0.0.0.0  Mask:255.255.255.0
          inet addr:192.168.123.200  Bcast:0.0.0.0  Mask:255.255.255.0
          inet addr:192.168.123.200  Bcast:0.0.0.0  Mask:255.255.255.0
```

**Comment by aboch** [comment]
@mountkin 

Closing as this now works.

Also, regarding the range, being it is specified in cidr notation, be aware that 
`192.168.123.200/28` == `192.168.123.192/28`.

So you test should be rephrased as
```
$ docker network create --gateway=192.168.123.1 --ip-range=192.168.123.192/28 --subnet=192.168.123.0/24 --aux-address='ip1=192.168.123.192' --aux-address='ip2=192.168.123.193' dev
d6fcd04f4127294c305daf7709a9b09a244958ada4a57935cbe81cd8fac2d8a0
$ docker run --net=dev --rm busybox ifconfig eth0|grep inet
          inet addr:192.168.123.194  Bcast:0.0.0.0  Mask:255.255.255.0
          inet6 addr: fe80::42:c0ff:fea8:7bc2/64 Scope:Link
$
```
