### ISSUE TITLE
Are kernel modules (brige, nf_nat, br_netfilter ) necessary to run docker with libnetwork?

### ISSUE THREAD

**Issue by kimh** [docker/libnetwork#551]
I'm trying to run docker 1.8.1 on lxc container and running a docker container with "-p" option makes docker daemon completely frozen.

Although I can create another issue for why it gets frozen in docker/docker issues, I'm wondering if that is because my lxc container is missing a few kernel moduels. Here is the `/var/log/upstart/docker.log`.

```
Waiting for /var/run/docker.sock
Warning: '-d' is deprecated, it will be removed soon. See usage.
WARN[0000] please use 'docker daemon' instead.
INFO[0000] Listening for HTTP on unix (/var/run/docker.sock)
INFO[0000] Option DefaultDriver: bridge
INFO[0000] Option DefaultNetwork: bridge
WARN[0000] Running modprobe bridge nf_nat br_netfilter failed with message: FATAL: Could not load /lib/modules/3.14.28-031428-generic/modules.dep: No such file or directory
```

So, as you see, it fails to load some kernel modules. In fact, my container is missing these modules

```
$ modprobe brige
FATAL: Could not load /lib/modules/3.14.28-031428-generic/modules.dep: No such file or directory
$ modprobe nf_nat
FATAL: Could not load /lib/modules/3.14.28-031428-generic/modules.dep: No such file or directory
$ modprobe br_netfilter
FATAL: Could not load /lib/modules/3.14.28-031428-generic/modules.dep: No such file or directory
```

So my question is are these kernel modules mandatory in docker 1.8 or newer with libnetwork?

**Comment by kimh** [comment]
Ping. Someone? If this is the type of question that I can't ask here, I will close the, so let me know.

**Comment by mavenugo** [comment]
@kimh apologies on the delay. Yes, it is absolutely the right place to ask these questions.

Bridge driver makes use of linux networking stack extensively which depends on some of these kernel modules based on the enabled features. But as you can see these are WARN messages and doesn't impact the docker bootup itself. 

Are you trying to launch a docker daemon inside a LXC container ?

**Comment by kimh** [comment]
>Are you trying to launch a docker daemon inside a LXC container ?
Yes. Docker boots fine in a LXC container, but the problem that I'm trying to solve is when I run a container with `-p` option, then the container as well as docker daemon itself completely frozen and doesn't respond to any subsequent docker commands.

I run the daemon with `-D` but the only error that I see is these kerne-modules-missing warnings.

Do you think will I get any issues with the use of `-p` option if I miss these modules? (Sorry for vague question!)

**Comment by mavenugo** [comment]
@kimh it should not be a problem. docker build system and the integration-cli all run in DinD (Docker in Docker). you are trying Docker-in-LXC instead and it should just work the same. I would recommend you to look at the docker/docker repo on how dind is used to achieve this.

Also, pls take a look at http://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/ for best practices and NOT so good practice on using DinD.

**Comment by kimh** [comment]
@mavenugo thanks for the explanation. I'll close this issue.
