### ISSUE TITLE
docker network create fails with "failed to allocate vxlan id: no bit available"

### ISSUE THREAD

**Issue by rhim** [docker/libnetwork#559]
I have a consul server setup that is being used as the backend kv store. After a few test runs of docker network create, I started seeing this error:

failed to allocate vxlan id: no bit available

Has someone seen this and have a pointer on how to fix it.

Also, I have seen consul get into state where it just returns 500 error for all calls, and the only way for me to make progress is to remove the consul container and restart from scratch. 

Any feedback on this will be much appreciated.

**Comment by mavenugo** [comment]
@rhim when the backing KV store (consul or etcd or zookeeper) behaves erratically, it will impact the vxlan allocation. can you debug to identify the root-cause on why consul fail to behave ? 
There could be some known bug in consul in the version that you are using. Which version of consul are you trying ?

**Comment by rhim** [comment]
@mavenugo I am using the latest version 0.5.2. What is bizarre is that another host that is pointing to the same consul server is able to create a network just fine. The only difference between these two hosts is that one is a VM running in EC2 (the one that is failing) and one is a physical machine (that succeeds).

Both are running Ubuntu 14.04.3 with kernel 3.19.0-28-generic. 

BTW, I can't find any more debug spew related to this error in /var/log/upstart/docker.log. Am I looking at the right place for overlay driver related log messages?

**Comment by rhim** [comment]
Ohh, found another difference: physical machine is running Docker version 1.9.0-dev, build d9065fc, experimental, while VM is running Docker version 1.9.0-dev, build 7001619, experimental.

I will downgrade VM to d9065fc and see if that fixes the issue. If yes, then it could be a regression.

**Comment by rhim** [comment]
Yup, looks like a regression. I am able to create the network with version d9065fc. Should I file a separate issue for this? Would be nice if someone else could confirm this as well.

@mavenugo : would it be possible for you to ping someone in libnetwork team? Thx.

**Comment by mavenugo** [comment]
@rhim thanks for the confirmation. we can use this issue to debug this further. (no need to file another)

**Comment by aboch** [comment]
We have not had reports of this bug since.
Moreover a couple of bugs in the bitsequence code which could have led to this issue were fixed.
Closing for now.
