### ISSUE TITLE
Support for force-remove network

### ISSUE THREAD

**Issue by mavenugo** [docker/libnetwork#568]
network object is reference counted by number of connected endpoints. It is useful for the case of globally scoped networks to make sure network is not inadvertently removed when there are connected containers. But, there are cases (such as forced docker daemon kill) in which the network refcount gets unaccounted for. Hence we need a way to force-remove a network if the user chooses to.

**Comment by WeiZhang555** [comment]
Is this a placeholder or a `help-wanted` issue?  If it's an issue that call for help, I'm interested to contribute and help. :)

**Comment by mavenugo** [comment]
@WeiZhang555 this is currently a place holder issue waiting on @mrjana 's changes to the datastore. Once his changes are in, we will have a better judgement on the complexity of this particular issue.

**Comment by WeiZhang555** [comment]
OK, got it.

**Comment by fcrisciani** [comment]
this feature is available, closing
