### ISSUE TITLE
ip stability on container restart

### ISSUE THREAD

**Issue by mavenugo** [docker/libnetwork#569]
since CNM's lifecycle provides an ability to retain endpoint even when the container restarts, it would be useful to provide the ip stability by reusing the endpoint.
It ofcourse has other issues such as ip-address exhaustion. But that can be mitigated by forcing the user to cleanup any stopped container. Removing a container should result in deleting the endpoint and that is a reasonable compromise.

**Comment by WeiZhang555** [comment]
This is a nice feature, really looking forward to this :+1:

**Comment by fcrisciani** [comment]
This is the current behavior iff there is only 1 container restarting, if there is more than one there would be a race between the 2 and it is possible that the IP will be swap between the restarting containers
