### ISSUE TITLE
iptables rules are not honored by overlay traffic 

### ISSUE THREAD

**Issue by gauravphoenix** [docker/libnetwork#571]
I've two docker hosts (host1 and host2) connected via the overlay network. On host1 I am running a container which listens on port 80 and I can access it just fine from host2. 
Now if I create a iptables rule  `iptables -A INPUT -p tcp  --match multiport --dports 80 -j REJECT` I expect that I can't access port 80 anymore from host2. But that doesn't happen. I've also tried using FORWARD chain and that doesn't work either. 

So my question is- how do I configure overlay networking such that host IP tables rules can be honored?

**Comment by robert-blankenship** [comment]
+1

**Comment by chenchun** [comment]
> I've two docker hosts (host1 and host2) 

Do you mean host1 and host2 are docker containers?

> Now if I create a iptables rule iptables -A INPUT -p tcp --match multiport --dports 80 -j REJECT I expect that I can't access port 80 anymore from host2.

Where did you create these rules? are you creating them inside containers? I think if you create these rules inside host1 container instead of on the host machine, you'll get what you want.

**Comment by chenchun** [comment]
```
root@docker-1:/home/vagrant# docker network create -d overlay vxlan
566ed3abcd7e69c37a70ca004ff31ef320b465aab5b183b14cf83921d405cf44
root@docker-1:/home/vagrant# docker run --net=vxlan --name=host1 -d --privileged ubuntu nc -lk 80
9000eb11d1706423c0881474ea0111132ab95d1d7bde3217ca9fa839e6523267
root@docker-1:/home/vagrant# docker exec -it host1 bash
root@9000eb11d170:/# apt-get update && apt-get install iptables 
...

root@docker-1:/home/vagrant# docker run --net=vxlan --name=host2 --rm ubuntu nc -v host1 80
Connection to host1 80 port [tcp/http] succeeded!
root@docker-1:/home/vagrant# docker exec host1 iptables -A INPUT -p tcp --match multiport --dports 80 -j REJECT
root@docker-1:/home/vagrant# docker run --net=vxlan --name=host2 --rm ubuntu nc -v host1 80
nc: connect to host1 port 80 (tcp) failed: Connection refused
```
