### ISSUE TITLE
failed to create endpoint: Bind for ... failed: port is already allocated.

### ISSUE THREAD

**Issue by alfredr** [docker/libnetwork#575]
This happens after stopping and removing the old container that was using the port, the port is unavailable. It seems like it's like it's not releasing the old port from the port allocator. The only way to get the port back seems to be to restart docker.

Further, there is a stale docker-proxy hanging around and the system seems to have accumulated a large number of stale virtual interfaces.

**Comment by fcrisciani** [comment]
this issue is fixed on master. closing
