### ISSUE TITLE
persistent failure of atomic kv operations until docker is restarted

### ISSUE THREAD

**Issue by alfredr** [docker/libnetwork#576]
Frequently, I get errors of the following form on container start which persist until docker is restarted.

```
docker start e834638cd1db -- Error response from daemon: Cannot start container e834638cd1dbbc60209a772c385d5f15d8a86b8d12a96e04d077e52869555b0c: Unable to complete atomic operation, key modified
```

Other docker hosts which use the same consul instance as a kv store for libnetwork do not have this issue and consul continues to operate normally.

**Comment by fentas** [comment]
had the same issue right now with `Docker version 17.10.0-ce, build f4ffd25`.
`service docker restart` helped. :+1: 

But I guess unresolved issue.

**Comment by abhi** [comment]
@fcrisciani they are not related. Lets track it with moby issues.

**Comment by fcrisciani** [comment]
@abhi the description is actually fitting perfectly the same behavior that I saw, but it's ok to track it on moby, maybe you can post here the reference issue to have a link.

**Comment by mavenugo** [comment]
@fcrisciani i opened https://github.com/moby/moby/issues/35310 to track this. This is unrelated to the IPAM changes. But the `endpoint_cnt` states are messed up due to the lb-endpoint management.

**Comment by fcrisciani** [comment]
@mavenugo sure no prob, agree to keep only one place to track, I previously reopened this one because was generic enough to track the error message experienced.
