### ISSUE TITLE
Who owns the networks?

### ISSUE THREAD

**Issue by tomwilkie** [docker/libnetwork#60]
Its my understanding that libnetwork keeps references to network objects it creates; however, I can't see an interface for retrieving or iterating over these objects.  Is it expected that the caller (ie the docker daemon) keeps a duplicate list of networks, and uses this for looking up network objects for deleting them and listing them?  Or would you be receptive to add Get() and Walk() methods to the NetworkController interface?

A similar question arises for NetworkDrivers.  I understand libnetwork is under development right now, and am happy to put together some code for this (and do a PR).

**Comment by mrjana** [comment]
@tomwilkie Yes the libnetwork api is by no means complete. I was just in the middle of coding these methods right now  so you should see them very soon :-)

**Comment by tomwilkie** [comment]
SGTM; I'll assign this to you, and look forward to seeing the progress.

**Comment by squaremo** [comment]
Presumably this can be closed now that libnetwork is integrated with docker -- @tomwilkie ?
