### ISSUE TITLE
Can't return MAC from remote drivers

### ISSUE THREAD

**Issue by tomdee** [docker/libnetwork#605]
If I return a MAC in the CreateEndpoint call, libnetwork seems to ignore it.
- It doesn't set that as the MAC on the veth in the container
- It doesn't return a MAC when running `docker info`

Furthermore, if I try to return a MAC in the EndpointOperInfo call
`{"value": {"com.docker.network.endpoint.macaddress": "EE:EE:EE:EE:EE:EE"}`

Then the docker daemon crashes with

```
 http: panic serving @: interface conversion: interface is string, not net.HardwareAddr
goroutine 591 [running]:
```

**Comment by mavenugo** [comment]
@tomdee thanks for proactively trying the plugin integration. since you are familiar with the code, would you mind checking whats going on and push a PR ?
Also add a test to make sure it stays working.

**Comment by tomdee** [comment]
Looks like part of this is already addresses by https://github.com/docker/libnetwork/pull/451

I'm not happy tacking this issue as I don't understand how this is meant to work. Can you comment on what the expected behaviour is? e.g. what is libnetwork meant to do with the MAC from the createendpoint call? and why is the MAC given in two places - 1) the createEndpoint and OperInfo?

**Comment by mavenugo** [comment]
ping @mrjana

**Comment by tomdee** [comment]
ping @mrjana 

I'm still failing to get the Calico driver to set the MAC address so that docker inspect shows the correct output...

**Comment by aboch** [comment]
@tomdee The Endpoint mac address that docker stores and reports in the inspect o/p is getting collected by docker right after endpoint creation.
Internally this comes to your remote driver via `EndpointOperInfo()` call.

If you are still hitting the `EndpointInfo.SetMacAddress()` issue, you can discard, if I am not mistaken, currently libnetwork does not do anything with that MAC.

**Comment by aboch** [comment]
We are changing docker info to retrieve the MAC address from Endpoint.Info().Iface().MacAddress(), so you won't hit the marshalling issue in EndpointOperInfo() for remote drivers.
