### ISSUE TITLE
NetworkDriver.CreateNetwork, NetworkDriver.CreateEndpoint options in network UI

### ISSUE THREAD

**Issue by michaelhenkel** [docker/libnetwork#620]
Hi All,

CreateNetwork and CreateEndpoint support the map Options but it doesn't seem to be exposed to the network UI. Am I missing something or is it just not there, yet.

Thanks,
Michael

**Comment by tomdee** [comment]
CreateNetwork options are exposed in the new ipam PR. 

The docker run labels don't seems to be passed to drivers on CreateEndpoint or Join.
As far as I know there is no way for the user to set Options for those two calls.

**Comment by mavenugo** [comment]
@tomdee thats orrect. we have network labels that is coming up.
no endpoint labels yet. We have to get the Service story straight before having that in place.

**Comment by tomdee** [comment]
You wouldn't consider passing in the container's labels on the Join() call?

**Comment by mavenugo** [comment]
@tomdee i tried : https://github.com/docker/docker/pull/13476. but it needs another round of discussions I guess.
