### ISSUE TITLE
--publish-service not available in docker run

### ISSUE THREAD

**Issue by sebgoa** [docker/libnetwork#662]
Hi, started the two hosts setup with the Vagrantfile:

$ docker info
Containers: 1
Images: 4
Server Version: 1.9.0-dev
Storage Driver: aufs
 Root Dir: /var/lib/docker/0.0/aufs
 Backing Filesystem: extfs
 Dirs: 6
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-30-generic
Operating System: Ubuntu 15.04
CPUs: 1
Total Memory: 993.1 MiB
Name: vagrant-ubuntu-vivid-64
ID: UHQQ:GZSM:CVCL:2T56:COG3:WYSM:MRFJ:LORJ:INI3:UZI3:X4PR:CGS6
WARNING: No swap limit support
Experimental: true
Cluster store: consul://192.168.33.10:8500
vagrant@vagrant-ubuntu-vivid-64:~$ docker version
Client:
 Version:      1.9.0-dev
 API version:  1.22
 Go version:   go1.4.3
 Git commit:   add0d25
 Built:        Thu Oct 15 18:08:18 UTC 2015
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.9.0-dev
 API version:  1.22
 Go version:   go1.4.3
 Git commit:   add0d25
 Built:        Thu Oct 15 18:08:18 UTC 2015
 OS/Arch:      linux/amd64
 Experimental: true
vagrant@vagrant-ubuntu-vivid-64:~$ 

I can create a network but not a service:

$ docker service ls
docker: 'service' is not a docker command.
See 'docker --help'.

$ docker network ls
NETWORK ID          NAME                DRIVER
928f84a7058d        foobar              overlay  
a56ba30d9d19        bridge              bridge  
f399ecb48df2        none                null  
44031322c1ed        host                host  

$ docker run -ti --publish-service=foo.foobar ubuntu:14.04
flag provided but not defined: --publish-service
See 'docker run --help'.

So there seems to be a few things out of sync.
- docker --help does not list network or service as commands
- docker run --net can be used to attach a container to a network from lib network but I did not see clear docs around this.
- And --publish-service does not seem to be available anymore

Or I am missing something :)

**Comment by chenchun** [comment]
`--publish-service` is an experimental UX and have been removed. you can take a look at https://github.com/docker/docker/pull/16645

> Replaced experimental --publish-service with --net=<user-defined-network>
