### ISSUE TITLE
simple bridge driver does not cleanup veth interfaces properly on endpoint delete

### ISSUE THREAD

**Issue by mrjana** [docker/libnetwork#68]
The libnetwork test code has revealed that the simple bridge driver is not cleaning up the veth interfaces in endpoint delete operation leaving some stale interfaces on the bridge.

Also, currently bridge driver only expect one endpoint. It should instead store one endpoint per sandbox.

This PR is for fixing the above two issues.

**Comment by dave-tucker** [comment]
Fixed in  #69
