### ISSUE TITLE
Proposal: generalize --net=container:<id> and allow an arbitrary net namespace

### ISSUE THREAD

**Issue by pyakpyak** [docker/libnetwork#692]
It would be more generic if libnetwork/docker allowed `--net=netns:<path>`, similar to (or instead of)  `--net=container:<name|id>`. The latter could be just a shortcut on top of the more generic api.

From the api documentation i'm not sure it's supported.

**Comment by pyakpyak** [comment]
@mrjana @mavenugo do you think it's hard to expose? I can start working on it, but will need some time to learn the codebase.

**Comment by mavenugo** [comment]
@pyakpyak pls refer to https://github.com/docker/libnetwork/pull/372. This was discussed in the past and we couldnt accommodate it into CNM for the said reasons. Please let us know if you have a better idea to support this without breaking CNM.

**Comment by runcom** [comment]
@mavenugo does this comment still stand https://github.com/docker/libnetwork/pull/372#issuecomment-122910307? If yes, is a custom plugin the right thing to develop, as in:
```
docker network create netns12345 -l namespace.path=/var/run/netns/12345
docker run -itd --net=netns12345 fedora
```

**Comment by runcom** [comment]
@mavenugo @aboch any thoughts?

**Comment by runcom** [comment]
ping @mavenugo @aboch

**Comment by mavenugo** [comment]
@runcom today we have the `-o` option to `network create` to pass plugin specific data. But it is highly discouraged to use that as a way to pass on non-portable data such as a namespace path. Such configurations may inadvertently tie in a container to the underlying infra.
