### ISSUE TITLE
flag provided but not defined: --kv-store

### ISSUE THREAD

**Issue by kingbirdzheng** [docker/libnetwork#693]
--kv-store is not defined during setting up overlay network.

<code>
$ docker -d --kv-store=consul:localhost:8500 --label=com.docker.network.driver.overlay.bind_interface=eth0
</code>
Warning: '-d' is deprecated, it will be removed soon. See usage.
flag provided but not defined: --kv-store
See 'docker --help'.

<code>
$ docker --version
</code>
Docker version 1.9.0-dev, build ccf5b60, experimental

**Comment by nicklaslof** [comment]
--kv-store has been replaced with --cluster-store and --cluster-advertise

see https://github.com/docker/docker/blob/master/docs/userguide/dockernetworks.md#native-multi-host-networking

**Comment by kingbirdzheng** [comment]
@nicklaslof thanks for the info.
