### ISSUE TITLE
Kernel version requirement for overlay driver

### ISSUE THREAD

**Issue by kingbirdzheng** [docker/libnetwork#700]
For the overlay driver support, it requires Kernel >= 3.16 as stated in the overlay driver description. It is relatively a new version. I am interested in motivations for this requirement. 

Thanks.

**Comment by mavenugo** [comment]
@kingbirdzheng this is a dupe of https://github.com/docker/libnetwork/issues/329 . It explains the kernel issue that prevents overlay driver from working.

**Comment by kingbirdzheng** [comment]
@mavenugo, sorry for the duplicate existed issue.

Before creating this issue, I failed to search the similar ones, and I still can't find #329 even now :-)

![github_docker_libnetwork_issues](https://cloud.githubusercontent.com/assets/5513784/10720712/10200dee-7bd5-11e5-9ea2-c41f0855d576.PNG)

**Comment by mavenugo** [comment]
@kingbirdzheng just click this :) https://github.com/docker/libnetwork/issues/329

**Comment by mavenugo** [comment]
@kingbirdzheng PTAL #821 . We now support kernels < 3.16. Should be made available in next Docker release.
