### ISSUE TITLE
make network policy available to network drivers

### ISSUE THREAD

**Issue by jainvipin** [docker/libnetwork#708]
Containers could be associated with a network policy, for example
- security policy: who can talk to/from a service/container
- infrastructure policy: specify the affinity towards network infrastructure usage (bandwidth/latency/etc)
- ipam policy: that dictates various attributes to consider when implementing ipam for network/service tiers
- NFV policy: use of an virtual/physical network-function (e.g. fw or lb), when container (or a group identified) in some way to be associated with it
- etc.

https://github.com/docker/docker/pull/13476 captures some discussion on why labels are not the best to serve specifying the information to the drivers. There is however a need to allow getting this information in the drivers during CNM Join event. I could understand that specifying the grouping of containers can be done OOB (for now) but there is a need to get the tags/attributes/labels/options to the drivers to get this hint.

Ideally a driver should be able to do, things like following based on OOB definition of interpreting those opts/labels/attributes:
- if a container belongs to 'prod' class, assign it a higher network priority
- if a container is associated with 'test' limit is bandwidth usage to '10Mbps'
- If a container is a 'storage_infra', then provide the traffic with 'lossless' network

In order to support the richness and the use cases, it would be best if network attributes are available in some form in the drivers in the docker ecosystem.

Of course, the easiest thing that would work for me would be what @mavenugo suggestd that a driver 'foo' should be able to get 'com.foo.xxx' labels. I wanted to get community input and response from libnetwork MAINTAINERS for this and discuss it; of course we'll be happy to submit a PR for this change.

And in doing so, if the worry is to keep the image intact/unmutated w.r.t. what drivers can do when the app is deployed, then we are leaving out the possibility of an application leveraging the network niceties for above use cases for container runtime.

I will perhaps write a separate proposal/issue on making policy (ideally network/storage/compute) a first class object in docker ecosystem. Until then, a way to implement this using labels/options to get this information during container Join (along the lines of above PR) would be wonderful.

**Comment by mavenugo** [comment]
thanks @jainvipin for raising this issue. Just to clarify on the terminology usage. AFAIU, Labels have a specific and special meaning in docker daemon as discussed in #13476 whereas the options passed to driver (policy or otherwise) doesn't seem to fit that very well. In order to make it easy for such proposals, lets call it driver options. If any of the functionality expected of those options fit the definition of labels, then we could call it out explicitly. Lets hear from @icecrime on his views on this topic.

**Comment by jainvipin** [comment]
@mavenugo - sure; I have yet to fully understand the subtlety of the terminology and underlying assumptions around 'labels' vs. 'options' - because options in libnetwork was introduced very recently. From what I understood, labels need to keep the immutable nature of an application i.e. ideally wouldn't change the meaning of where  an application gets deployed.

Given that, I don't see anything wrong with making network (and thus network drivers) aware of 'network related labels', if not all labels. If an image was tagged with certain labels, then those can only be used in meaningful way if network drivers become aware of it. I would love to get some take from @icecrime and others on it.

If we need a layering of translation:
- do we need a plugin entity to be able to translate that in custom way to convert the network labels to driver options?
- how could those converted options be provided during docker run (CNM join)

**Comment by shettyg** [comment]
+1 on the requirement.

The network options should ideally be available both for 'docker run --net=foo' as well as 'docker network connect foo'. Ability to associate security policies, network QoS etc for a container makes it a first class citizen in a datacenter.
