### ISSUE TITLE
no vxlan interface created using overlay driver

### ISSUE THREAD

**Issue by kingbirdzheng** [docker/libnetwork#730]
Following the overlay.md, I am trying to set up a overlay network cross 2 hosts. However, I find the overlay.md is out of date since some commands doesn't work right now. Is there any resource I can refer to for the latest commands?

I summarize the commands based on searching in issues. What the IP address and port should be specified for the <code>--cluster-advertise</code>?

<code>$ docker -d --kv-store=consul:localhost:8500 --label=com.docker.network.driver.overlay.bind_interface=eth0</code>
=> 
<code>$ docker -d --cluster-store=consul://localhost:8500 --cluster-advertise=???.???.???.???:???</code>

<code>$ docker -d --kv-store=consul:localhost:8500 --label=com.docker.network.driver.overlay.bind_interface=eth0 --label=com.docker.network.driver.overlay.neighbor_ip=<host-1-ip-address> </code>
=>
<code>$ docker -d --cluster-store=consul:localhost:8500 --cluster-advertise=???.???.???.???:??? </code>

**Comment by kingbirdzheng** [comment]
@mavenugo

**Comment by thaJeztah** [comment]
@kingbirdzheng up to date documentation on overlay networking can be found in the docker documentation; http://docs.docker.com/engine/userguide/networking/get-started-overlay/

hope this helps!

**Comment by thaJeztah** [comment]
@mavenugo perhaps the old documentation here should be removed? I don't think the `/docs` directory from lib network is currently published on docs.docker.com?

**Comment by kingbirdzheng** [comment]
@thaJeztah thanks for the update.
