### ISSUE TITLE
for sandbox implementation, just network namespace?

### ISSUE THREAD

**Issue by AdoHe** [docker/libnetwork#733]
FYI.

**Comment by pyakpyak** [comment]
@AdoHe If i understand you correctly you want to be able to join any arbitrary namespace with your container? 

I agree it's very easy to apply configuration directly to net ns and then move it to a container + you're not restricted by existing api. I created a request for this ~month ago #692 . It would be nice if docker supports this directly.

**Comment by AdoHe** [comment]
@pyakpyak yes, exactly what I want. I will take a look of your pr.

**Comment by mavenugo** [comment]
Closing this issue as this is a dupe of https://github.com/docker/libnetwork/issues/692.
