### ISSUE TITLE
typo error in documentation ?

### ISSUE THREAD

**Issue by debianmaster** [docker/libnetwork#746]
Last command in the documentation (scroll to the end)  
`$ docker-compose up --x-networking up -d`  
https://docs.docker.com/engine/userguide/networking/get-started-overlay/  

should be 
`$ docker-compose  --x-networking up -d`

**Comment by thaJeztah** [comment]
Thanks for reporting @debianmaster, this was actually fixed already (but not yet published on the website); see https://github.com/docker/docker/pull/17713

**Comment by fcrisciani** [comment]
I think now is published :) closing

**Comment by debianmaster** [comment]
👍
