### ISSUE TITLE
What do I do with "subnet sandbox join failed for "10.0.0.0/24": error creating vxlan interface: file exists"

### ISSUE THREAD

**Issue by danehammer** [docker/libnetwork#751]
I am following [this doc](http://docs.docker.com/engine/userguide/networking/get-started-overlay/) and everything goes swimmingly verifying the overlay network, seeing each agent in the swarm get it created. But when I try to run the nginx image, I get this message:

```
root@hobo:~# docker run -itd --name=web --net=my-net --env="constraint:node==hobo" nginx
ed181ec9bd9422284451ef4106ffc272c31747a8fd187566a3ab6d768cc7fc02
Error response from daemon: Cannot start container ed181ec9bd9422284451ef4106ffc272c31747a8fd187566a3ab6d768cc7fc02: subnet sandbox join failed for "10.0.0.0/24": error creating vxlan interface: file exists
```

I'm not sure how to act on that. I've tried different nodes, and I've tried putting the "-H tcp://\<manager_ip\>:2376" in the docker command to send it to the swarm "host", with no impact, same behavior.

**Comment by danehammer** [comment]
Hey sorry for opening this. Some how my google-fu failed me earlier, there's [another issue](#562) where this same thing happened, so I ended up taking down the docker service on every node, blowing away those /var/run/docker/netns/* files, and everything works.

How cool is it that I ran a wget on one container and pulled a website from another container, with zero port config and mapping?!

**Comment by dave-tucker** [comment]
@danehammer it's pretty cool isn't it :sunglasses: 
glad you found a solution! let us know if you get stuck
happy networking!

**Comment by aravindsappstore** [comment]
@danehammer I keep getting this error on v1.10 and if I do a `service docker stop; service iptables restart; service docker start` it goes away.

**Comment by brettdh** [comment]
I too am seeing this on 1.10. Solved by rebooting the hosts. Thanks @aravind-murthy; next time I will try restarting iptables.

**Comment by dave-tucker** [comment]
For those seeing this on 1.10, please open a new issue and provide some more information about your environment - see [here](https://github.com/docker/docker/blob/master/CONTRIBUTING.md#reporting-other-issues) for details. This will help the maintainers to better identify what is causing this.
