### ISSUE TITLE
mac-address ignored in overlay network

### ISSUE THREAD

**Issue by bergtwvd** [docker/libnetwork#753]
I have a container that requires a specific MAC address (for licensing). When I run the container on an overlay network the MAC address seems to be ignored and I cannot run the container.

The command is:
docker run -d --net=training1 --mac-address="00:18:8B:0D:4F:0B" --name crc -p 9001:9001  xxxx/container1

docker@mhs-demo0:~$ docker info
Containers: 5
Images: 100
Server Version: 1.9.0
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 110
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.12-boot2docker
Operating System: Boot2Docker 1.9.0 (TCL 6.4); master : 16e4a2a - Tue Nov  3 19:49:22 UTC 2015
CPUs: 1
Total Memory: 996.2 MiB
Name: mhs-demo0
ID: 7LLO:X7J6:DBNR:NTW7:UXIB:2EIB:WX6H:FYVH:REED:CH5K:NONT:VP3U
Debug mode (server): true
 File Descriptors: 46
 Goroutines: 95
 System Time: 2015-11-14T13:55:29.554181416Z
 EventsListeners: 1
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Username: bergtwvd
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Cluster store: consul://192.168.99.100:8500
Cluster advertise: 192.168.99.101:2376

docker@mhs-demo0:~$ docker --version
Docker version 1.9.0, build 76d6bc9

docker@mhs-demo0:~$ uname -a
Linux mhs-demo0 4.1.12-boot2docker #1 SMP Tue Nov 3 06:03:36 UTC 2015 x86_64 GNU/Linux

**Comment by aboch** [comment]
Thanks for reporting the issue. It's a bug and fix is coming shortly.
