### ISSUE TITLE
No multicast support in default overlay network

### ISSUE THREAD

**Issue by bergtwvd** [docker/libnetwork#754]
The default overlay network appears not to support multicast.

When I do:
 docker run --net=training2 -it bergtwvd/po TEST-1

and on the same host:
 docker run --net=training2 -it bergtwvd/po TEST-2

Then the containers do no see each other on the multicast net and they run as two independent federations.

docker@mhs-demo0:~$ docker info
Containers: 7
Images: 123
Server Version: 1.9.0
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 137
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.12-boot2docker
Operating System: Boot2Docker 1.9.0 (TCL 6.4); master : 16e4a2a - Tue Nov  3 19:49:22 UTC 2015
CPUs: 1
Total Memory: 996.2 MiB
Name: mhs-demo0
ID: 7LLO:X7J6:DBNR:NTW7:UXIB:2EIB:WX6H:FYVH:REED:CH5K:NONT:VP3U
Debug mode (server): true
 File Descriptors: 51
 Goroutines: 112
 System Time: 2015-11-14T14:20:52.761573279Z
 EventsListeners: 1
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Username: bergtwvd
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Cluster store: consul://192.168.99.100:8500
Cluster advertise: 192.168.99.101:2376
docker@mhs-demo0:~$
docker@mhs-demo0:~$ docker --version
Docker version 1.9.0, build 76d6bc9
docker@mhs-demo0:~$
docker@mhs-demo0:~$ uname -a
Linux mhs-demo0 4.1.12-boot2docker #1 SMP Tue Nov 3 06:03:36 UTC 2015 x86_64 GNU/Linux
docker@mhs-demo0:~$

**Comment by thaJeztah** [comment]
Looks like this is a duplicate of https://github.com/docker/libnetwork/issues/552

**Comment by bergtwvd** [comment]
Correct. Let's close this one and refer to #552.
