### ISSUE TITLE
Does docker daemon currently support connecting multiple network interfaces on a single host (using cluster-advertise)?

### ISSUE THREAD

**Issue by vijaykumark** [docker/libnetwork#758]
Does docker daemon support connecting to two network interfaces on a single host using cluster-advertise? We have two ethernet interfaces (eth0, eth1) on one host server which are connected to two different networks. The idea is to connect both networks to the docker containers.

Couldn't find in the docker daemon help if it is possible to mention multiple --cluster-advertise options for same docker daemon.
Tried below command /1/ to start docker daemon and it started fine but there was only one network node per host server created in zookeeper kv store /2/.  
In the below zookeeper ls output /2/, you can see three different host IPs (10.0.0.18, 10.0.0.19, 10.0.0.20). 10.0.0.1/20 subnet is connect to eth1. Docker daemon ignored the eth0 cluster-advertise option.

/1/ /usr/bin/docker daemon -H fd:// \
                     -H tcp://0.0.0.0:2375 \
                     --cluster-store=zk://10.0.0.12:2181/newnet \
                     --cluster-advertise=eth0:2376 \
                     --cluster-advertise=eth1:2377

/2/ List of nodes added after starting docker daemon.
[zk: 10.0.0.12:2181(CONNECTED) 2] ls  /newnet/docker/nodes
[10.0.0.18:2377, 10.0.0.20:2377, 10.0.0.19:2377]

By default docker libnetwork is run on top of one network interface as shown in Figure 1.
Is it possible to run as shown in Figure 2, connected to two network interfaces?
![newdockerlibnetwork](https://cloud.githubusercontent.com/assets/13167000/11496468/b8aaa3aa-981a-11e5-9ac5-a0075ecd82ff.jpg)

Does docker daemon currently support connecting multiple network interfaces? If it is not possible then is there any other way to connect multiple network interfaces on a single host?

**Comment by vijaykumark** [comment]
@mavenugo  : Is there any way to run docker libnetwork on top of two network interfaces?

**Comment by vijaykumark** [comment]
@GordonTheTurtle  There was no reply from docker developers so far. The issue is still present and we don't have a solution. It would be great if someone could resolve it.

**Comment by fcrisciani** [comment]
@vijaykumark what you are describing is not possible, what instead you can do with 2 interfaces starting from 17.06 is to separate control plane traffic from data path traffic.
This is possible using the flag `--data-path-addr` (https://docs.docker.com/engine/reference/commandline/swarm_init/#usage) during the swarm init and swarm join specifying which is the interface or IP (that identify the interface) to use for the data path traffic of the overlay network

**Comment by vijaykumark** [comment]
@fcrisciani  For clarity, is control plane traffic is between swarm manager and workers? Data path is between containers for application related traffic?
Our need is that the application running inside docker container can talk to two different interfaces.

**Comment by fcrisciani** [comment]
@vijaykumark yes, data plane traffic is only container to container, control plane is all the rest.

**Comment by deisi** [comment]
hey, I have a similar issue.
@fcrisciani you sad that what is requested is not possible. Do you mean this is currently not possible or is there an underlying reason for this being impossible to implement and this will most likely never happen?

**Comment by fcrisciani** [comment]
@deisi you can run your container in host mode and you will see the same networking that you see on the host, but there is no network isolation.
When there is a bridge in between the packets from the container have to be natted and so one interface has to be choosen

**Comment by vijaykumark** [comment]
Closing the issue as it's stale.

**Comment by jaredvacanti** [comment]
Should this work when using Docker Swarm mode and 'host-mode' publishing? From the docs "In this case, control traffic (traffic related to managing the swarm and the service) is still sent across an overlay network, but the individual swarm service containers send data using the Docker daemon’s host network and ports." 

I experience different behavior from a swarm service with host-mode publishing (listening on both`eth0` and `eth1` **does not** work) and a container run with `--network=host` (listening on both `eth0` and `eth1` **does** work).
