### ISSUE TITLE
Proposal: Add an option to disable default gateway added by libnetwork

### ISSUE THREAD

**Issue by chenchun** [docker/libnetwork#759]
Currently, when containers join an overlay network, libnetwork automatically creates a default gateway to provide external connectivity if users don't provide global gateway. But there are situations that containers don't need to visit outside networks. For our use case, `iptable_nat` module is not installed by default and if you want to use nat network, you need to consult the security team to install the module. 
So I propose to add an option to disable default gateway. If maintainers think it make sense, I'd like to make a PR.

**Comment by jc-m** [comment]
I will second that. This code:
'''
func (sb *sandbox) needDefaultGW() bool {
   var needGW bool

   for _, ep := range sb.getConnectedEndpoints() {
      if ep.endpointInGWNetwork() {
         continue
      }
      if ep.getNetwork().Type() == "null" || ep.getNetwork().Type() == "host" {
         continue
      }
      // TODO v6 needs to be handled.
      if len(ep.Gateway()) > 0 {
         return false
      }
      needGW = true
   }
   return needGW
}
'''
assumes that it fine to add a default gateway in all use case other than host and none. This is not correct as when using a remote driver, this cause many issues when the default gateway is created.

for example:
```
Error response from daemon: Cannot start container 1c5b403b5e7e1f1627f1d33598fb9d7a5b045b6ccaacaa737a6a07580121df57: [8] System error: failed to set gateway while updating gateway: file exists
```
if the content of the join response is : 
```
    respIface := &netApi.InterfaceName{
        SrcName: tempName,
        DstPrefix: "eth",
    }
    sandboxRoute := netApi.StaticRoute{
        Destination: "0.0.0.0/0",
        RouteType:     1, // CONNECTED
        NextHop:    "",
    }
    resp := &netApi.JoinResponse{
        StaticRoutes: []netApi.StaticRoute{sandboxRoute},
        InterfaceName: respIface,
    }
```
The daemon takes additional liberties if you just return:
```
    respIface := &netApi.InterfaceName{
        SrcName: tempName,
        DstPrefix: "eth",
    }
    resp := &netApi.JoinResponse{
        InterfaceName: respIface,
    }
```
in which case it creates a bridged interface anyway on the default docker network , which for a remote driver makes no sense and can cause issues.

**Comment by sanimej** [comment]
@chenchun @jc-m If the containers connected to a network backed by a remote driver should be isolated the driver can set the Gateway IP in the JoinResponse. Driver doesn't have to do any plumbing to set up the gateway. It can simply set the Geteway IP given by IPAM. If the Gateway is set for any endpoint libnetwork will not connect the container to the default gateway network.

@aboch I think we have to see why this error 'failed to set gateway while updating gateway: file exists' is seen.

**Comment by jc-m** [comment]
@sanimej The problem is that in pure L3, we don't want to have a gateway set - we use proxy arp and the gateway is set on the host by the driver / IPAM module.
I would argue that if a driver doesn't set a gateway, then, no gateway should be set, otherwise, what is the point of the remote driver ?

You should look also at https://github.com/gopher-net/ipvlan-docker-plugin/issues/6
for a simular issue with the ipvlan driver in L3 mode.
