### ISSUE TITLE
Overlay network creation error

### ISSUE THREAD

**Issue by prateekgogia** [docker/libnetwork#764]
I have two ubuntu VMs in VirtualBox. Running etcd inside docker containers in each of these VMs. I am trying to setup overlay network. I have seen this problem a few times now. When I try to create an overlay network, it gives the following error but creates the network, creating another network succeeds without any error.

root@ubuntu:~# docker network create -d overlay multi
Error response from daemon: pool configuration failed because of 100: Key not found (/newroot3/docker/network/v1.0/ipam) [99]
root@ubuntu:~# docker network create -d overlay multi1
fcf782c73314cce813ed8bcf3b79499cb31f2e440583fbd774a248b44c996846

root@ubuntu:~# docker info
Containers: 14
Images: 6
Server Version: 1.9.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 34
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.16.0-30-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 1
Total Memory: 993.7 MiB
Name: ubuntu
ID: 4SPX:46UV:JWS7:6UM4:2W4T:33EI:MN2Y:ONGL:3JJO:M5EP:OQTB:APBI
Username: prateekgogia
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Cluster store: etcd://192.168.56.10:4001/newroot3
Cluster advertise: 192.168.56.10:0

**Comment by sanimej** [comment]
@prateekgogia This is probably because the etcd running in the container is not fully up yet. As part of the network create some of the IPAM data gets written to the store. Does this happen if you try to create the network right after launching the etcd container ?

**Comment by prateekgogia** [comment]
Hi @sanimej, etcd was running and was stable much before. This time I was just trying to create a new network. Are there any logs I can collect ?

**Comment by yangdongsheng** [comment]
met the same error. Any suggestion about it?

**Comment by woshihaoren** [comment]
I am restart etcd,and delete data,then met the same error.
How can create IPMA data

**Comment by michaljrk** [comment]
Hi,

Any suggestions with this issue?
For me only re-creating entire vagrant machine helps..

**Comment by kuruoujou** [comment]
I am reaching the same issue, but my environment is a rack of about 20 or so physical nodes running CoreOS. This worked about two months ago, I left it alone, came back, and now it does not work. We did refresh the cluster in this time, but we had done that several times before with no issues. I can't create any overlay networks in the swarm. Has there been any movement on this particular issue?

**Comment by wangweihong** [comment]
met the same error too. 

kiongf@youruncloud:~/appsoar$ sudo docker network create -d overlay test1
Error response from daemon: pool configuration failed because of 100: Key not found (/docker/network/v1.0/ipam) [16]

I can get /docker/network and /docker/node key from etcd cluster inside and outside the container.

> root@3ca46eb4367c:/# etcdctl ls /docker/network/v1.0
> /docker/network/v1.0/network
> /docker/network/v1.0/endpoint

This is my environment.
> kiongf@youruncloud:~/appsoar$ sudo docker info
> Containers: 16
>  Running: 1
>  Paused: 0
>  Stopped: 15
> Images: 61
> Server Version: 1.11.2
> Storage Driver: aufs
>  Root Dir: /var/lib/docker/aufs
>  Backing Filesystem: extfs
>  Dirs: 108
>  Dirperm1 Supported: true
> Logging Driver: json-file
> Cgroup Driver: cgroupfs
> Plugins: 
>  Volume: local
>  Network: host bridge null
> Kernel Version: 4.4.0-24-generic
> Operating System: Ubuntu 16.04 LTS
> OSType: linux
> Architecture: x86_64
> CPUs: 4
> Total Memory: 7.756 GiB
> Name: youruncloud
> ID: JX2L:QY7S:7GTK:QOGL:Y6PM:JIXV:4OI6:CYGK:JYBV:SO5P:CDQR:YIMS
> Docker Root Dir: /var/lib/docker
> Debug mode (client): false
> Debug mode (server): true
>  File Descriptors: 19
>  Goroutines: 61
>  System Time: 2016-07-01T11:35:29.515400071+08:00
>  EventsListeners: 0
> Registry: https://index.docker.io/v1/
> WARNING: No swap limit support
> Cluster store: etcd://192.168.4.23:12379
> Cluster advertise: 192.168.4.23:2376
>
