### ISSUE TITLE
etcd as backend storage on remote host

### ISSUE THREAD

**Issue by prateekgogia** [docker/libnetwork#766]
I have 2 VMs running in Virtualbox and I am running the storage backend as etcd. Etcd is running in a docker container on both the hosts. When I provide the cluster store IP of host A in host B docker daemon, it doesn't connect to the etcd cluster. However, if I provide local IP to the docker daemon, it connects. Etcd in both the containers form a cluster and I don't see any error. etcd port for container is mapped to the host port. 

Scenario 1 - (Works)
HostA: 
ip:192.168.56.10
etcd container -p 4001:4001 mapped port
--Cluster store: etcd://192.168.56.10:4001/newroot
HostB:
ip: 192.169.57.2 
etcd container -p 4007:4007 mapped port
--Cluster store: etcd://192.169.57.2:4007/newroot

Scenario 2 -  (Fails)
HostA: 
ip:192.168.56.10
etcd container -p 4001:4001 mapped port
--Cluster store: etcd://192.168.56.10:4001/newroot
HostB:
ip: 192.169.57.2 
etcd container -p 4007:4007 mapped port
--Cluster store: etcd://192.168.56.10:4001/newroot  --------------<<<<<<<<<<<<<<<<<<<<
etcd cluster is formed in both the scenarios.

Is this expected ??When etcd is on remote host, we see the following error: 

ERRO[0040] discovery error: Unexpected watch error
ERRO[0060] discovery error: Unexpected watch error
ERRO[0060] Registering as "192.169.57.2:0" in discovery failed: client: etcd cluster is unavailable or misconfigured
ERRO[0080] discovery error: Unexpected watch error
ERRO[0080] Registering as "192.169.57.2:0" in discovery failed: client: etcd cluster is unavailable or misconfigured
ERRO[0100] discovery error: Unexpected watch error

**Comment by bpradipt** [comment]
This looks to be an etcd issue. I'm using libnetwork with etcd without any issues.
In your etcd config, check if ETCD_ADVERTISE_CLIENT_URLS contains http://192.168.56.10:4001

**Comment by abronan** [comment]
Indeed, most of the time issues on bootstrap come from a misconfigured `--advertise-client-urls` flag (if you used `127.0.0.1:4001` for example, this will not work).

@prateekgogia Can you please output the command or the config you used to start etcd? Thanks!
