### ISSUE TITLE
Container in the default network cannot access a mapped port from a custom network

### ISSUE THREAD

**Issue by wr0ngway** [docker/libnetwork#776]
This is with docker 1.9.1

To duplicate:

```
docker network create test
docker run -p 8888:80 --rm --name=nginx --net=test nginx

# success from host
wget -T 1 http://$(docker-machine ip default):8888/

# success from container on same network
docker run --rm --net=test busybox wget -T 1 http://$(docker-machine ip default):8888/

# timeout from container on default network
docker run --rm busybox wget -T 1 http://$(docker-machine ip default):8888/
```

The "docker-machine ip default" is the same in all three cases, and represents the docker host's ip
I'd expect that the container on the default network should still be able to access the mapped port from the test network, since from it's perspective it is just trying to reach some external ip, and that external ip/port is reachable outside the container.

If the wget container is run on a different host than the nginx one, then the connection succeeds.

Tagging @sanimej as he helped verify this as an issue on irc

**Comment by aboch** [comment]
This issue should be fixed since 1.11.x.
Can you please confirm ? Thanks.
