### ISSUE TITLE
Overlay driver runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by ghidi** [docker/libnetwork#780]
I have created a 3 containers over swarm using docker-compose with --x-networking and --x-network-driver overlay. The containers are created correctly but when I try to restart a container, the docker daemon fails with the following exception:

2015/11/26 19:12:05 http: panic serving 172.17.0.2:54605: runtime error: invalid memory address or nil pointer dereference
goroutine 1059 [running]:
net/http.func·011()
    /usr/local/go/src/net/http/server.go:1130 +0xbb
github.com/docker/libnetwork/drivers/overlay.(_driver).Join(0xc2084f2aa0, 0xc20890f3c0, 0x40, 0xc20890fb40, 0x40, 0xc208aabb60, 0x22, 0x7f569deaac90, 0xc208b3f7a0, 0x0, ...)
    /go/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/drivers/overlay/joinleave.go:70 +0xc72
github.com/docker/libnetwork.(_endpoint).sbJoin(0xc208b3f7a0, 0x7f569deaac28, 0xc2096fc4e0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /go/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/endpoint.go:376 +0x9c9
github.com/docker/libnetwork.(_endpoint).Join(0xc208e38bd0, 0x7f569deaac28, 0xc2096fc4e0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /go/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/endpoint.go:324 +0x1a8
github.com/docker/docker/daemon.(_Container).connectToNetwork(0xc208823000, 0xc208b281c8, 0x4, 0x0, 0x0, 0x0)
    /go/src/github.com/docker/docker/daemon/container_unix.go:1059 +0x885
github.com/docker/docker/daemon.(_Container).allocateNetwork(0xc208823000, 0x0, 0x0)
    /go/src/github.com/docker/docker/daemon/container_unix.go:956 +0x574
github.com/docker/docker/daemon.(_Container).initializeNetworking(0xc208823000, 0x0, 0x0)
    /go/src/github.com/docker/docker/daemon/container_unix.go:1101 +0x4c6
github.com/docker/docker/daemon.(_Container).Start(0xc208823000, 0x0, 0x0)
    /go/src/github.com/docker/docker/daemon/container.go:297 +0x236
github.com/docker/docker/daemon.(_Daemon).ContainerStart(0xc20862dcc0, 0xc20899dcf7, 0x40, 0x0, 0x0, 0x0)
    /go/src/github.com/docker/docker/daemon/start.go:47 +0x24f
github.com/docker/docker/api/server/router/local.(_router).postContainersStart(0xc2088aaf80, 0x7f569df1a310, 0xc208c58510, 0x7f569df1a2d8, 0xc2085a37c0, 0xc208f34d00, 0xc208c58390, 0x0, 0x0)
    /go/src/github.com/docker/docker/api/server/router/local/container.go:192 +0x162
github.com/docker/docker/api/server/router/local._router.(github.com/docker/docker/api/server/router/local.postContainersStart)·fm(0x7f569df1a310, 0xc208c58510, 0x7f569df1a2d8, 0xc2085a37c0, 0xc208f34
d00, 0xc208c58390, 0x0, 0x0)
    /go/src/github.com/docker/docker/api/server/router/local/local.go:134 +0x7b
github.com/docker/docker/api/server.func·004(0x7f569df1a310, 0xc208c58510, 0x7f569df1a2d8, 0xc2085a37c0, 0xc208f34d00, 0xc208c58390, 0x0, 0x0)
    /go/src/github.com/docker/docker/api/server/middleware.go:87 +0x7c7
github.com/docker/docker/api/server.func·003(0x7f56a00eba50, 0xc20802afd0, 0x7f569df1a2d8, 0xc2085a37c0, 0xc208f34d00, 0xc208c58390, 0x0, 0x0)
    /go/src/github.com/docker/docker/api/server/middleware.go:66 +0x10e
github.com/docker/docker/api/server.func·002(0x7f56a00eba50, 0xc20802afd0, 0x7f569df1a2d8, 0xc2085a37c0, 0xc208f34d00, 0xc208c58390, 0x0, 0x0)
    /go/src/github.com/docker/docker/api/server/middleware.go:49 +0x47c
github.com/docker/docker/api/server.func·001(0x7f56a00eba50, 0xc20802afd0, 0x7f569df1a2d8, 0xc2085a37c0, 0xc208f34d00, 0xc208c58390, 0x0, 0x0)
    /go/src/github.com/docker/docker/api/server/middleware.go:27 +0x1dc
github.com/docker/docker/api/server.func·007(0x7f569df1a2d8, 0xc2085a37c0, 0xc208f34d00)
    /go/src/github.com/docker/docker/api/server/server.go:156 +0x265
net/http.HandlerFunc.ServeHTTP(0xc2086e45a0, 0x7f569df1a2d8, 0xc2085a37c0, 0xc208f34d00)
    /usr/local/go/src/net/http/server.go:1265 +0x41
github.com/gorilla/mux.(_Router).ServeHTTP(0xc2085759a0, 0x7f569df1a2d8, 0xc2085a37c0, 0xc208f34d00)
    /go/src/github.com/docker/docker/vendor/src/github.com/gorilla/mux/mux.go:98 +0x297
net/http.serverHandler.ServeHTTP(0xc2088a35c0, 0x7f569df1a2d8, 0xc2085a37c0, 0xc208f34d00)
    /usr/local/go/src/net/http/server.go:1703 +0x19a
net/http.(_conn).serve(0xc208f203c0)
    /usr/local/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
    /usr/local/go/src/net/http/server.go:1751 +0x35e

I am using docker 1.9.1 with VirtualBox on OSX 10.11

**Comment by aboch** [comment]
@ghidi 
Can you please check if you are hitting the same issue of https://github.com/docker/docker/issues/14145 
if the solution works for you as well ?

**Comment by ghidi** [comment]
I am using 4.1.13-boot2docker so I am not sure it is related to kernel version. I will try to create a scenario so you can reproduce it.

**Comment by ghidi** [comment]
Here is a scenario that fails on my laptop.

```bash
#Key-value store for overlay networking
docker-machine create -d virtualbox blsw-keystore
docker $(docker-machine config blsw-keystore) run \
    -d -p "8500:8500" -h "consul" \
    progrium/consul \
    -server -bootstrap

# Docker Swarm master
docker-machine create -d virtualbox \
    --swarm --swarm-image="swarm" --swarm-master \
    --swarm-discovery="consul://$(docker-machine ip blsw-keystore):8500" \
    --engine-opt="cluster-store=consul://$(docker-machine ip blsw-keystore):8500" \
    --engine-opt="cluster-advertise=eth1:2376" \
    --engine-label="blu.hdfs.role=namenode" \
    blsw-master

# Docker Swarm nodes
for i in {0..1}
do
    docker-machine create -d virtualbox \
        --swarm --swarm-image="swarm" \
        --swarm-discovery="consul://$(docker-machine ip blsw-keystore):8500" \
        --engine-opt="cluster-store=consul://$(docker-machine ip blsw-keystore):8500" \
        --engine-opt="cluster-advertise=eth1:2376" \
        --engine-label="blu.hdfs.role=datanode" \
        blsw-node-$(printf %02d ${i})
done

# Point Docker to Swarm master
eval $(docker-machine env --swarm blsw-master)
```

Create a docker-compose.yml file inside a directory called ’hdfs’ with the following content
```yaml
namenode_data:
  image: busybox
  command: /bin/true
  volumes:
    - /var/lib/hadoop/dfs/name
  environment:
    - "constraint:blu.hdfs.role==namenode"

namenode_logs:
  image: busybox
  command: /bin/true
  volumes:
    - /var/log/hadoop
  environment:
    - "constraint:blu.hdfs.role==namenode"

namenode_daemon:
  image: ghidi/hdfs
  command: hdfs namenode
  volumes_from:
    - namenode_data
    - namenode_logs
  environment:
    - "constraint:blu.hdfs.role==namenode"
  ports:
    - "50070:50070"
    - "8020:0820"
```

Format the HDFS (this will succed)
```bash
docker-compose --x-networking --x-network-driver overlay run --rm namenode_daemon hdfs namenode -format
```
Creating network "hdfs" with driver "overlay"
Pulling namenode_daemon (ghidi/hdfs:latest)...
blsw-node-00: Pulling ghidi/hdfs:latest... : downloaded
blsw-master: Pulling ghidi/hdfs:latest... : downloaded
Pulling namenode_data (busybox:latest)...
blsw-node-00: Pulling busybox:latest... : downloaded
blsw-master: Pulling busybox:latest... : downloaded
Creating hdfs_namenode_data_1
Creating hdfs_namenode_logs_1
Formatting using clusterid: CID-28e61fc8-7c2a-41c8-ab34-117484746f57

Start the namenode (this will fail)
```bash
docker-compose --x-networking --x-network-driver overlay up -d
```

Starting hdfs_namenode_logs_1
Starting hdfs_namenode_data_1
ERROR: Post https://192.168.99.171:2376/v1.21/containers/3210af7e786727756376101b9cd8e341258a58c7541f853baa053c1b75ac2735/start: EOF

192.168.99.171 is Swarm master

SSH to Swarm master and cat the docker file
```bash
docker-machine ssh blsw-master cat /var/log/docker.log
```

time="2015-12-06T17:21:25.965254209Z" level=debug msg="Assigning addresses for endpoint hdfs_namenode_data_1's interface on network hdfs"
time="2015-12-06T17:21:25.965299965Z" level=debug msg="RequestAddress(GlobalDefault/10.0.0.0/24, <nil>, map[])"
time="2015-12-06T17:21:25.968693910Z" level=debug msg="Assigning addresses for endpoint hdfs_namenode_data_1's interface on network hdfs"
time="2015-12-06T17:21:26.009287487Z" level=debug msg="Received user event name:jl 192.168.99.171 dedb2646fb55464f8cc9e9b82a3ba73a5d6021d179945e2539991f698c783475 3449eb505ef254e02f1ca1c2239a6a437c6d944f2a8416c5a72de8c301105dfd, payload:leave 10.0.0.2 255.255.255.0 02:42:0a:00:00:02\n"
time="2015-12-06T17:21:26.009544758Z" level=debug msg="Parsed data = dedb2646fb55464f8cc9e9b82a3ba73a5d6021d179945e2539991f698c783475/3449eb505ef254e02f1ca1c2239a6a437c6d944f2a8416c5a72de8c301105dfd/192.168.99.171/10.0.0.2/255.255.255.0/02:42:0a:00:00:02\n"
2015/12/06 17:21:26 http: panic serving 172.17.0.2:44521: runtime error: invalid memory address or nil pointer dereference
goroutine 963 [running]:
net/http.func·011()
	/usr/local/go/src/net/http/server.go:1130 +0xbb
github.com/docker/libnetwork/drivers/overlay.(*driver).Join(0xc2088bb220, 0xc208588640, 0x40, 0xc2085889c0, 0x40, 0xc2089e9b60, 0x22, 0x7efdd6743280, 0xc208df2ea0, 0x0, ...)
	/go/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/drivers/overlay/joinleave.go:70 +0xc72
github.com/docker/libnetwork.(*endpoint).sbJoin(0xc208df2ea0, 0x7efdd67430b0, 0xc208f60d00, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/endpoint.go:376 +0x9c9
github.com/docker/libnetwork.(*endpoint).Join(0xc208dcebd0, 0x7efdd67430b0, 0xc208f60d00, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/endpoint.go:324 +0x1a8
github.com/docker/docker/daemon.(*Container).connectToNetwork(0xc209127000, 0xc208a50208, 0x4, 0xc208ee9101, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/container_unix.go:1059 +0x885
github.com/docker/docker/daemon.(*Container).allocateNetwork(0xc209127000, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/container_unix.go:956 +0x574
github.com/docker/docker/daemon.(*Container).initializeNetworking(0xc209127000, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/container_unix.go:1101 +0x4c6
github.com/docker/docker/daemon.(*Container).Start(0xc209127000, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/container.go:297 +0x236
github.com/docker/docker/daemon.(*Daemon).ContainerStart(0xc208662b40, 0xc2089c36d7, 0x40, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/start.go:47 +0x24f
github.com/docker/docker/api/server/router/local.(*router).postContainersStart(0xc2088b8160, 0x7efdd6fb1f08, 0xc208b05a40, 0x7efdd6fb1ed0, 0xc208b69ea0, 0xc208eec410, 0xc208b05560, 0x0, 0x0)
	/go/src/github.com/docker/docker/api/server/router/local/container.go:192 +0x162
github.com/docker/docker/api/server/router/local.*router.(github.com/docker/docker/api/server/router/local.postContainersStart)·fm(0x7efdd6fb1f08, 0xc208b05a40, 0x7efdd6fb1ed0, 0xc208b69ea0, 0xc208eec410, 0xc208b05560, 0x0, 0x0)
	/go/src/github.com/docker/docker/api/server/router/local/local.go:134 +0x7b
github.com/docker/docker/api/server.func·004(0x7efdd6fb1f08, 0xc208b05a40, 0x7efdd6fb1ed0, 0xc208b69ea0, 0xc208eec410, 0xc208b05560, 0x0, 0x0)
	/go/src/github.com/docker/docker/api/server/middleware.go:87 +0x7c7
github.com/docker/docker/api/server.func·003(0x7efddd99ba50, 0xc20802afd0, 0x7efdd6fb1ed0, 0xc208b69ea0, 0xc208eec410, 0xc208b05560, 0x0, 0x0)
	/go/src/github.com/docker/docker/api/server/middleware.go:66 +0x10e
github.com/docker/docker/api/server.func·002(0x7efddd99ba50, 0xc20802afd0, 0x7efdd6fb1ed0, 0xc208b69ea0, 0xc208eec410, 0xc208b05560, 0x0, 0x0)
	/go/src/github.com/docker/docker/api/server/middleware.go:49 +0x47c
github.com/docker/docker/api/server.func·001(0x7efddd99ba50, 0xc20802afd0, 0x7efdd6fb1ed0, 0xc208b69ea0, 0xc208eec410, 0xc208b05560, 0x0, 0x0)
	/go/src/github.com/docker/docker/api/server/middleware.go:27 +0x1dc
github.com/docker/docker/api/server.func·007(0x7efdd6fb1ed0, 0xc208b69ea0, 0xc208eec410)
	/go/src/github.com/docker/docker/api/server/server.go:156 +0x265
net/http.HandlerFunc.ServeHTTP(0xc2086ed460, 0x7efdd6fb1ed0, 0xc208b69ea0, 0xc208eec410)
	/usr/local/go/src/net/http/server.go:1265 +0x41
github.com/gorilla/mux.(*Router).ServeHTTP(0xc208587ea0, 0x7efdd6fb1ed0, 0xc208b69ea0, 0xc208eec410)
	/go/src/github.com/docker/docker/vendor/src/github.com/gorilla/mux/mux.go:98 +0x297
net/http.serverHandler.ServeHTTP(0xc2088afaa0, 0x7efdd6fb1ed0, 0xc208b69ea0, 0xc208eec410)
	/usr/local/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc208045360)
	/usr/local/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1751 +0x35e
