### ISSUE TITLE
Question on eth1 of container even with other Network Driver specified

### ISSUE THREAD

**Issue by kingbirdzheng** [docker/libnetwork#781]
#### Issue Description and Help Needed
I found an issue that every container has one more interface (eth1 with IP address assigned by Bridge driver) than expected when I implements a Libnetwork remote driver. 
I need help on 
- What's the background info of having this interface?
- How to create container without this interface?

#### Detailed info
<code>docker --version</code>
Docker version 1.9.0-dev, build ccf5b60, experimental

container create command:
<code>docker run -itd --net=ericNet --name=con-1 busybox</code>

When I attach to the container, I found 3 interfaces while eth1 is not expected.

/ # ifconfig
eric-0    Link encap:Ethernet  HWaddr B6:0D:E8:63:A3:6D  
          inet addr:10.0.0.2  Bcast:0.0.0.0  Mask:255.255.255.0
          inet6 addr: fe80::b40d:e8ff:fe63:a36d/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:33 errors:0 dropped:0 overruns:0 frame:0
          TX packets:11 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:7065 (6.8 KiB)  TX bytes:1158 (1.1 KiB)

eth1      Link encap:Ethernet  HWaddr 02:42:AC:12:00:21  
          inet addr:172.18.0.33  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::42:acff:fe12:21/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:25 errors:0 dropped:0 overruns:0 frame:0
          TX packets:8 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:4261 (4.1 KiB)  TX bytes:648 (648.0 B)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

**Comment by jc-m** [comment]
it may be related to https://github.com/docker/libnetwork/issues/775

**Comment by aboch** [comment]
@kingbirdzheng 
This is by design, please check at the end of Join section at
https://github.com/docker/libnetwork/blob/master/docs/remote.md

Alternatively your driver can explicitly ask libnetwork to not provide any assistance for the external connectivity (See #775 and its resolution in #778 as pointed out by @jc-m ). This option is not yet documented in the doc above.

Let us know if more clarification is needed or if we can close this issue.
Thanks.

**Comment by kingbirdzheng** [comment]
@aboch 
Thanks for the info. I am closing this issue.
