### ISSUE TITLE
Docker container not resolved to the appropriate ip address

### ISSUE THREAD

**Issue by dzlab** [docker/libnetwork#783]
I've an application composed of a kafka producer and another kafka consumer. I'm trying to deploy it on a Docker swarm on AWS with mutli-host networking enabled. Kafka container is created by the following docker-compose.yml file:

```
kafka:
  image: spotify/kafka
  environment:
    ADVERTISED_PORT: 9092
  ports:
    - "2181:2181"
    - "9092:9092"
```

This is how I run the containers for the different components:

```
> docker-compose -f helloworld_kafka.yml --x-networking up -d
Creating network "helloworld"
...
> docker run -d --name helloworld_producer_1 --net helloworld -it elsoufy/myimage ./myexec -role producer -queue helloworld_kafka_1:9092
> docker run -d --name helloworld_consumer_1 --net helloworld -it elsoufy/myimage ./myexec -role consumer -queue helloworld_kafka_1:9092
```

When I check the `/etc/hosts` of `helloworld_kafka_1` I found entries for both helloworld_server_1 and helloworld_consumer_1:

```
10.0.0.2    kafka_container_id
127.0.0.1   localhost
::1 localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
10.0.0.3    helloworld_server_1
10.0.0.3    helloworld_server_1.helloworld
10.0.0.4    helloworld_consumer_1
10.0.0.4    helloworld_consumer_1.helloworld
```

But when I check the logs of the latter I realize that they failed to connect to kafka. I see the following:

```
> docker logs consumer_container_id
2015/11/27 16:05:52 Kafka brokers: helloworld_kafka_1:9092
2015/11/27 16:05:52 Failed to start consuming dial tcp: lookup kafka_container_id on 10.10.0.2:53: no such host
```

It looks like When `10.10.0.2` is the DNS (port 53) used by containers to resolve name and that it's not reachable. When I inspect the network of any nodes I cannot find this address, and it's not in the range of the helloworld overlay network (This address is part of my AWS VPC). How I can make this DNS reachable? any suggestion is appreciated.

**Comment by dzlab** [comment]
@abronan i'm not using links, it's a DNS problem, why this issue is closed??

**Comment by yaxinlx** [comment]
same problem here. "dial tcp: lookup ce328c91cbf4 on 172.31.0.2:53: no such host"

**Comment by pdevine** [comment]
This seems to be a timing issue.

I just ran in to the exact same problem: "dial tcp: lookup dtr-etcd-73aa19d1bd89.dtr-ol on 192.168.36.2:53: no such host".  When I added a 5 second sleep before trying to access the host everything worked fine.

**Comment by dzlab** [comment]
thanks @pdevine for the hint, but where exactly should the timing be added?
