### ISSUE TITLE
Proposal : TTL based stale endpoint expiry 

### ISSUE THREAD

**Issue by mavenugo** [docker/libnetwork#786]
Libnetwork cleans up stale endpoint when docker daemon comes up after an ungraceful shutdown. It works fairly well for local network drivers. When the stale endpoints are removed, `network` can be effectively removed if there are no active containers connected to that network.
For global network driver, when a docker daemon goes down ungracefully and if the user never brings the daemon back up again, the endpoints remain stale in the kv-store preventing the ability to remove the network.

The proposal is to expire the stale endpoints using libkv TTL mechanism.

**Comment by abdasgupta** [comment]
So is the idea to use delete function from a particular backend of libkv to remove the stale endpoint from kv store??
