### ISSUE TITLE
IPsec capabilities?

### ISSUE THREAD

**Issue by pierreozoux** [docker/libnetwork#787]
Posting from https://github.com/docker/swarm/issues/1458#issuecomment-160414868

I just saw the new nice feature of cross host linking. This is nice, but if you want to do a cross IaaS provider setup (like in this [video](https://youtu.be/3I6hWb24_qE)), I don't see the point without a VPN.
My question is: is there any plan to support this kind of feature? (In the previous post, somebody said it was plan for 1.1?)

Thanks :)

**Comment by mavenugo** [comment]
@pierreozoux this is really a good feature to have, but currently this is not targeted for 1.10 release. But, if you or others are willing to help implement the feature, we can help in all possible ways to make this happen.

**Comment by pierreozoux** [comment]
@mavenugo thanks for your comment!
Do you have a rough idea of when?

I'd love to help of course, but I'm more an ops than a dev, so I could help testing but not much more :)
In the mean time, I'll play with tinc configured with etcd, will see how it goes :)

**Comment by mavenugo** [comment]
@pierreozoux can you try running the overlay network with a manual ipsec configuration (http://lartc.org/howto/lartc.ipsec.html) and confirm if you could run a multi-host docker overlay network running securely on top of your ipsec tunnels ?

**Comment by prateekgogia** [comment]
Hi @mavenugo, 
I tried overlay with ipsec configured on ubuntu. Whenever I try to send anything from one host to another it is encrypted. However, when I try to ping from one container to another using overlay networking, vxlan packets are not getting encrypted. Following is a snippet from tcpdump:

08:17:34.577297 IP 172.31.128.228.38220 > 172.31.129.167.4789: VXLAN, flags [I] (0x08), vni 256
IP 10.0.1.2 > 10.0.1.3: ICMP echo request, id 15, seq 9, length 64

This is captured on the destination host and this host drops any traffic from the sender IP 172.31.128.228, if it is unencrypted. I am guessing it has to do something with IPtables on both the hosts.
Is it possible that I am hitting this bug: #430 ? Any pointers what I should try ?

**Comment by aboch** [comment]
Closed by #1199
