### ISSUE TITLE
via remote driver creates one network: admin, start a container with network admin, but got two IP, one is from admin, other is from a bridge which is automatically created

### ISSUE THREAD

**Issue by yangzhares** [docker/libnetwork#797]
as title, i create a network: admin via remote driver, and start a container(docker run --rm -ti --net=admin busybox sh) with network admin, but got two IP, one is from admin, other is from a bridge which is automatically created by system. in fact, i want to get only one IP which should be from admin, how can avoid this?

============================
~ # ifconfig
eth0      Link encap:Ethernet  HWaddr FA:16:3E:A7:D6:70
          inet addr:10.0.0.2  Bcast:0.0.0.0  Mask:255.255.255.0
          inet6 addr: fe80::f816:3eff:fea7:d670/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:13 errors:0 dropped:0 overruns:0 frame:0
          TX packets:11 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:1038 (1.0 KiB)  TX bytes:858 (858.0 B)

eth1      Link encap:Ethernet  HWaddr 02:42:AC:12:00:02
          inet addr:172.18.0.2  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::42:acff:fe12:2/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:15 errors:0 dropped:0 overruns:0 frame:0
          TX packets:8 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:1170 (1.1 KiB)  TX bytes:648 (648.0 B)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

**Comment by chenchun** [comment]
Libnetwork is about to providing an `DisableGatewayService` option in `JoinResponse` to disable default gateway bridge network, you can take at https://github.com/docker/libnetwork/pull/778

**Comment by yangzhares** [comment]
cool
