### ISSUE TITLE
Support to let remote driver generate the network id

### ISSUE THREAD

**Issue by yeasy** [docker/libnetwork#805]
Currently, the create network API (POST to `/NetworkDriver.CreateNetwork`) set a unique network id generated by libnetwork.

Can it support leaving this field empty, while in this case will mean to let the backend driver generate and reply?

In some scenario, this is quite useful, as the backend driver may maintain its own network information base. E.g., in OpenStack Neutron, there is already a network id, it will be very complicated to let both side manage their special network id name space. On the other hand, from the aim of the libnetwork, it should support sync the network information between the docker side and the underly driver side.

I would like to write some proposal if people like this feature.

Please feel free to correct me if I miss something.

Thanks!

**Comment by jainvipin** [comment]
@yeasy

I am trying to grok the `very complicated` part of two entities maintaining their own ids and map back and forth - especially if the life-cycle events of libnetwork's network and orchestration entity's network are different.

I have implemented this mapping for my driver and so I ask.

**Comment by yeasy** [comment]
@jainvipin sure, it is already implemented by holding the mapping information.
Wanna say there could be more simple and scale way.
How do u think?

**Comment by jainvipin** [comment]
@yeasy - well, I can't speak for the libnetwork maintainers but keeping them independent and separate is better IMO, because the life-cycle of the two entities (even if they are mapped 1:1) is different.

Also note that if making your plugin simpler/scalable makes libnetwork proportionately complicated, then overall complexity is not always reduced, nor did we make the scale better.

**Comment by yeasy** [comment]
Since the inactive discussion, let's close it first.

Anyone interested, pls feel free to re-open.  Thanks!
