### ISSUE TITLE
Specifying NICs per network

### ISSUE THREAD

**Issue by rgbkrk** [docker/libnetwork#806]
Is there a way to specify what NICs to provide to a new Docker network?

**Comment by dave-tucker** [comment]
Could you be a little more specific?
Neither the `bridge` or `overlay` drivers bind to any NICs
If you are writing your own driver that does (e.g for VLANs etc...) you can provide options at network creation time.

For example, assuming your driver is called "vlan":

`docker network create -d vlan -o vlan_id=2 -o iface=eth1` netvlan2`

**Comment by jainvipin** [comment]
@rgbkrk - it would be good to know the use case you have in mind. The ones I am aware of are:
- allow specifying vtep to be used for an ovleray (thus a NIC, rather its IP as vtep IP)
- allow specific nic to create a physically isolated underlay for containers than the rest (note that for overlays it would amount to same thing as using a user specified VTEP)
- allow specific nic to leverage its capabilities (speed, offload, etc)

**Comment by rgbkrk** [comment]
I must be greatly missing something in configuration and in wording. I'll try to give it a go here.

I'd like to be able to run a container where it binds to a specific interface rather than all of them.

Let's say these are my interfaces (which, well, they are):

```
bond0     Link encap:Ethernet  HWaddr a0:36:9f:2c:e7:09
          inet6 addr: fe80::a236:9fff:fe2c:e709/64 Scope:Link
          UP BROADCAST RUNNING MASTER MULTICAST  MTU:1500  Metric:1
          RX packets:52322251301 errors:0 dropped:0 overruns:0 frame:0
          TX packets:284286399 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:45291273986040 (45.2 TB)  TX bytes:290919089819 (290.9 GB)

bond0.101 Link encap:Ethernet  HWaddr a0:36:9f:2c:e7:09
          inet addr:104.130.18.111  Bcast:104.130.18.255  Mask:255.255.255.0
          inet6 addr: fe80::a236:9fff:fe2c:e709/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:3662593442 errors:0 dropped:1 overruns:0 frame:0
          TX packets:175239529 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:2137680204169 (2.1 TB)  TX bytes:282699708939 (282.6 GB)

bond0.401 Link encap:Ethernet  HWaddr a0:36:9f:2c:e7:08
          inet addr:10.184.13.252  Bcast:10.184.15.255  Mask:255.255.240.0
          inet6 addr: fe80::a236:9fff:fe2c:e708/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:39377240753 errors:0 dropped:17 overruns:0 frame:0
          TX packets:9369941 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:41938737951075 (41.9 TB)  TX bytes:2299396900 (2.2 GB)
```

and that I want to bind port 443 on address 10.184.13.252 / interface bond0.401. I'm unsure of how to do this without using either `--net=host` or offering on all interfaces.

**Comment by rgbkrk** [comment]
> Neither the bridge or overlay drivers bind to any NICs

Pardon my ignorance, does this mean they bind to all NICs?

> If you are writing your own driver that does (e.g for VLANs etc...) you can provide options at network creation time.

> docker network create -d vlan -o vlan_id=2 -o iface=eth1 netvlan2`

I'm definitely not writing my own driver here, but this certainly seems like the syntax I'd want for setting such a thing.

**Comment by dave-tucker** [comment]
@rgbkrk I think what you are looking for is [here](https://docs.docker.com/engine/reference/run/#expose-incoming-ports)

Specifically the `ip:hostPort:containerPort` variant:
`docker run -p 10.184.13.252:443:443`

**Comment by rgbkrk** [comment]
Ah, ok. Makes perfect sense. I just have to query using `ip addr show bond0.401`, `grep` for the address, and use that in the `docker run` command.

**Comment by rgbkrk** [comment]
Thank you very much for taking the time to help me @dave-tucker, I'll make sure to help others to gift that forward. :smile:
