### ISSUE TITLE
Libnetwork to provide inbuilt Null IPAM driver

### ISSUE THREAD

**Issue by aboch** [docker/libnetwork#809]
The Request/Release Pool and Request/Release Address APIs always succeeds on a null ipam driver.

Until this is ready, users can rely on any external ipam driver plugin which provides the above behavior.

**Comment by chenchun** [comment]
@aboch Can I work on this one ? I've written a vlan network plugin and wish libnetwork could provide a null ipam to give others the ability to manage IP assignment.

**Comment by aboch** [comment]
@chenchun Please go ahead, thanks. 
FYI, I wrote an implementation for this sometime back: https://github.com/aboch/libnetwork_new/commit/743070c9b9e4eb3e0ba52aa962c1fdaf774921a8, but did not push it. You may want to take a look at it, if something can be reused.
