### ISSUE TITLE
Plans for vendoring

### ISSUE THREAD

**Issue by rosenhouse** [docker/libnetwork#832]
Hi,

We would like to use libnetwork with the new [`vendor` support](https://docs.google.com/document/d/1Bz5-UB7g2uPBdOx-rw5t9MxJwkfpx90cqG9AFL0JAYo/edit).  It is experimental as of Go 1.5 and will be [on-by-default in Go 1.6](https://tip.golang.org/cmd/go/#hdr-Vendor_Directories).

We've tried this locally and it appears to work, with these changes:
- move the `Godeps/_workspace/src` directory to `vendor`
- `export GO15VENDOREXPERIMENT=1`
- build with Go 1.5

Are there plans to upgrade to Go 1.5?  Are there plans to switch to the `GO15VENDOREXPERIMENT`?

Thank you.

cc: @dbellotti

**Comment by dave-tucker** [comment]
Personally, I'd be :+1: in moving to the new `vendor` model.
The biggest point of debate will be what tool to use to manage the `vendor` directory.

While `godep` will continue to work, there are some awesome tools out there like [`glide`](https://github.com/Masterminds/glide) that seem to provide a much better workflow.

@mrjana, have you had a chance to look at the experimental Go 1.5 vendoring yet?

**Comment by rosenhouse** [comment]
It's worth noting that `Godep` supports the new vendor experiment, via the same environment variable, so no tool change is necessary:
   https://github.com/tools/godep#go-15-vendor-experiment

If people want to migrate to a different tool, that's great, but would be a different issue.

**Comment by dave-tucker** [comment]
My preliminary testing showed that `./...` with the vendor experiment will include every vendored package. That means we have to replace every occurrence with something like `$(go list ./... | grep -v vendor)` :panda_face:

**Comment by rosenhouse** [comment]
Looks like this is done :-)
