### ISSUE TITLE
Proposal: Add API to check the health of remote drivers 

### ISSUE THREAD

**Issue by aaithal** [docker/libnetwork#844]
# Introduction

Remote network drivers in Libnetwork are stand-alone processes listening to `POST` requests on `.sock` files. The [remote network driver design document](https://github.com/docker/libnetwork/blob/master/docs/remote.md) exposes a set of APIs and endpoints for the same. In a production system, it is critical to monitor the health of the driver. However, there is no API support for doing this today. Having such a capability is critical for remedying and restoring the driver.
# Overview of the Solution

A crude way to determine the health of the remote driver on a Linux host would be to create a nanny process to monitor the state of the driver process using the process id. But, such a setup lacks the ability to determine if the driver has reached a terminal state and can not recover any more.

Hence, the proposal is to extend the remote network driver API by adding a new `GetHealth()` API.

The remote driver will receive another POST message to the URL `/NetworkDriver.GetHealth` with no payload. A success response is empty (with a HTTP response code of 200):

```
{}
```

An unhealthy driver can choose to respond with a non-200 response code and may optionally include a reason in the response body.

The `driverapi.Driver` type needs to be extended with a new `GetHealth()` API to support this. Also, the `network.Network` struct can choose to expose this information to consumers of `libnetwork`, such as the docker daemon. Eventually, the daemon can choose to expose this information to its users via commands such as `docker network health bridge`.

Thoughts?

**Comment by jainvipin** [comment]
I am not sure what could libnetwork do about restoring a driver that becomes unresponsive. Note that it was not libnetwork that started the driver in the beginning. Along those lines, I'd argue that the entity that started the driver be responsible for doing the health-check

> Having such a capability is critical for remedying and restoring the driver

**Comment by aaithal** [comment]
@jainvipin I agree. It's not the intent that libnetwork perform any actions when the driver is deemed unhealthy, nor that it should be doing the health check. Rather, that all drivers should expose a `/NetworkDriver.GetHealth` endpoint (or something similar) so that processes managing/monitoring such drivers have a standard way of querying for health. 

For example, if an application deployed in cloud environment is dependent on a docker network for its network configuration, and if the docker network is supported by a remote driver, having health check semantics makes managing such applications really simple, as VMs with unhealthy drivers can be targeted for termination/restart etc. Now, in a world where you allow  applications to bring in their own drivers, managing them becomes unfeasible if each driver has it's own health check semantics. Driver 'A' can choose to publish its health on the local host port 9000, Driver 'B' 9001 and so on.
