### ISSUE TITLE
Proposal: Use IPVS instead of iptables/userland proxy

### ISSUE THREAD

**Issue by cpuguy83** [docker/libnetwork#852]
IPVS is fast and has been part of the kernel since forever.
It would be cool if we could use it instead of iptables (and the userland proxy).
This may also resolve issues seen with hairpin nat on iptables.

See https://github.com/kobolog/gorb as a working daemon that uses ipvs for load balancing...
We'd use it like this except there's only one backend.
This could potentially be utilized when there is some service level concept as well.

**Comment by qoke** [comment]
You may want to contribute to this thread as well... https://github.com/kubernetes/kubernetes/issues/17470

Kubernetes desperately needs IPVS support, the user land proxy only works for TCP (and slowly compared to IPVS). We seem to all be rolling our own IPVS solutions for Docker/K8S now,

**Comment by thockin** [comment]
@qoke The kubernetes proxy in iptables works really well for just about every use case we have seen so far.  That's not to say I don't think IPVS will be possibly better, but nobody is suffering.  I don't know where you get "the user land proxy only works for TCP" :)

**Comment by ligc** [comment]
@cpuguy83 HI, the IPVS load balancing with Docker is cool,  is there any additional documentation that describes the internals of IPVS with Docker? 

I want to evaluate/benchmark how the Docker IPVS scales,  if we have a lot of swarm workers, what the Docker IPVS performance overhead will be? Do you have any existing data that could share with us? If not, I could run the benchmark and post to the community.

Here are my thoughts about the test case, your comments and suggestions will be appreciated.
1. Use a http service like apache2
2. Start with 1 worker in the swarm
3. Deploy the service with **--publish 80** and **--replicas 1**
4. run httpperf against the **\<swarm_manager_ip\>:30000** to stress the service (is this right?)
5. Add more workers into the swarm, and update the service with **docker service scale \<servicename\>=\<number of workers\>**
6. Run httpperf against **\<swarm_manager_ip\>:30000** again and again with different numbers of workers and service replicas

Thank you

**Comment by cpuguy83** [comment]
Closing since in the end this will introduce a lot of edge cases and will most certainly break some existing users.
