### ISSUE TITLE
Proposal: Enhancements to IPAM API

### ISSUE THREAD

**Issue by johnbelamaric** [docker/libnetwork#864]
I have been looking at the IPAM API with respect to integrating with Infoblox IPAM. There are a few enhancements that would be nice to see:

1) Inform IPAM of external port mappings. The idea here is to enable tracking of the external IP associated with a given container at a given point in time. IPAM here wouldn't really be providing any assignment of IPs, but rather just allowing the tracking of these associations within an external IPAM database. It can also be used as a hook for creating DNS entries in the organization-wide DNS.

2) Extend the first point to actually request an available _external_ IP for use by a container, assuming the host has many IPs. Something like "-p available:80:80" - delegate to the IPAM driver what IP is "available". Of course the first point is necessary for this so when the container goes away the IP is released.

3) Enable the passing of key-value pairs from the command line into the IPAM driver at the time of network creation.

4) At container run, enable the selection of a network by passing in key/value pairs rather than explicitly choosing the network. The IPAM driver would use those key/value pairs to locate a specific, matching network.

I imagine 1, 2, and 4 would all be optional driver capabilities.

John

**Comment by aboch** [comment]
@johnbelamaric 
Thanks for the proposal.

Regarding
> 3) Enable the passing of key-value pairs from the command line into the IPAM driver at the time of network creation.

This functionality is being added by @rmb938 in https://github.com/docker/docker/pull/17316
PTAL

**Comment by johnbelamaric** [comment]
Awesome, thanks.

**Comment by bboreham** [comment]
In 4), by "network" did you mean a thing created via `docker network create`, or an IP network like 10.0.0.0/8, or something else?

**Comment by johnbelamaric** [comment]
I did mean the thing created with `docker network create`. The change in 3) would allow a similar thing - when creating a network, you could specify meta-data to select the CIDR from something the IPAM driver knows about. But the idea of 4) is to separate knowledge of addressing from the actual deployment. If you are not using overlays but rather all externally accessible networks then this becomes more relevant.

**Comment by bboreham** [comment]
That's a long way from the function of the current IPAM API. Docker have intentionally carved up the surface into segregated parts, so the network doesn't know about containers, IPAM doesn't know about networks, and so on. I think you need to re-cast your proposal in terms of some higher-level abstraction.

**Comment by johnbelamaric** [comment]
Yeah, I hear your point that IPAM may not be the right place for 4). The use case here is one we have seen in OpenStack and likely will become an issue here too. The problem is that larger operators are having trouble scaling with overlays. So they build out a more traditional L3 network and tie specific subnets to racks (or maybe clusters in this case). I think this can be mostly solved by 3) in that case.

**Comment by johnbelamaric** [comment]
So after spending a bit more time understanding the lib network model I think that 1) and 2) are possibly useful but not really necessary, since they only apply to the bridge network driver. A better solution is just to use a separate network for the external IPs and so you can assign the IPAM at that point.

What is still missing is passing meta-data from lib network to the IPAM driver. Right now, the API serves lib network's purpose of getting subnets and IPs - but doesn't provide enough info to make an external IPAM able to display useful data.

I am looking at adding a few capabilities to publish some of the information that is interesting to external IPAM systems via the API.
