### ISSUE TITLE
Typo for "network not found" error message

### ISSUE THREAD

**Issue by Mierdin** [docker/libnetwork#909]
I have noticed a minor typo in the output of several `docker network` commands, when I try to do something with a network that doesn't exist. Basically, the error message seems to have an extra "null" appended to the end of it:

```
docker network inspect swarm-agent/bridge                                                                                                                                                                                     
Error response from daemon: No such network: swarm-agent/bridgenull
```

**Comment by wenchma** [comment]
@Mierdin what's your docker engine version ? my test result:

    $ docker network inspect swarm-agent/bridge
    []
    Error: No such network: swarm-agent/bridge
