### ISSUE TITLE
Default network driver in help output

### ISSUE THREAD

**Issue by Mierdin** [docker/libnetwork#911]
I noticed that the help output for the `docker network create` command shows the default driver is "bridge", but to my understanding, the default is "overlay". Does this need updated?

```
docker network create --help   

Usage:  docker network create [OPTIONS] NETWORK-NAME

Creates a new network with a name specified by the user

  --aux-address=map[]      auxiliary ipv4 or ipv6 addresses used by Network driver
  -d, --driver=bridge      Driver to manage the Network
  --gateway=[]             ipv4 or ipv6 Gateway for the master subnet
  --help=false             Print usage
  --ip-range=[]            allocate container ip from a sub-range
  --ipam-driver=default    IP Address Management Driver
  -o, --opt=map[]          set driver specific options
  --subnet=[]              subnet in CIDR format that represents a network segment
```

**Comment by Mierdin** [comment]
Just realized this may/may not be impacted by running against a Swarm cluster. In the event that it's a single host, of course the default is "bridge", so maybe this is just one of those things where the user should know that the default is overlay when running against Swarm. Thoughts?

FWIW, I am running this against a Swarm cluster.

**Comment by mavenugo** [comment]
@Mierdin that's correct. its a swarm specific default (and it make sense). The UX displaying bridge as the default may be confusing for some users. we need to check with swarm and docker maintainers on the best approach.
