### ISSUE TITLE
"docker network ls" shows output in different order each time

### ISSUE THREAD

**Issue by patrikerdes** [docker/libnetwork#926]
When doing the command `docker network ls` multiple times, the order of the output is not stable. I suggest that the output is ordered.

To reproduce:
```
# docker network ls
NETWORK ID          NAME                DRIVER
dee57d976e2e        bridge              bridge
8aa8e65d768b        none                null
6d05043c492d        host                host
# docker network ls
NETWORK ID          NAME                DRIVER
8aa8e65d768b        none                null
6d05043c492d        host                host
dee57d976e2e        bridge              bridge
```

I would expect the output to be sorted in some way. That would make it easier to spot any differences in the list between invocations of the command. I don't have any specific suggestion on the order.

Docker version: 1.10.0-rc3, build 08c24cc

**Comment by aboch** [comment]
IMO this is should be taken care by the docker client code, given it is a feature to ease readability for a human user.

**Comment by patrikerdes** [comment]
Ok, I'm closing this issue and writing the same issue on the docker project.
