### ISSUE TITLE
CIDR range for bridge networks (1.10.0-rc2)

### ISSUE THREAD

**Issue by jianghaitao** [docker/libnetwork#927]
__Setup__
```
Ubuntu 14.04.3 LTS
# docker --version
Docker version 1.10.0-rc2, build c1cdc6e
```
__Steps__
```
for i in {1..100}; do docker network create --driver bridge test-br-$i; done
```
__Problems__
Docker host (VM) lost network connectivity and later I found out that the route defined for bridge network above conflicted with my host network unexpectedly. See below 
```
netstat -nr
0.0.0.0         10.11.1.1       0.0.0.0         UG        0 0          0 eth0
10.11.1.0       0.0.0.0         255.255.255.0   U         0 0          0 eth0
172.17.0.0      0.0.0.0         255.255.0.0     U         0 0          0 docker0
172.18.0.0      0.0.0.0         255.255.0.0     U         0 0          0 docker_gwbridge
172.19.0.0      0.0.0.0         255.255.0.0     U         0 0          0 br-68ea8758231c
172.20.0.0      0.0.0.0         255.255.0.0     U         0 0          0 br-f922b0fa61dc
172.21.0.0      0.0.0.0         255.255.0.0     U         0 0          0 br-930b75014169
172.22.0.0      0.0.0.0         255.255.0.0     U         0 0          0 br-268e8bf8c50e
172.23.0.0      0.0.0.0         255.255.0.0     U         0 0          0 br-7e04deff513e
172.24.0.0      0.0.0.0         255.255.0.0     U         0 0          0 br-d8433f9dcec7
172.25.0.0      0.0.0.0         255.255.0.0     U         0 0          0 br-f08ba4b958bb
172.26.0.0      0.0.0.0         255.255.0.0     U         0 0          0 br-4f569ef1a49b
172.27.0.0      0.0.0.0         255.255.0.0     U         0 0          0 br-12fdcd4210c1
172.28.0.0      0.0.0.0         255.255.0.0     U         0 0          0 br-4925ab98bd67
172.29.0.0      0.0.0.0         255.255.0.0     U         0 0          0 br-eb83d0836bfd
172.30.0.0      0.0.0.0         255.255.0.0     U         0 0          0 br-645827e52521
172.31.0.0      0.0.0.0         255.255.0.0     U         0 0          0 br-99604aeee1ba
192.168.16.0    0.0.0.0         255.255.240.0   U         0 0          0 br-a51ecf4694f6
192.168.32.0    0.0.0.0         255.255.240.0   U         0 0          0 br-fca06329a6d3
192.168.48.0    0.0.0.0         255.255.240.0   U         0 0          0 br-5de2ce87854d
192.168.64.0    0.0.0.0         255.255.240.0   U         0 0          0 br-2a6a096f2c92
192.168.80.0    0.0.0.0         255.255.240.0   U         0 0          0 br-bb9784c94e2f
192.168.96.0    0.0.0.0         255.255.240.0   U         0 0          0 br-515801ded7f1
192.168.112.0   0.0.0.0         255.255.240.0   U         0 0          0 br-b5fc0f9f518d
192.168.128.0   0.0.0.0         255.255.240.0   U         0 0          0 br-a5bb7924ccd2
192.168.144.0   0.0.0.0         255.255.240.0   U         0 0          0 br-b619be4d071c
192.168.160.0   0.0.0.0         255.255.240.0   U         0 0          0 br-070cebe0df04
192.168.176.0   0.0.0.0         255.255.240.0   U         0 0          0 br-701bd81fd638
192.168.192.0   0.0.0.0         255.255.240.0   U         0 0          0 br-3578c5ec467a
192.168.208.0   0.0.0.0         255.255.240.0   U         0 0          0 br-a795854f2158
192.168.224.0   0.0.0.0         255.255.240.0   U         0 0          0 br-f1ba42e6469d
192.168.240.0   0.0.0.0         255.255.240.0   U         0 0          0 br-47ec0cbb9aec
```
It looks like by default, the non-default bridges CIDR is from 172.18.0.0 - 172.31.0.0 with mask of  255.255.0.0 , after that, CIDR is all of sudden jump to 192.168.16.0 ... with mask of 255.255.240.0. 

My questions would be 
* How many bridge network can a docker host support if no option is specified when docker network create?
* Is there anyway to control the CIDR range of bridge networks in the Docker configuration / option so above creation of bridge network is better controlled? i.e if defined range is exhausted, an error / warning will be thrown?

**Comment by mavenugo** [comment]
@jianghaitao pls use the `--subnet` option when creating the network.
If these options are not used, libnetwork will automatically choose and assign a subnet range as indicated above.

With the `--subnet` option, you have better control over the CIDR and you can test the limit of number of bridges (which is essentially the linux kernel limit).

**Comment by jianghaitao** [comment]
Yes, I am aware of the --subnet option. I just wondering
- if we can control the overall bridge cidr range in the docker configuration / option thus have a predicable default behavior when no option is specified
- why the jump of cidr and mask?

**Comment by aboch** [comment]
@jianghaitao 

>How many bridge network can a docker host support if no option is specified when docker network create?

32 for local scoped networks like bridge networks (172.17.00/16 - 172.31.0.0/16 + 192.168.0.0/20-192.168.240/20), provided none of the predefined network overlap with any route on your system

> Is there anyway to control the CIDR range of bridge networks in the Docker configuration / option so above creation of bridge network is better controlled?

See @mavenugo 's response

> [...] i.e if defined range is exhausted, an error / warning will be thrown?

Yes:
`Error response from daemon: failed to parse pool request for address space "LocalDefault" pool "" subpool "": could not find an available predefined network
`

**Comment by aboch** [comment]
@jianghaitao 

> why the jump of cidr and mask?

We pick from the reserved private subnets.

**Comment by jianghaitao** [comment]
@aboch Thanks for the clarification. Did not find these in the related Docker networking documentation.

**Comment by aboch** [comment]
@jianghaitao 

I know, it's always hard to keep documentation up to date with code changes.
You can find at
https://github.com/docker/libnetwork/blob/master/ipamutils/utils.go#L20
https://github.com/docker/libnetwork/blob/master/ipamutils/utils.go#L33
the code responsible to define the predefined networks.
Default IPAM driver uses that to self assign an address pool for request on local and global address space.

**Comment by jianghaitao** [comment]
@aboch Thanks a lot!
