### ISSUE TITLE
Create dummy interface inside the container?

### ISSUE THREAD

**Issue by deitch** [docker/libnetwork#932]
Is it possible to use the network plugin API to create a dummy interface inside the container? 

It is unclear to me if the remote driver plugin actually **creates** the endpoint, or if it **instructs** libnetwork to do so with the response to the API call `network.createEndpoint()` 

https://github.com/docker/libnetwork/blob/master/docs/remote.md#create-endpoint implies the latter, but https://github.com/docker/libnetwork/blob/master/docs/design.md says 

> An implementation of an Endpoint could be a veth pair, an Open vSwitch internal port or similar. 

I have a hard time seeing how the plugin could create the actual endpoint since:

1. It is not given a container identifier in the `createEndpoint()` call
2. The plugin could be remote (i.e. on a different host)

How would I implement a dummy interface for a network endpoint?

**Comment by chenchun** [comment]
> Is it possible to use the network plugin API to create a dummy interface inside the container?

Yes, you can. In the [join response](https://github.com/docker/libnetwork/blob/master/docs/remote.md#join), you can tell libnetwork the dummy device name through `InterfaceName.SrcName` and the name prefix inside container through `InterfaceName.DstPrefix`.

*The entries in InterfaceName represent actual OS level interfaces that should be moved by LibNetwork into the sandbox; the SrcName is the name of the OS level interface that the remote process created, and the DstPrefix is a prefix for the name the OS level interface should have after it has been moved into the sandbox (LibNetwork will append an index to make sure the actual name does not collide with others).*

But what is your intention of creating a dummy interface inside a container?

> The plugin could be remote (i.e. on a different host)

It's can't be currently. Here's the plugin document 
[*Network plugins implement the Docker plugin API and the network plugin protocol.*](https://docs.docker.com/engine/extend/plugins_network/#write-a-network-plugin)

[*A docker plugin is a process running on the same docker host as the docker daemon, which registers itself by placing a file in one of the plugin directories described in Plugin discovery.*](https://docs.docker.com/engine/extend/plugin_api/#what-plugins-are)

**Comment by deitch** [comment]
> Yes, you can. In the join response, remote plugin can tell libnetwork the dummy device name through InterfaceName.SrcName and the name prefix inside container through InterfaceName.DstPrefix.

I get it. So my driver would create the dummy interface, say, `dummy10`, then hand it back in the join response with 

````json
"InterfaceName": {
        "SrcName": "dummy10",
        "DstPrefix": "eth"
    },
````

which would mean, "take dummy10 and put it in the container as an interface with a prefix of 'eth' ". Is that it?

> But what is your intention of creating a dummy interface inside a container?

I can think of a number of use cases, but in the particular case at hand, there are several processes inside the container, call them S and T1 through T10. S is sending voluminous traffic to T1-T10. For simplicity, it is streaming using udp multicast. Since it never needs to leave the container, it would be very wasteful over the normal interface (and hate to think what several of these would do on the network unnecessarily), so we just set a dummy interface, and route the particular multicast IP to that interface. All traffic is kept internal.

>> The plugin could be remote (i.e. on a different host)

> It's can't be currently.

I am not sure you are right. I believe the remote API supports any URL in the `.json` file for the API, and the docker engine always talks http - locally or over the network - to it. See the example at https://docs.docker.com/engine/extend/plugin_api/#json-specification as well as https://github.com/docker/libnetwork/blob/master/docs/remote.md

That is the part I didn't get. If a network plugin is supposed to be able both to create networks and to create endpoints, which then get passed back to the engine and put in the container (as you explained above), how could it do that remotely?

**Comment by chenchun** [comment]
> which would mean, "take dummy10 and put it in the container as an interface with a prefix of 'eth' ". Is that it?

Yes, this is what libnetwork does.
For your use case, you actually want S and T1 through T10 to communicate within a container, so why not create a dummy interface through the init process of the container? Is it really need to create a plugin?

**Comment by deitch** [comment]
>> which would mean, "take dummy10 and put it in the container as an interface with a prefix of 'eth' ". Is that it?

> Yes, this is what libnetwork does.

Thanks for the clarification. Very helpful.

> why not create a dummy interface through the init process of the container? Is it really need to create a plugin?

You mean the init process inside the container? You cannot:

````
Avi-Deitcher-MacBook-Air:~ adeitcher$ docker run -it centos:7 bash
[root@7d9e866a555e /]# ip link add dummy0 type dummy
RTNETLINK answers: Operation not permitted
````

How would the truly remote (i.e. not local to host) API work? Is the assumption that it has some direct access to the host and will construct the interfaces as necessary, even when coming over remote?

**Comment by chenchun** [comment]
> You mean the init process inside the container? You cannot:

> ```
> Avi-Deitcher-MacBook-Air:~ adeitcher$ docker run -it centos:7 bash
> [root@7d9e866a555e /]# ip link add dummy0 type dummy
> RTNETLINK answers: Operation not permitted
> ```

You have to add `--cap-add=NET_ADMIN` option

> How would the truly remote (i.e. not local to host) API work?

It's plugin's job to create interfaces they want on the local host. So I think a remote network plugin can't work.

> The remote API supports any URL in the .json file for the API, and the docker engine always talks http - locally or over the network - to it.

Yes, it can be a remote URL. But the plugin document clearly states that a docker plugin is a process running on the same docker host as the docker daemon. That is the design.

**Comment by deitch** [comment]
> You have to add --cap-add=NET_ADMIN option

Yes, which I do not want to do for a standard container, of which I may have many, which is why I would want a network plugin to do it.

> Yes, it can be a remote URL. But the plugin document clearly states that a docker plugin is a process running on the same docker host as the docker daemon. That is the design.

So the docs are somewhat confusing. No surprise there. :-) 

Thanks @chenchun
