### ISSUE TITLE
Proposal: Pluggable DNS service discovery

### ISSUE THREAD

**Issue by clinta** [docker/libnetwork#936]
In #767 it was suggested that the DNS service discovery should be pluggable. This issue is to discuss the requirements and interface for such a plugin. Most of these ideas are modeled after the NetworkDriver API.

DNS plugins should be implemented using the docker plugin API, responding to `Plugin.Activate` with `{ "Implements": ["DNSDriver"] }`. When any container is started with `--dns-driver=drivername` docker should POST to `/DNSDriver.Publish` with details about the container, including at least the container Name, HostName, NetworkMode, and the NetworkID, IPAddress and GlobalIPv6Address for each network attached to the container. It should also contain the list of dns servers passed to the container via the `--dns` option as well as an arbitrary list of options which can be passed to the DNS plugin by the user using the `--dns-opt=` flag. The plugin should respond to this request with an array of options to be added to the containers resolv.conf.

The `--dns-driver` option should expose the 2 default drivers that are built in to docker, as well as a meta driver `default`. The builtin `none` driver uses the current behavior of the docker0 network, where the contents of --dns, or of the hosts resolv.conf are propagated into the container, and docker does nothing with dns traffic or service discovery. The builtin `docker` driver uses the current default behavior of custom networks, using the built in docker DNS service which configures the container's resolv.conf with 127.0.0.11 and adding iptables rules to NAT that traffic to a high port on the host where the service is listening. The meta-driver, `default`, which is the default if this option is unspecified, will use the `none` driver on the docker0 network and the `docker` driver on any other networks. The behavior of the `default` driver may change with future docker versions.

**Comment by mavenugo** [comment]
@clinta thanks for the proposal.
one general question. With the existing support for `--dns`, the DNS lookup can be expanded beyond the embedded DNS server. Is there a specific functionality that you see that is fundamentally different (and will always be different) that calls for a need for a pluggable driver which in turn will provide a `dns server` IP back tot he container. And who and how will that DNS server be managed ? and with the current network isolation mechanisms in place, how will it work ? 

Can you please add more details on the big picture on how it is intended to be used and how can it guarantee plugin portability without impacting the apps.

**Comment by clinta** [comment]
I'm supposing that if a plugin could not pass a dns server back to the container, then the container would always get 127.0.0.11 as it's dns server, and then the docker daemon would pass those dns requests elsewhere. This approach doesn't work for me for a couple of reasons.

1. It depends on docker manipulating iptables. I run docker with `--iptables=false` and strictly manage the firewalls on my hosts, regularly restoring them from a template managed by my configuration management infrastructure.

2. It is another IPv4 dependancy introduced into docker, while I'm trying to work toward an IPv6 only datacenter.

3. Some dns functionality is dependant on being able to identify the requesting IP. DNS logging is used as an early indicator of a security breach. If every request comes from the docker host's IP it is not clear if one container is compromised or if the entire host is. Obviously this is moot for users who do not run with `--ip-masq=false`, but it is important to me. I also run multiple user defined networks with different IP ranges. I can use these ranges and bind views to serve different results to different networks. This also isn't possible if the request is being proxied by the host.

All of these conserns solved by allowing the plugin to specify what options are placed in the containers resolv.conf and allowing the plugin to manipulate the firewall if that is required depending on where the plugin is listening.

How the dns server will be managed is all up the user. It is also up to the user to be sure that their particular dns plugin is compatible with the network mode they're using. If they are running on an isolated network, then they need to use a plugin which returns a localhost address and manipulates IPTables. I am not proposing changing any default behavior, so if the user uses the default options all will work fine. But just as docker allows users to run without ip masquerading with the understanding that these users need to know how to configure routing on their own, users should be allowed to customize their dns with the understanding that it is possible to create configurations that are incompatible.

I also think preserving the none driver functionality is useful. If someone doesn't need registration and simply wants to pass chosen dns servers into the container, having to run a plugin just to parse and send back options that already exist in docker seems unnecessary.

As for a big picture, here's roughly what my docker network looks like.

I have 8 hosts which run various containers. These containers exist on various user defined networks using my [vxlan plugin](https://github.com/clinta/docker-vxlan-plugin). These docker hosts run with `--iptables=false and --ip-masq=false`. The vxlan networks that run on the host exist on our core datacenter router and are routable to the rest of our datacenter without any NAT. They only NAT in our network is at our edge router to the internet.

We rely heavily on functioning DNS including views and logging and for these reasons run our own internal BIND resolvers.

I would like to have dns entries for containers automatically added to our BIND servers, so the dns plugin I have in mind to write is one that sends RFC 2136 DNS updates to our BIND server when containers are started. This would be a great improvement over sending the updates from the container itself because I can use secure updates without ever giving the container access to the keys.

**Comment by mrichmon** [comment]
It might be useful to include some kind of hostname map specification to control how the DNS updates are generated. For example:

==publish nginx containers to .public zone==
image-match: "nginx"
zone: ".public"

==publish DB containers to .internal zone using container name===
image-match: "db" | "mysql"
zone: ".internal"
record: "${NAME}"

**Comment by bboreham** [comment]
Referencing https://github.com/docker/docker/issues/19474#issuecomment-209357935 where I discuss some possibilities for a pluggable DNS.
