### ISSUE TITLE
Add support for firewalld integration

### ISSUE THREAD

**Issue by mrjana** [docker/libnetwork#96]
Add support for host configurations where firewalld is the master iptables manager

**Comment by dave-tucker** [comment]
What about ufw?

**Comment by dave-tucker** [comment]
... explaining myself further... 
where there are rule managers in place like firewalld and ufw, perhaps it would make sense for us to describe rules in abstract form and to have a driver framework for "firewalls".

**Comment by mrjana** [comment]
@dave-tucker Yes, we need a generic framework to interact with all kinds of rule managers out there. But this issue was created to track a much immediate need because some sort of firewalld support was added to iptables in docker/docker which we need to integrate with before the docker/docker PR :-)

**Comment by dave-tucker** [comment]
Closed by https://github.com/docker/libnetwork/pull/278
