### ISSUE TITLE
Proposal: Default gateway priority with few user define networks

### ISSUE THREAD

**Issue by mort1k** [docker/libnetwork#960]
When connect container to multiple networks is not possible to select required the default gateway. Is 
it possible to specify the container to use a gateway, can be with option --use-network-gateway?!

The current behavior of the gateway is set in alphabetical order of connected networks from the list in "Networks" container option.

**Comment by mort1k** [comment]
duplicate: https://github.com/docker/docker/issues/20179

**Comment by aboch** [comment]
Thanks @mort1k 
Yes this issue is a duplicate of https://github.com/docker/docker/issues/20179.

Given the needed code changes are in docker/docker code only, I would close this issue and leave the other one open.

Thanks,
