### ISSUE TITLE
index out of range in etchosts.Delete

### ISSUE THREAD

**Issue by sperka** [docker/libnetwork#966]
In certain cases there is a docker service restart due to an "index out of range" runtime error when using weave net with mesos/marathon to deploy containers.

Log:

Container 8812916ec6104b2706396c779434d31cb10574160a223364c2c57f7135ace860 failed to exit within 0 seconds of SIGTERM - using the force 
panic: runtime error: index out of range

goroutine 315 [running]:
github.com/docker/libnetwork/etchosts.Delete(0xc8216ebc00, 0x61, 0xc820a721c0, 0x1, 0x1, 0x0, 0x0)
	/usr/src/docker/vendor/src/github.com/docker/libnetwork/etchosts/etchosts.go:154 +0x543
github.com/docker/libnetwork.(*sandbox).deleteHostsEntries(0xc820d1bc00, 0xc820a721c0, 0x1, 0x1)
	/usr/src/docker/vendor/src/github.com/docker/libnetwork/sandbox.go:815 +0x6c
github.com/docker/libnetwork.(*endpoint).sbLeave(0xc820085900, 0x7ff74622eae0, 0xc820d1bc00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/src/docker/vendor/src/github.com/docker/libnetwork/endpoint.go:599 +0xb35
github.com/docker/libnetwork.(*endpoint).Leave(0xc821681100, 0x7ff74622eae0, 0xc820d1bc00, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/src/docker/vendor/src/github.com/docker/libnetwork/endpoint.go:536 +0x1bf
github.com/docker/libnetwork.(*sandbox).delete(0xc820d1bc00, 0xc8215b7b00, 0x0, 0x0)
	/usr/src/docker/vendor/src/github.com/docker/libnetwork/sandbox.go:199 +0xad4
github.com/docker/libnetwork.(*sandbox).Delete(0xc820d1bc00, 0x0, 0x0)
	/usr/src/docker/vendor/src/github.com/docker/libnetwork/sandbox.go:166 +0x32
github.com/docker/docker/daemon.(*Daemon).releaseNetwork(0xc820156780, 0xc820d1b500)
	/usr/src/docker/.gopath/src/github.com/docker/docker/daemon/container_operations_unix.go:1013 +0x4f1
github.com/docker/docker/daemon.(*Daemon).Cleanup(0xc820156780, 0xc820d1b500)
	/usr/src/docker/.gopath/src/github.com/docker/docker/daemon/start.go:159 +0x3d
github.com/docker/docker/container.(*containerMonitor).Close(0xc8215d0680, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/container/monitor.go:127 +0x68
github.com/docker/docker/container.(*containerMonitor).start.func1(0xc8216cbd5f, 0xc8215d0680, 0xc8216cbd60)
	/usr/src/docker/.gopath/src/github.com/docker/docker/container/monitor.go:158 +0xaa
github.com/docker/docker/container.(*containerMonitor).start(0xc8215d0680, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/container/monitor.go:239 +0xbc5
github.com/docker/docker/container.(*containerMonitor).(github.com/docker/docker/container.start)-fm(0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/container/monitor.go:101 +0x2e
github.com/docker/docker/pkg/promise.Go.func1(0xc8216b2ae0, 0xc821652280)
	/usr/src/docker/.gopath/src/github.com/docker/docker/pkg/promise/promise.go:8 +0x1d
created by github.com/docker/docker/pkg/promise.Go
	/usr/src/docker/.gopath/src/github.com/docker/docker/pkg/promise/promise.go:9 +0x5d

**Comment by sanimej** [comment]
@sperka Can you add the docker info output ?

**Comment by sperka** [comment]
@sanimej sorry I completely forgot to provide that info.

$ docker version
Client:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:27:08 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:27:08 2016
 OS/Arch:      linux/amd64

$ docker info
Containers: 25
 Running: 0
 Paused: 0
 Stopped: 25
Images: 5
Server Version: 1.10.1
Storage Driver: devicemapper
 Pool Name: docker-253:1-525513-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.857 GB
 Data Space Total: 107.4 GB
 Data Space Available: 38.21 GB
 Metadata Space Used: 5.53 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.142 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.77 (2012-10-15)
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: host bridge null
Kernel Version: 3.13.0-52-generic
Operating System: Ubuntu 14.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.861 GiB
Name: mesos-slave1
ID: FFYP:ZNVS:6JP5:CADZ:I7VX:N4C6:L7NZ:W4C3:QBKW:NBBT:3CJA:HUJC
WARNING: No swap limit support
