### ISSUE TITLE
Allow user to disable some driver intialization

### ISSUE THREAD

**Issue by mYmNeo** [docker/libnetwork#981]
Our machine's kernel does not have module about nat.So we set `-b none` to docker daemon, the daemon tried to disable bridge network.But libnetwork cannot notice about this, `removeIPChain` and `setupIPChain` raised an erro while intialization, then the daemon failed to start.

To solve this problem, I add a option to let libnetwork disable some driver initialization. #980

**Comment by aboch** [comment]
@mYmNeo On start, daemon will always look for the default bridge network and delete it if present.
Even with #1043 changes, the bridge driver will be initialized when libnetwork receives the Delete() call.

Would starting the daemon with `--iptables=false` be a valid option for you ?

**Comment by mYmNeo** [comment]
@aboch yes, I finally added `--iptables=false` to achieve this.
