### ISSUE TITLE
unify license

### ISSUE THREAD

**Issue by onlyjob** [docker/libnetwork#991]
Licensing docs under different license seems unnecessary. Why?
[There is a good reason to use one license](https://people.debian.org/~bap/dfsg-faq.html#docs).

Could the whole package be (re-)licensed under Apache-2.0 please?

Thanks.

**Comment by thaJeztah** [comment]
I think this is the same discussion we had on https://github.com/docker/libkv/issues/50 ?

**Comment by onlyjob** [comment]
Discussion in libkv was focused on incorrect license grant which is certainly a problem here as well.
